### ISSUE TITLE
Tapahtumalistaussivu

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#1]
Osallistuvan budjetoinin alustalle on toivuttu sitä, että kaikkiin tapahtumiin pääsisi yhdestä paikasta - riippumatta siitä mihin prosessiin ne liittyvät.  Tämä on nyt toteuttu tekemällä Tapahtumat-niminen kehitysryhmä, mutta silloin tapahtumat eivät näy suurpiirien tapahtumavälilehdellä.  Onko järkevästi mahdollista saada helposti toimintoa, joka mahdollistaisi tapahtumien tarkastelun sekä prosessikohtaisesti että yhteisenä listauksena?  Siis ilman, että ne syöttää kahdesti järjestelmään. :)

**Comment by katjahenttonen** [comment]
Tajusin jälkijättöisesti, että tämän voisi toteuttaa höydyntämällä prosessiryhmää.  Eli saman prosessiryhmän tapahtumat pitäisi saada listattua jossain kerralla. Kommentoin samaa MetaDecidimissä.

**Comment by ahukkanen** [comment]
Onnistuu kustomoinnilla, mutta tuskin saamme tätä Decidimin päätyyn ajettua kovin nopeasti ainakaan. Tuo pitäisi päättää, että näytetäänkö aivan kaikki tapahtumat vai vain tiettyyn prosessiryhmään liittyvät, kuten ehdotat yllä. Implementaatiotasolla on helpompaa näyttää kaikki, mutta molemmat vaihtoehdot kyllä onnistuvat teknisesti.

Mikäli näytetään prosessiryhmätasolla, niin onko tuo kyseinen prosessiryhmä aina kovakoodattuna lähdekoodiin vai pitääkö tuolta kyseiseltä sivulta voida jotenkin filtteröidä tapahtumia per prosessiryhmä?

**Comment by katjahenttonen** [comment]
En missään tapauksessa suunnitellut mitään kovakoodauksia.  Tapahtumien filtteröinti prosessiryhmittäin olisi meidän kannalta pidemmän päälle paras ratkaisu, mutta kaikkien tapahtumien listauksella pääsisimme jo pitkälle. Eli kaikkien tapahtumien näyttäminen riittää jos sen saa helpommin toteuttua.

**Comment by katjahenttonen** [comment]
Ilmeisesti valikoiden kustomointi nykyisellään on pajon vaikeampaa kuin olin ajatellut. Kuvittelin, että tämä olisi jotenkin parametrisoitavissa. Toivottavasti tähän saadaan Decidimin päässä muutosta. Siihen asti ylävalikko on ehkä viisainta pitää nykyisellään.  Kaikki tapahtumat listaava sivu olisi hyödyllinen, mutta linkin siihen ei ole pakko olla ylävalikossa.  Etsitään sillä parempi paikka.

**Comment by katjahenttonen** [comment]
MetaDecidemisistä voisi varmaan vetää pois tuon ehdotuksen tapahtumasivusta ( https://meta.decidim.org/processes/roadmap/f/122/proposals/13125).  Sopivassa kohtaa voisimme miettiä koko Decidim-yhteisön kannalta järkevän ehdotuksen ja laittaa sitten uudestaan.

**Comment by ahukkanen** [comment]
Valikkoa voi kyllä kustomoida kooditasolla instanssispesifisti, mutta UI-konfigurointia näille ei ole, kuten CMS-järjestelmissä. Tuossa Metadecidimin ehdotuksessa ehdotan juuri sitä, että valikko olisi käyttöliittymästä kustomoitavissa jokaiselle instanssille, joka helpottaisi näitä muutoksia.

Näissä kooditason valikkoviittauksissa kuitenkin on haastavaa, jos pitää viitata tiettyyn käyttöliittymästä luotuun entiteettiin, kuten prosessiin tai prosessiryhmään. Näissä viittaukset pitäisi tehdä ID-numeroilla, jotka voivat erota instanssikohtaisesti, eli ne eroavat jokaiselle applikaation instanssille (tuotanto, ninja, ideapaahtimo, kehitysympäristö).

Näissä viittauksissa staattiseen sivuun sinänsä ei ole suurempaa ongelmaa, kuten tässä tapauksessa.

**Comment by ahukkanen** [comment]
> MetaDecidemisistä voisi varmaan vetää pois tuon ehdotuksen tapahtumasivusta ( https://meta.decidim.org/processes/roadmap/f/122/proposals/13125). Sopivassa kohtaa voisimme miettiä koko Decidim-yhteisön kannalta järkevän ehdotuksen ja laittaa sitten uudestaan.

Ehdotuksia, jotka ovat jo keränneet ääniä, ei kaiketi voi vetää pois.

**Comment by katjahenttonen** [comment]
Ok, kiitos lisätiedoista.  Ehdotuksesi kustomoitavuudesta oli hyvä ja tarpeellinen,  olen yrittänyt saada kollegoitani äänestämään sitä (toistaiseksi turhaan, pitää muistutella tästä). Sen sijaan kaikkien instassin tapahtumien listaus yhdellä sivulla ei ole ehkä Decidimin kannalta fiksuin mahdollinen ominaisuus (kuten itsekin kommentoit), joten  edistäisin pitämmällä tähtäimellä mieluummin prosessiryhmäkohtaista listausta.  Ja, kiitos, hyvä tietää, että viittaukset staattiseen sivuun ovat suhteellisen ongelmattomia.

**Comment by katjahenttonen** [comment]
Tämä pitää avata uudestaan.  Tarvitsemme tapahtumalistauksen asap, nyt joudumme syöttämään samat tapahtumat kahteen paikkaan (prosessikohtaisesti kunkin alueen tapahtumat sekä  kehitysryhmälle kaikki tapahtumat).  Tässä ei ole oikein järkeä ja tapahtumat on muutenkin vähän typerän näköisiä kehitysryhmässä. Eli kaikkia tapahtumien listaus tarvitaan ja pidemmän päälle pitää voida suodattaa prosessiryhmäkohtaisesti myös.

**Comment by ahukkanen** [comment]
Sovimme, että toteutetaan yleinen tapahtumalistaussivu, joka listaa kaikki järjestelmästä löytyvät tapahtumat, mukaan lukien:

- Kaikkien prosessien tapahtumat
- Kaikkien ryhmien tapahtumat

**Comment by ahukkanen** [comment]
Tämä näyttäisi olevan jo implementoitu Decidimin coreen versioon 0.15. Decidim-päivityksen pitäisi siis tuoda myös tämä ominaisuus mukanaan.

Ks.
https://github.com/decidim/decidim/issues/3700

Esimerkki:
https://meta.decidim.org/
https://meta.decidim.org/meetings/

@katjahenttonen Onko tuo riittävä tähän tarkoitukseen?

Liittyy: #42

**Comment by katjahenttonen** [comment]
Hieno juttu!  Kyllä tämä näyttäisi medän kannalta toimivalta ratkaisulta.  Tuon Decidim-versiopäivityksen voisi varmasti nyt nostaa ihanprioritettilistan kärkeen.
