### ISSUE TITLE
Ideapaahtimon visumuutokset

### ISSUE THREAD

**Issue by ahukkanen** [City-of-Helsinki/decidim-helsinki#10]
Ideapaahtimo-instanssiin halutaan seuraavat päävärit, jotta se erottuu Osallistu-alustasta.

VALKOINEN
Pantone White
CMYK 0, 0, 0, 0
RGB 255, 255, 255
#FFFFFF
RAL 9003

KULTA
Pantone 871
CMYK 10, 30, 75, 15
RGB 194, 162, 81
#C2A251
RAL 1036

Suunniteltava, miten toteutetaan. Ideapaahtimon voisi ehkä haarauttaa omaan repositorioonsa.

**Comment by ahukkanen** [comment]
Toistaiseksi sovimme seuraavaa @katjahenttonen kanssa:

- Ylä- ja alapalkkiin väriksi kulta (yllä). Teksti kullan päällä pitää ehkä vaihtaa mustaksi.
- Prosessien listaukseen taustalle vaalean harmaa (#ebedf1) tai hopea (#dedfe1)

Näillä muutoksilla ajetaan uusi versio Ideapaahtimoon ja pyydetään tarkastamaan värien miellyttävyys.

Tekninen toteutustapa näille on pienimuotoinen puukotus, jolla instanssispesifisti voi yliajaa perustyylejä. Mikäli Ideapaahtimo halutaan ottaa laajempaan käyttöön myöhemmin, kehitys voidaan haarauttaa omaan repositorioonsa.

**Comment by katjahenttonen** [comment]
Tässä @ahukkanen  tarkemmat speksit ulkonäköön:

Kaikki tekstit mustalla (samoin Helsinki-tunnus)
Taustaväriksi vaihdellen kulta ja valkoinen
- yläpalkkiin kulta
- kuvan alla olevaan osioon valkoinen (kuten nytkin)
- vihreä osio kultaiseksi
- alin osio valkoiseksi

**Comment by ahukkanen** [comment]
Tämä toteutettu Ideapaahtimoon.

Epäselvyys "alimmasta osiosta", päädyimme seuraavaan:
- Footerissa kulta
- Prosessilistausten taustalla valkoinen, teksti mustalla
