### ISSUE TITLE
Popup ja virheviestin muuttaminen

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#100]
Muutamia popup ja virheviestejä pitäisi muuttaa selkäemmiksi kuten aiemmin oli puhetta Slackisa. Sain näille nyt myös käännökset, ks. liite. [muutoksiavirhejapopupviesteihin.docx](https://github.com/City-of-Helsinki/decidim-helsinki/files/3646945/muutoksiavirhejapopupviesteihin.docx).

**Comment by ahukkanen** [comment]
Termit on nyt muutettu.

Tein varmennuksiin liittyvät termimuutokset termikustomoinnin kautta. Löytyvät setistä "Varmennuksiin liittyvät termit".

Lisäksi huomasin myös popupin otsikossa seuraavan termin, joka on muutettu:
Varmennus vaaditaan -> Tunnistautuminen vaaditaan / Identifiering krävs / Identification required

Tätä voi tarvittaessa muuttaa suoraan termikustomoinnista.

**Comment by katjahenttonen** [comment]
Kiitos paljon!  Yritin itse itse muuttaa noita termikustomoinnin kautta, mutta en jostain syystä löytänyt oikeita käännösavaimia.  Nyt kun oot vienyt ne tuonne niin voidaan toki itse ylläpitää.
