### ISSUE TITLE
"Määraha" on ylittynyt jos yrittää äänestää yli viittä projektia

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#102]
Äänimäärä per henkilö -kenttä vaikuttaa edelleen ei-toivotulla tavalla, eli tulee virheilmoitus "määräraha on ylittynyt", vaikka oikeasti määraha ei ole ylittynyt vaan käyttäjä yrittää äänestää useampaa kuin viittä projektia.  Tämä siis testauksessa löytynyt ongelma, jonka OSP  vakuutti korjanneensa. Korjaus ei joko toimi tai sitten sitä ei ole vielä ajattu meidän tuotantoon.  Olisiko helpoin work-around päivittää kentän arvo suoraan tietokannassa riittävän korkeaksi esim. 50?

**Comment by katjahenttonen** [comment]
Tämän sain siis aiemmin kierrettyä siten, että vaihdon vaan kentän "äänimäärä per henkilö"(eng. total projects) arvon äänestyskomponentin asetuksissa tarpeeksi suureksi. Mut nyt enää sitä ei voi vaihtaa suoraan käyttöliittymästä kun ääni o tullut.

**Comment by ahukkanen** [comment]
Tämä on nyt korjattu.
