### ISSUE TITLE
Henkilötodistuksen tyyppeihin ajo- ja KELA-kortit

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#103]
Lomakkeeseen "Esiinny uutena hallituna käyttäjänä" pitäisi saada henkilötodistuksen tyyppi pudotusvalikkoon:  ajokortti ja KELA-kortti.  Nämä ovat meidän systeemissä sallittuja henkilötodistuksia vaikka eivät käykään virallisissa vaaleissa. Tämä on määrittelyasia, joka uonohtui minulta.

**Comment by ahukkanen** [comment]
Nämä valinnat löytyvät nyt kyseisestä pudotusvalikosta.
