### ISSUE TITLE
mPassID-kirjautuminen ei toimi jos kielenä ruotsi tai englanti

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#105]
mPassID-tunnistatuminen ei toimi, jos Omastadissa kielenä ruotsi tai englanti.  Heti kun on klikannut "Wilma ID for school students" tai "Wilma för elever" niin käyttäjä ohjautuu mPassID:n sivuille, jossa seuraava virheilmoitus: "The login service was unable to identify a compatible way to respond to the requested application. This is generally to due to a misconfiguration on the part of the application and should be reported to the application's support team or owner."

**Comment by ahukkanen** [comment]
Tämä on nyt korjattu pikafiksillä, joka poistaa sen kielen paluuosoitteesta.

Tätä pitää vielä katsoa hieman tarkemmin, koska tuo paluuosoite pitää aina täsmätä siihen, mikä näihin molempiin palveluihin on määritetty (MPASSid ja Suomi.fi).

Decidim kyllä muistaa käyttäjän aikaisemmin valitseman kielen, mutta ongelmana on edelleen näissä kirjautumispalveluissa näkyvä kieli, jonka pitäisi täsmätä. Tämä vaatii vielä lisää säätöä.

**Comment by ahukkanen** [comment]
Tämä on nyt korjattu alla oleviin gemeihin (omniauth-suomifi, omniauth-mpassid) ja pikafiksi on poistettu samalla käytöstä, kun sitä ei enää tarvita.

Käytössä oleva kielikoodi välitetään nyt Suomi.fi:lle, eli myös sen käyttöliittymä näkyy sillä kielellä, millä OmaStadikin. Suomi.fi tukee kaikkia samoja kieliä, jotka ovat käytössä OmaStadissa.

MPASSid tukee suomea ja ruotsia, mutta kielikoodia sinne ei lukuisista yrityksistä huolimatta näytä pystyvän välittämään. MPASSid:n kirjautumissivu tulkitsee halutun kielen käyttäjän selaimen kieliasetuksen mukaan, joka toiminee useimmissa tapauksissa.

Tiedustelen vielä MPASSid:ltä, onko tuossa SAML-rajapinnassa olemassa mitään tapaa välittää kielikoodia. Dokumentaatiossa sellaisesta ei ole mainintaa.

**Comment by ahukkanen** [comment]
MPASSid:ltä tuli vastaus, että kielikoodia ei voi nykyään välittää kirjautumissivulle, vaan se tulkitaan aina käyttäjän selaimen kieliasetuksen mukaan.

Toistaiseksi siis kirjautumissivun kieli voi siis vaihtua, jos OmaStadissa on valittu esim. ruotsi kieleksi ja käyttäjän selaimen kieliasetuksen preferoitavana kielenä on suomi. Tässä tapauksessa siis kirjautumissivu näkyy suomeksi, vaikka OmaStadissa oli valittu ruotsi.

MPASSid lisäsi ehdotuksen kielikoodin välityksestä backlogiinsa, eli tämä voi jossain vaiheessa muuttua, mutta nykyään tuolle ei ole mitään ratkaisukeinoa.

**Comment by katjahenttonen** [comment]
Ok, kiitos selvityksestä, tämä riittää, kaikki pääsevät nyt kirjautumaan ja kielikin toimii useimmilla.
