### ISSUE TITLE
Ideapaahtimon pävitys uusimaan Decidim-versioon

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#107]
Ideapaahtimon voisi päivittää uusimpaan Decidim-versioon ja laittaa samalla Snoobi-analyytikan.  Snoopiskripti on liitteenä.  Ensi maananantaina aamupäivällä odotetaan käyttöpiikkiä, joten silloin päivitystä ei kannnata tehdä, paras päivitysaika ehkä iltaisen klo 16 jälkeen.
[Snoobi skripti_ideapaahtimo_hel_fi.txt](https://github.com/City-of-Helsinki/decidim-helsinki/files/3716775/Snoobi.skripti_ideapaahtimo_hel_fi.txt)

**Comment by ahukkanen** [comment]
Ideapaahtimo on nyt päivitetty samaan versioon kuin OmaStadi.

Decidimistä on julkaistu viime viikolla uusi versio (0.19) ja tämä kannattanee päivittää äänestyksen päätyttyä. Tästä voisi tehdä erillisen issuen.

**Comment by ahukkanen** [comment]
Snoobi-seuranta lisätty myös Ideapaahtimoon.
