### ISSUE TITLE
Ohjeviesti "Valitse suurpiiri" popup -ikkunaan

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#108]
Slack-keskusteluun viitataan lisätään Valitse suurpiiri-valikkoon ohjeteksti.

"Voit äänestää koko Helsingin suunnitelmista ja valitsemasi suurpiirin suunnitelmista.  Sinulle ehdotetaan kotiosoitteeesi postinumeron (tai Wilma-tunnistautuvilla koulun postinumeron) mukaista suurpiiriä, mutta voit vaihtaa sen alla olevasta putodusvalikosta.  Jos haluat äänestää tiettyä suunnitelmaa, tarkista etukäteen minkä suurpiirin alueella se sijaitsee.  Jos haluat vaihtaa tässä tekemäsi valinnan jälkikäteen, katso ylävalikosta Ohjeet."

You can vote both on the plans for entire Helsinki and plans for the district you select below. The service automatically suggests a major district based on your postal code (or postal code of  your school if you identify with Wilma), but you can change it using the drop-down menu. If you want to vote for a particular plan, please check beforehand what districts it belongs to.  If you want to change the district later, please see Instructions.

Dur kan rösta i det stordistrikt som du väljer och dessutom hela Helsingfors röstningsområde. Programmet föreslår som standard ditt postnummers stordistrikt, men du kan om du vill ändra på röstningsområdet i rullgardinsmenyn. Om du vill rösta för en viss plan, vänligen se i förväg vilka distrikt den tillhör. Om du vill ändra distriktet senare, se Instruktioner.

**Comment by ahukkanen** [comment]
Tämä on nyt lisätty tuotantoon ja ninjaan.
