### ISSUE TITLE
Äänestystilastot

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#109]
Tarvitaan yksityiskohtaiset tilastot äänestyksestä 31.10 jälkeen seuraavasti.  Tilastot eivät sisällä henkilötietoja ja ne voi lähettää esim salasanan suojatussa zip-paketissa sähköpostin liitteenä.

Suomi.fi tunnistauneet ja toimipisteissä henkilöpapereilla tunnistautuneet (osbu):

- Prosessin ID
- Prosessin nimi (suomeksi)
- Prosessin URL
- Äänen ID (tämän avulla voi erotella annetut äänet, koska riveittäin on kaikki ääneen valitut projektit)
- Äänestetyn projektin ID
- Äänestetyn projektin nimi (suomeksi)
- Äänestetyn projektin URL
- Sukupuoli
- Postinumero (osalla tyhjä)
- Ikä (export-hetkellä)

Wilma-tunnuksilla tunnistautuneista seuraavat tiedot (osbu+ruuti):

- Prosessin ID
- Prosessin nimi (suomeksi)
- Prosessin URL
- Äänen ID (tämän avulla voi erotella annetut äänet, koska riveittäin on kaikki ääneen valitut projektit)
- Äänestetyn projektin ID
- Äänestetyn projektin nimi (suomeksi)
- Äänestetyn projektin URL
- Luokka
- Koulukoodi

**Comment by ahukkanen** [comment]
Lisäksi pyydettiin seuraavanlaisia yhteenveto-Exceleitä:

Yhteenveto äänestystuloksista (prosesseittain esim. välilehdille eroteltuna):
- Prosessin nimi
- Äänestetyn projektin nimi
- Äänestetyn projektin kustannusarvio
- Äänestetyn projektin saamat äänet yhteensä

Lisäksi tarvitaan tietoa, millä tavoin äänestäjät ovat tunnistautuneet, eli seuraavanlainen yhteenveto kustakin tunnistautumistavasta: 
- Suomi.fi-tunnistautuneiden äänestäjien määrä yhteensä
- MPASSid-tunnistautuneiden äänestäjien määrä yhteensä
- Toimipisteessä tunnistautuneiden äänestäjien määrä yhteensä
