### ISSUE TITLE
Uudenlainen listausnäkymä Accountability -moduliin

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#116]
Seuranta (Accountability) modulin logiikkaa toivotaan muutettavan Decidimissä siten, että välilehdelle siirryttyessä näkyisi välittömästä listanäkymä kaikista toteutukseen valituista hankkeista (ks. kuva).  Tähän listaan ei siis tarvitsisi siirtyä enää välisivun kautta, jossa ensin valitaan aihepiiri. Listaa pitäisi kuitenkin olla mahdollista filtteröidä kahden muuttujan, alue ja aihepiiri, perusteella.  Lisäksi toivotaan vapaahakukenttää.  Liitteenä jonkinlainen kuvallinen räpystys, josta ehkä selviää mitä tarkoitan, elementtien ei tarvitse olla sijoittuneet juuri noin.
![omastadi-suunnitelmattoteutukseen](https://user-images.githubusercontent.com/39044068/68391901-3f1cb680-0171-11ea-9d2b-3b873c98289b.png)

**Comment by ahukkanen** [comment]
Pystytäänkö tuo Alue-filtteri toteuttamaan ihan sillä Teema-tietueella?

Oletuksenahan näihin voi liittää teeman ja aihepiirin.

**Comment by katjahenttonen** [comment]
@ahukkanen  Joo, kyllä tuon voi Teema-tietueella hoitaa ainakin toistaiseksi koska sitä ole tarvetta käyttää mukaan. Pitäisi vaan toteuttaa mahdollisuuus hakea (ie salata listaa) kummankin perusteella.

**Comment by katjahenttonen** [comment]
Tässä vielä muistiin kaksi keskeisintä pointtia viime keskiviikon palaverista:
- toteuttavia hankkeita ei laiteta sivulle listamuodossa (kuten esimerkissä) vaan kuvallisia "kortteja" (vrt. ehdotukset ja suunnitelmat)
- objektit sisaitsevat kunkin prosessin sisällä, mutta niille tehdään prosessirajat ylittävä yhteissivu sekä etusivuelementti samoin kuin Tapahtumilla jo on.
-

**Comment by ahukkanen** [comment]
Listaussivusta on nyt demo ninjassa prosessin alla. Koostesivu (kaikkien prosessien tulokset) puuttuu vielä, mutta katsotaan ensin, että tuo leiska on OK.

**Comment by katjahenttonen** [comment]
@ahukkanen Liitteessä on kuvattu (ks. kommentit) kolme pientä muutospyyntö leiskaan.
![accountability-korjaukset2](https://user-images.githubusercontent.com/39044068/70528833-cc2fa280-1b57-11ea-8e46-10c75e05fde5.png)

**Comment by katjahenttonen** [comment]
Lisäksi @ahukkanen vielä yksi juttu.  Accountablility-komponentin asetuksissa voi määritellä tekstin kohtaan "Nimi termille "Tulokset" ja nimi termille "Suunnitelmat".  Tarvitsemme ja käytämme tätä (Tulos -> Hanke ja Suunnitelma --> Tehtävä) mutta valitetavasti tuossa ei voi määritellä sanalla yksikkö tai monikkimuotoa erikseen. Sille olisi tarvetta koska käyttöliittymässä kumpaakin voi olla 1-n kappaletta.  Mitä tälle olisi tehtävissä?

**Comment by katjahenttonen** [comment]
Lisäksi toivotaan sivupalkin nostamista ylöspäin ison kuvan viereen. Eli toteutetaan tämä:
https://files.slack.com/files-pri/T02DHG0DR-FR45GADA6/projekti-kuvapaikka-sarakkeessa.jpg

**Comment by ahukkanen** [comment]
Tässä viitatut UI-muutokset on nyt toteutettu moduuliin.

Muutin kauttaaltaan termin "projekti" -> "hanke", eli jos sen jättää määrittelemättä komponentille, niin silloin nuo yksikkö- ja monikkomuodot tulevat suoraan lähdekäännöksistä (1 hanke, 2 hanketta).

Jos termit kuitenkin määritellään, niin silloin pitää käyttää monikkomuotoa, jolloin muoto on tuo jälkimmäinen esim. "Hankkeet: 2". Tämä siitä syystä, että tuo monikkokäännös tehdään ohjelmallisesti näille termeille, joka toimii ilmeisen hyvin esim. englannille ja espanjalle, minkä takia näille on vain yksi konfiguraatioarvo määritetty.
