### ISSUE TITLE
Kuvien lisääminen tuloksille Accountability Modulissa

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#117]
Hei!

Accountability modulissa seurattaville hankkeille (eli "tuloksille") on voitava lisätä kuvia.  Hankkeeseen liittyvät  kuvat voisivat näkyä yhteydessä samalla tavalla kuin esimerkiksi suunnitelmille lisätyt kuvat.

**Comment by katjahenttonen** [comment]
Joku kuvista haluttaisiin nostaa myös listausnäkymään (#116)  ikonin tilalle

**Comment by ahukkanen** [comment]
Pääkuvan ja listauskuvan lisääminen on nyt mahdollista accountability-moduulissa ninjassa.

**Comment by ahukkanen** [comment]
Lisätty myös mahdollisuus liitteille, samaan tapaan kuin budjetointiprojekteilla.
