### ISSUE TITLE
Accountability-modulissa aikajana vertikaaliin

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#118]
Hei!

Accountability moduliessa tulokseen liittyvän aikajanan muotua haluttaisiin muuttaa siten että se kulkisi vertikaalisesti vasemmalta oikealle eikä horisontaalisesti ylhäältä alas.  Nykyisenlaisen aikajan kuva liitteenä.

![omastadi-aikajana](https://user-images.githubusercontent.com/39044068/68393376-9708ec80-0174-11ea-9df0-f1d3b39aec80.png)

**Comment by ahukkanen** [comment]
Ninjassa olevassa versiossa aikajana tulee nyt näkyviin sivusuunnassa laajoilla näytöillä. Näkymä on edelleen pystysuunnassa kapeammilla näytöillä (mobiili).

**Comment by katjahenttonen** [comment]
Kiitos, tämä on hyvä. Kuten sovimme Slackissä niin aikajaa pitäisi vielä korjata siten että tila jaetaan taisesta milestonien kesken ja aikaja jatkuu tarvittaessa seuraavalle riville. Toteutetaan ensimmmäinen vaihtoehto täällä kuvatusta leiskasta: https://files.slack.com/files-pri/T02DHG0DR-FR2NDCASW/aikajana-rivit.png

**Comment by ahukkanen** [comment]
Aikajanan pyydetty UI-muutos on toteutettu.
