### ISSUE TITLE
Accountability-modulin aikajaan muutos päivämäärän formaatti

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#119]
Slack-keskusteluun viitaten, tarkan päivämäärän sijasta pitää kuhunkin aikajanalla olevaan milestoniin yhdistää väljempi aikamääritelmä vuodenaika + vuosi, esim.  kevät 2020 tai syksy 2021.  Tämän vaatima tietokantamuutos on ok.

**Comment by ahukkanen** [comment]
Aikajanan itemeille on nyt määritetty myös otsikko-kenttä, jonka määrittämällä tuon kyseisen tekstin saa muutettua halutunlaiseksi. Mikäli tätä tekstiä ei ole määritelty, muoto tulee edelleen samalla tavalla päivämäärästä.

**Comment by katjahenttonen** [comment]
@ahukkanen  onko tätä mahdollista toteuttaa siten, että päivämäärä ei olisi pakollinen kenttä?   Vai onko tuo yksilöllinen avain tietokannassa?

**Comment by ahukkanen** [comment]
Päivämäärä ei nyt ole enää pakollinen kenttä.

Ei ole tietokannassa avaimena, kenttien pakollisuus oli määritetty lomakeluokkaan.

**Comment by katjahenttonen** [comment]
Hyvä, kiitos!
