### ISSUE TITLE
Osoite on oltava Helsingissä

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#12]
Jos käyttäjä  syöttää vain katuosoitteen, oletuskaupungin on oltava Helsinki.  Ihanteellisesti muita kuin Helsinkiin sijoittuvia tapahtumia tai ehdotuksia ei pitäisi voida edes syöttää. Tämä tulee jatkuvasti esiin kun käyttäjät alkavat testata palvelua, esim. paikaksi syötetään "Alppila" ja se paikantuu Pohjois-amerikkaan. Jopa stadiluotsit onnistuvat hallintakäyttöliittymästä syöttämään vahingossa tapahtumia, jotka paikantuvat kaukaiseen maaahan.  Yksikin väärin paikatuvat ehdotus/tapahtuma sotkee kaikkien näkymän, kun kartta skaalautuu väärin.

**Comment by katjahenttonen** [comment]
Tämän korjaaminen olisi varmasti höydyllistä kaikille Decidimin käyttäjille, joten pitäisi lisätä joku parametri "oletuskaupunki" tms.

**Comment by ahukkanen** [comment]
Tämä muutos on lokaalisti toteutettu Helsingin Decidim-instanssiin samaan malliin kuin MTK:ssa.

Seurataan tuota Decidim-kehitysehdotuksen etenemistä, myöhemmin tämän kustomoinnin voi todennäköisesti poistaa, jos tuo etenee, kuten äänten mukaan vaikuttaisi.
