### ISSUE TITLE
Accountablity moduli: kuvatekstin lisääminen

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#120]
Liitteitä lisättäessä käyttäjää pyydetään syöttämään "Kuvan tai liitteen otsikko".   Jos kyseessä on kuva, kyseisen kentän sisältö pitäisi näyttää käyttäjälle kuvatekstinä.

**Comment by ahukkanen** [comment]
Liitekuvien näyttöön on tehty seuraavat muutokset:
- Kuva näytetään aina saman kokoisena, riippumatta lähdekuvan koosta tai kuvasuhteesta. Huomioikaa, että nyt esim. pystykuvat leikataan keskeltä tuohon kuvapaikalle sopivaan muotoon.
- Kuva näytetään ns. "kortissa" sen otsikon ja kuvauksen kanssa, jotka hallintapaneelista on määritelty.

Tämä muutos vaikuttaa kaikkiin liitekuviin, joita erilaisilla olioilla (mm. suunnitelmat, äänestysprojektit) järjestelmässä on.

Käyttöliittymässä tämä näyttää seuraavalta:
![liitekuvat](https://user-images.githubusercontent.com/864340/70884245-1ee8de80-1fde-11ea-91f0-d36fd6db12d9.jpg)
