### ISSUE TITLE
Accountability-modulin sivubanneri

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#121]
Accountability-modulin sivubannerista toivottiin vielä hieman erilaista, liitteenä Belindan piirtämä luonnos.
![Toteutuksen seuranta_sivubanner ilman karttaa_korjattu](https://user-images.githubusercontent.com/39044068/71184041-c6d20680-2281-11ea-904b-22e4b32a3259.jpg)

**Comment by katjahenttonen** [comment]
Tässä oli idena vielä että käytettäisiin aihepiirikohtaisia värikoodeja  tuon Hankinta-infon reunuksissa. En tiedä onnistuuko tämä järkevästi (voi unohtuu jos menee liian työlääksi) mutta varmuuden vuoksi tähän vielä nuo värikooditkin: 

- *    Rakennettu ympäristö: R=0 G=114 B=188
- - •	Puistot ja luonto: R=198 G=156 B=79
- - •	Oppiminen ja osaaminen: R=160 G=201 B=236
- - •	Terveys ja hyvinvointi: R=243 G=112 B=33
- - •	Ekologisuus: R=81 G=191 B=157
- - •	Liikunta ja ulkoilu: R=178 G=181 B=183
- - •	Kulttuuri: R=241 G=162 B=198
- •	Yhteisöllisyys: R=255 G=212 B=0

**Comment by ahukkanen** [comment]
Sivubannerin tietoja voi nyt vapaasti hallita tuloksen editointinäkymästä. Siihen voi vapaasti kirjoittaa mitä tahansa. Oletuksena siihen tulee tuloksen kategoria ja teema Decidimin määritysten mukaisesti (näitä termejä voi toki muuttaa, miksi näitä kutsutaan)

Teemaväriä voi nyt muuttaa jokaiselle tulokselle erikseen. Tuo kategoriakohtainen teemaväri voisi mennä hieman hankalaksi, kun en tiedä määritelläänkö nämä teemoina vai kategorioina teknisesti Decidimissä, jotka ovat eri olioita. Toki voimme kustomoida myös kategoria- ja teemaolioita decidimin coresta, mutta se vaikuttaisi sitten core-gemiin, kun taas muut tässä tehdyt muutokset vaikuttavat ainoastaan accountability-moduuliin.

Nuo kategoria/teemakohtaiset ikonit ovat myös hankalia tästä syystä. Toki voimme lisätä siihen ikonivalikkoon uusia ikoneita ja määritellä tämän aina manuaalisesti jokaiselle tulokselle erikseen. Tätä varten pitäisi luoda oma ikonisetti, johon ikonit määritellään (tarvitsemme ikonivektorit tätä varten).

Tällä hetkellä Decidimissä on valmiiksi määriteltynä vain Decidimin omat ikonit ilmeisesti lisenssisyistä. Mikäli muita ikoneita halutaan käyttää, ne pitää tosiaan erikseen määrittää.

Jakopainikkeista mietin, kannattaako niitä lisätä tuonne sivupalkkiin suoraan, koska niitä on kaiketi tulossa lisää uudemmissa versioissa. Nykyinen ratkaisu on myös yhtenevä muiden sivujen kanssa, jossa tuota jakopainiketta näytetään. Jos nämä halutaan ottaa kokonaan ulos siitä popupista, niin suosittelisin vielä miettimään tätä niin, että tuo jakopainikkeiden listaus toimii myös kaksirivisenä (jos niitä tulee lisää) ja niin, että se ei ole tuossa sivupalkissa, vaan sen alla (jotta se toimii myös muualla samalla tavoin).

Lisäsin esimerkin sivupalkista tänne:
https://osallistu.hel.ninja/processes/katjantesti/f/78/results/12

**Comment by katjahenttonen** [comment]
Kiitos paljon @ahukkanen! Ymmärrän hyvin että värejä ja ikoneja ei saa
aihepiireihin siten että tekninen toteutus olisia välttämättä
linkattu järkevä ja mukautumiskykyinen myös jatkossa. Siitä voidaan luopua.
Sitä jäin vielä miettimään että olisiko sivupalkin kenttien nimet ja ikonit
mitenkään mahdollista määritellä komponentin asetuksissa yksityisen
tuloksen asetusten sijasta tai lisäksi (jos lisäksi niin komponentin
asetuksista tulisi oletusarvot)? Meillä on nyt kymmeniä eri ehdotuksia,
joille kaikille halutaan sama sivupalkki, joten siitä tulee varmasti
sanomista jos kenttien ja ikonien nimet pitää syöttää kymmeniä kertoja
erikseen.  Toisaalta päätulosten sisälle halutaan varmasti sellaisia
alituloksia (tehtäviä), joilla sivupalkkia ei ole tai se on erilainen.

**Comment by katjahenttonen** [comment]
Edelliseen vielä lisäyksenä: jakopainikkeet lienee tosiaan viisaampaa jättää omaksi pop-upikseen. Jakopainikkeiden ulkonäöstä on tullut paljon negapalautettava, joten niiden ulkonäön muokkaamista voisi miettiä erikseen. Tällöin muutos pitäisi tehdä kautta järjestelmän, tehdään tästä oma tiketti jos on on tarpeen.

**Comment by ahukkanen** [comment]
@katjahenttonen Kyllä uskon, että tuollainen oletuskenttien määritys varmasti onnistuisi.

Halutaanko tämä niin, että erillisistä asetuksista määritellään:

a) Oletuskentät kaikille tuloksille ja näiden päivittäminen vaikuttaa automaattisesti kaikkiin tuloksiin (esim. jos jonkin kentän nimeä halutaan muuttaa keskitetysti tai jos halutaan lisätä uusi kenttä keskitetysti kaikille ehdotuksille). Tässä hieman ongelmallista olisi nuo yksittäiset eroavaisuudet tietyissä tuloksissa (minkä takia päädyin nykyiseen toteutukseen).

VAI

b) Oletuskenttien oletusarvot, joka syötetään uudelle tulokselle automaattisesti ja sitten niitä voi hallita jokaiselle tulokselle erikseen. Keskitettyjä muutoksia ei tehdä enää vanhoille tuloksille, jos oletuksia muutetaan.

Jutellaan tarvittaessa vaikka Slackissa lisää tästä, niin tarkennan, jos tästä ei saa kiinni.

**Comment by katjahenttonen** [comment]
Joo, jatketana keskustelua Slackissä. Mä suljen nyt tämän tiketin koska homma on toteutettu aiemman määrittelyn mukaan. Avaan uuden tiketin muutoksista niin pyysyy selkäempänä.
