### ISSUE TITLE
 decidim-initiatives modulin asennus testiympäristöön

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#123]
Decidimin aloitemoduli siis decidim-initiatives pitäisi asentaa meidän omaan testiympäristöön osallistu.hel.ninja.

**Comment by ahukkanen** [comment]
Initiatives-moduuli on asennettu nyt ninjaan. Koska yläpalkin navigaatiota on muokattu, tänne pääsee kirjoittamalla osoitteen perään `/initiatives`.
