### ISSUE TITLE
Seurantamodulin sivubannerille oletustemplate

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#124]
Seurantamodulin sivubannerin rakenteelle (eli tekstikenttien nimet, esim. "kustannusarvio" ja ikonit) tehdään komponenttitasolla määriteltävä oletustemplate, jota voisi tulostasolla käyttää tai jättää käyttämättä. Jos templeteä ei halua tulostasolla käyttää niin silloin on vaihtoehtona määritellä kentät tulostasolla itse tai jättää ne  määritettelmättä kokonaan (jolloin sivubanneria ei näytetä lainkaan).  Toivottavatavaa (mutta ei välttämätöntä) olisi että templatea voisi tulostasolla laajentaa, esim. lisäämällä yhden tuloskohtaisen kentän.  Kenttien arvot (esim. "50 000 €") pitää luonnollisesti aina määritellä tulostasolla eikä niitä tule ottaa mukaan oletustemplateen.

**Comment by ahukkanen** [comment]
Tämä löytyy nyt ninjasta testattavana.

Oletustemplaten määrittely on nyt mahdollista komponenttitasolla. Komponentin listaussivulla löytyy ylhäältä painike "Oletustiedot", mistä pääsee näitä "oletustemplaten" kenttiä määrittämään:

![tulokset-oletustiedot](https://user-images.githubusercontent.com/864340/73066507-db23a780-3eae-11ea-93f3-970deeedf376.png)

Yksittäisen tuloksen muokkaussivulla löytyy ensiksi nämä oletustiedot ja niiden yläpuolella kenttä, mistä oletustiedot voi ottaa halutessaan pois päältä. Mikäli kyseistä raksia ei ole ruudussa, oletustietoja ei näytetä kyseisen tuloksen sivulla. Oletustietojen alla voi määritellä myös tuloskohtaisia lisätietoja halutessaan (tai jättää määrittämättä):

![tulokset-tuloskohtaiset-lisatiedot](https://user-images.githubusercontent.com/864340/73066571-07d7bf00-3eaf-11ea-85c6-bf0bdeca2c96.png)

**Comment by katjahenttonen** [comment]
Kiitos, tämä on testattu ja kunnossa.
