### ISSUE TITLE
Kokoomasivu eri prosessien tuloksille

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#125]
Seurantamodulin tuloksille (eli seurattaville hankkeille) tarvitaan saman tyyppinen kokoomasivu kuin mitä tapahtumilla on (vrt omastadi.hel.fi/meetings).  Kokoomasivulla pitäisi olla mahdollisuus filtteröidä tuloksia seuraavasti: 1.  kaikki tulokset 2. tiettyyn prosessiryhmään kuuluvat tulokset (käytännössä Helsingin kaupungin osallistuva budjetointi tai RuutiBudjetointi) tai tiettyyn yhteen prosessiin liittyvät tulokset (esim. Kaakkoinen Helsinki tai Viikin nuorisotyöyksikkö).  Hakupalkit prosessit tulisi esittää prosessiryhmien alla, esim. sisennetystä (siten että käyttäjä näkee mihin prosessiryhmään mikäkin prosessi kuluu. Jos suinkin mahdollista, yhteen prosessiryhmään liittyville tuloksille olisi hyvä saada selkokielinen URL-osoite, esim. omastadi.hel.fi/results/[prosessiryhmännimi]), jota voi jakaa esim. somessa.

**Comment by ahukkanen** [comment]
Kokoomasivu löytyy nyt ylätason osoitteesta kirjoittamalla heti domainin perään:
`/results`

Nuo filtterit vielä puuttuvat, siinä oli hieman ongelmia. Mutta tulevat mukaan vielä tällä viikolla, kunhan keksin ratkaisun.

**Comment by ahukkanen** [comment]
Erillinen tiketti ym. ongelmasta #133 (korjattu).

**Comment by Valinje** [comment]
Oliko filtteröinnit ratkaistu?

**Comment by ahukkanen** [comment]
@Valinje Kyllä on, siihen liittyvät ongelmat on raportoitu tiketissä #133.

**Comment by Valinje** [comment]
suljen nyt tämän tiketin. On toteutettu lopputuloksen kannalta OK.
