### ISSUE TITLE
Seurantamodulin tuloskortin sivupalkin laatikoiden ulkonäkö yhtenäiseksi

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#127]
Seurantamodulin yksittäisellä tuloskortilla on nyt  laatikot "Edistyminen" ja sen alla "Hanke info".  Laatikot pitäisi ulkonäöllisesti yhteinäistää siten että reunat ovat saman paksuiset ja fontti on sama (tekstin ei välttämättä tarvite olla saman kokoinen). Mallina toivotaan käytettävän "Hanke info" laatikon tyyliä.

**Comment by ahukkanen** [comment]
Esitetty muutos on nyt tehty ja löytyy sekä ninjasta että tuotannosta.
