### ISSUE TITLE
Seurantamoduulin uuden tuloksen muokkaus

### ISSUE THREAD

**Issue by Valinje** [City-of-Helsinki/decidim-helsinki#129]
Kun aikaisemmin luodun tuloksen avaa uudelleen muokattavaksi, niin aikaisemmin tehdyt valinnat katoavat seuraavista kohdista:
•	aihepiiri
•	sisällytetyt ehdotukset
•	liitetyt suunnitelmat
Tämä pitäisi korjata niin, että aiemmin kirjatut kohdat säilyvät kunnes ne muutetaan kenttiin.

**Comment by ahukkanen** [comment]
Tämä on nyt korjattu ninjaan ja tuotantoon.

Ongelma koski seurantamoduuliin tehtyä kustomointia, joka muuttaa hallintalomakkeen toimintalogiikkaa, jotta se huomioi lisäämämme kentät.
