### ISSUE TITLE
Kuvat mukaan tapahtumien ja ehdotusten listanäkymiin

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#13]
Käyttäjät ovat todella paljon toivoneet, että tapahtumien, ehdotusten ja suunnitelmien (budjetointivaihe) listanäkymiin pitäisi saada kuvat.  Toki pitää olla myös joku oletuskuva, joka näytetään mikäli kuvaa ei ole lisätty. Siis samalla tavalla kuin pormestarin ideakilpailun yhteydessä jo ehdotuksille tehdään.  Ihmiset eivät koe ongelmana ajatusta siitä, että käyttäjien laittamat kuvat voivat olla huonoja tms.  Käyttäjiä tullaan kuitenkin ohjeistamaan siitä millainen on hyvä kuva.

**Comment by ahukkanen** [comment]
Tämä onnistuu kustomointina. Ehdotuksille ja suunnitelmille voi lisätä liitetiedostoja, mistä tämä kuva voidaan ladata.

Ideakilpailun osalta käsitin, että siellä tarkoitus olisi näyttää listauksissa ns. "kovakoodatut" aihepiirien kuvat.

Toteutustapa ehdotuksille listauksessa:
- Hae ehdotukseen liittyvä ensimmäinen liite
- Tarkasta onko se kuva
- Näytä kuva listauksessa, jos asetettu

Toteutustapa suunnitelmille (budjetointi) listauksessa:
- Hae suunnitelmaan liittyvät liitteet ja valitse niistä ensimmäinen kuvamuotoinen
- Näytä kuva listauksessa, jos asetettu

**Comment by katjahenttonen** [comment]
Ideakilpailussakin oli tarkoitus näyttää käyttäjien tekemät kuvat.  Kovakoodatut aihepiirien kuvat oli tarkoitus näyttää siinä tapauksessa, että käyttäjä ei ole lisännyt kuvaa liitteeksi. Samaa systeemiä siis kaivattaisiin osallistuvaan budjetointiin.

**Comment by ahukkanen** [comment]
Aihepiirien kovakoodatut kuvat on melko haastavaa toteuttaa tällä hetkellä OSBU-puolelle, mutta toki se voidaan tehdä kovakoodattuna, kuten ideakilpailuunkin.

Harkitsisin kuitenkin vielä, onko tämä ns. pakollinen ominaisuus.

Tuo käyttäjien syöttämien kuvien näyttäminen listauksessa on teknisesti huomattavasti helpompi ominaisuus toteuttaa.

**Comment by katjahenttonen** [comment]
Ok.  Aihepiirikohtaisten kuvien näyttäminen ei ole välttämätön ominaisuus.  Riittää, että käyttäjien omat kuvat näkyvät listauksessa (ja lisäksi meillä on jotenkin mietittynä miltä ilmoitus näyttää silloin kun käyttäjä ei ole ladannut kuvaa).  Mutta unohdetaan siis aihepiirikohtaiset kovakoodatut kuvat.

**Comment by katjahenttonen** [comment]
Tässä tulee aika kiire ehdotusvaiheen kanssa ja näkisin, että tämä ei nyt voi olla kovin korkean prioriteetin juttu. Minusta tuntuu, että useimmat halauvat jättää ehdotuksen ilman kuvaa.

**Comment by katjahenttonen** [comment]
Ok, hieno juttu!
