### ISSUE TITLE
Rajapinnan rakentaminen ideapaahtimoon

### ISSUE THREAD

**Issue by Valinje** [City-of-Helsinki/decidim-helsinki#130]
-kirjautumisen mahdollistaminen
-paluuliikenteen mahdollistaminen
-suunnitelmat rajapintaan

**Comment by ahukkanen** [comment]
Rajapinta on toteutettu ideapaahtimoon ja dokumentaatio on toimitettu integraatiokehittäjille.

**Comment by Valinje** [comment]
Suljen tämän heti, kun näemme rajapinnat tositoimissa.
