### ISSUE TITLE
Seuranta sivuilta "0 kommenttia" -kohdan poisto

### ISSUE THREAD

**Issue by Valinje** [City-of-Helsinki/decidim-helsinki#131]
Suunnitelmaan liittyvät ehdotukset kohdan perään sivun alalaitaan tulee "0 kommenttia" -laatikko. Tämä pitäisi poistaa heti.

**Comment by ahukkanen** [comment]
Kuten muistelinkin, niin tätä pystyy kyllä kontrolloimaan asetusten kautta. Oikea asetus on "Piilota kannatusmäärät" Ehdotukset-komponentin vaiheasetuksissa:

![liittyvat-ehdotukset-piilota-kannatukset](https://user-images.githubusercontent.com/864340/74437904-a2ee0400-4e71-11ea-882b-c241d6d2f0d4.png)

Tämä asetus on asetettu päälle kaikkiin aktiivisiin vaiheisiin kaikkien alueiden ehdotukset-komponentille, mikä korjaa kyseisen ongelman.
