### ISSUE TITLE
Somejakojen oletuskuvien vaihtaminen

### ISSUE THREAD

**Issue by Valinje** [City-of-Helsinki/decidim-helsinki#132]
Omastadin esim. seurantasivuja someen jakaessa kaikkiin jakoihin tulee sama yleiskuva. Somejaoissa oletusjakokuvaksi pitäisi saada määriteltyä kunkin hankkeen oma kuva. Toteutusaikataulu viimeistään syksyn 2020 OSBU:n ideointivaiheeseen.

**Comment by ahukkanen** [comment]
Some-jakokuviksi seurattaville hankkeille tulee nyt oletuksena se sama kuva, mitä käytetään listauksissa.
