### ISSUE TITLE
Seurannan koontisivun haku ja teema -toiminnot eivät toimi

### ISSUE THREAD

**Issue by Valinje** [City-of-Helsinki/decidim-helsinki#133]
Seurattavien hankkeiden kokoomasivulla https://omastadi.hel.fi/results
löytyvä hakutoiminto ei hae hankkeita. Teema -toiminnon alasvetolaatikko on tyhjä. Nämä korjaukseen.

**Comment by ahukkanen** [comment]
Teema taitaa olla sen takia tyhjä, koska tuotannossa ei ole yhtään teemaa määritetty.

**Comment by ahukkanen** [comment]
Hakutoiminto toimii nyt ja teemafiltteri on piilotettu, koska teemoja ei ole määritetty.
