### ISSUE TITLE
Tilafiltteröinnin muuttaminen ideapaahtimon tarpeisiin

### ISSUE THREAD

**Issue by Valinje** [City-of-Helsinki/decidim-helsinki#135]
Sisään tulevien ideoihin sisäänrakennetaan heti status --> arvioitavana.
Ideoilla on siten heti jokin seuraavista statuksista:
- arvioitavana
-käsitelty
-palkittu
Tilafiltteröinti näyttää myös 
-kaikki.

**Comment by ahukkanen** [comment]
Suunnitelmat-komponentin tilafilttereihin on tehty seuraavat muutokset:
- Muutettu oletusfiltteriksi "kaikki"
- Muutettu filttereiden järjestys: kaikki, hyväksytty, hylätty, arvioitavana

Idepaahtimon vuoden 2020 ideakanavaan on tehty seuraavat termikustomoinnit näihin tiloihin liittyviin termeihin:
- Hyväksytty => Palkittu
- Hylätty => Käsitelty

Nyt siis tilafiltterissä näkyy seuraavat:
- Kaikki
- Palkittu
- Käsitelty
- Arvioitavana

**Comment by ahukkanen** [comment]
Tehtävää vielä:
Kaikille uusille ideoille merkitään automaattisesti tila "arvioitavana".

**Comment by ahukkanen** [comment]
Oletustila-tarpeelle on nyt lisätty Suunnitelmat-komponenttiin uusi asetus "Oletustila". Tämä tila määritetään uusille suunnitelmille automaattisesti aina, kun sellainen julkaistaan.

Suunnitelmat-komponentti on siis se, mitä Ideapaahtimossa on käytetty ideointiominaisuutena.

Idepaahtimon vuoden 2020 ideakanavaan on asetettu oletustilaksi "Arvioitavana". Tämä tarkoittaa sitä, että kaikki uudet ideat merkitään automaattisesti tilaan "Arvioitavana", kun idea julkaistaan käyttäjän toimesta.
