### ISSUE TITLE
Uusi Decidim- moduuli ohjauksille

### ISSUE THREAD

**Issue by Valinje** [City-of-Helsinki/decidim-helsinki#138]
Tarvitaan uusi Decidim-moduuli, jonka tarkoituksena on toimia vanhan 2019 OSBU -prosessien siirrossa välineenä yhteen prosessiin siirrossa. Moduulilla voidaan määrittää ohjauksia vanhoista osoitteista uusiin. Tarvitaan myös hallintakäyttöliittymä, josta hallintakäyttäjät voivat käydä halutessaan näitä ohjauksia lisäämässä, poistamassa tai muuttamassa.

**Comment by ahukkanen** [comment]
Moduuli on nyt viety ninjaan ja tuotantoon migraatioajon yhteydessä (#139).
