### ISSUE TITLE
Tekninen migraatio datan siirtoon vanhoista prosesseista yhteen uuteen

### ISSUE THREAD

**Issue by Valinje** [City-of-Helsinki/decidim-helsinki#139]
Migraatio käy läpi vanhan prosessiryhmän "Helsingin osallistuva budjetointi" (omastadi-lantinen, omastadi-kaakkoinen, omastadi-etelainen, jne.) ja kaikista vanhoista alueprosesseista suorittaa jokaiselle prosessille seuraavia toimenpiteitä:
1. proposals ja plans -komponenteista käy läpi suunnitelmat ja ehdotukset ja siirtää ne uuden prosessin vastaaviin komponentteihin
 - Merkitsee jokaisen ehdotuksen oikealle alueelle käyttäen hyväksi Decidimin scopes-ominaisuutta (alueteema)
 - Generoi vanhoille komponentille uudelleenohjaukset jokaiseen uuden komponentin vastaavaan osoitteeseen käyttäen hyväksi uutta ohjausmoduulia. Osoitteissa vaihtuu prosessin URL-tunniste sekä Proposals-komponentin ID-numero.
2. Siirtää vanhan prosessin äänestyskomponentin uuteen prosessiin sellaisenaan.
 - Muuttaa äänestyskomponentin nimeksi aluetta kuvaavan nimen (esim. Eteläinen Helsinki)
- Generoi vanhalle prosessille uudelleenohjaukset jokaiseen uuden prosessin budjetointiprojektin osoitteeseen käyttäen hyväksi ohjaukseen luotua moduulia. Osoitteissa vaihtuu prosessin URL-tunniste, mutta komponentin ID pysyy samana.
3. Käy läpi kaikki seurattavat tulokset ja siirrä ne uuden prosessin Accountability-komponenttiin
- Merkitsee jokaisen seurattavan tuloksen oikealle alueelle käyttäen hyväksi Decidimin scopes-ominiasuutta (alueteema)
- Generoi vanhalle komponentille uudelleenohjaukset jokaiseen uuden komponentin seurattavan tuloksen osoitteeseen käyttäen hyväksi luotua ohjausmoduulia. Osoitteissa vaihtuu prosessin URL-tunniste sekä Plans-komponentin ID-numero.

**Comment by ahukkanen** [comment]
Migraatio on nyt ajettu OmaStadin tuotantoympäristössä.
