### ISSUE TITLE
Äänestysnäkymän muokkaus

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#14]
Näkymä, jossa suunitelmia valitaan ostoskortiin ei ole nyt kovin käyttäjäystävällinen.  Suunnitelmissa pitäisi näkyä ingressi ja joku kuva.  Ne pitäisi olla myös satunnaisjärjestykessä eikä aakkosjärjestyksessä kuten ilmeisesti nyt.  Muuten kaikki tekevät A:lla alkavia ehdotuksia saadaaksen etua äänetyksessä.

**Comment by katjahenttonen** [comment]
Tätä pitää vielä tarkentaa.

**Comment by ahukkanen** [comment]
Suunnitelmat eivät tule käyttäjiltä suoraan, vaan ne lisätään organisaation (Helsinki) päässä. Suunnitelmaan liittyy aina formaalimpi toteutussuunnitelma tai vähintään tarkempi selitys, mistä äänestetään (toteutussuunnitelma liitteenä on vapaaehtoinen). Suunnitelman itsessään voi liittää yhteen tai useampaan ehdotukseen.

Tähän siis ei sisälly riskiä, että käyttäjät lisäisivät A:lla alkavia suunnitelmia.

Miettisin vielä, onko satunnaisjärjestys tälle välttämätön. Näkisin, että budjetointivaiheessa aakkosjärjestys voi olla selkeämpi, kun oletuksena budjetointivaiheessa nuo suunnitelmat ei muutu (eli niitä ei tule lisää tai poistu) sen jälkeen, kun budjetointi alkaa.

Tuo lyhyt kuvaus listaukseen mukaan on mielestäni hyvä ehdotus. Lisäsin tästä kehitysehdotuksen Metadecidimiin:
https://meta.decidim.org/processes/roadmap/f/122/proposals/13155

**Comment by ahukkanen** [comment]
OK, totta tosiaan. Tuossa tapauksessa se käy kyllä järkeen, että ne saisi myös satunnaisjärjestykseen.

**Comment by katjahenttonen** [comment]
näyttäisi @ahukkanen  siltä että budjetointiprojektit nykyisen näytetään satunnaisessa järjestyksessä. Elikäs ilmeisesti Barcelonan pää on hoitanut tämän?

**Comment by ahukkanen** [comment]
Hmm, onkohan tässä ollut false flag tuon sorttauksen osalta. Katselen Decidimin commit-historiasta, niin kyllä tuo satunnaisjärjestys näyttää olleen kyseisessä komponentissa ihan sen alusta lähtien. Kyseistä hakua ei ole myöskään kustomoitu Helsingin päässä.

**Comment by katjahenttonen** [comment]
Tästä on puhetta jo syksyllä, että sen pitäisi olla siellä, mutta ei kyllä toiminut, testasin silloin moneen kertaan ja aina ne tuli samassa järjestyksessä. Eli varmaankin joku bugi ollut. Mä suljen tämän tiketin nyt.  Loppukuusta alan ihmetellä käyttäjien kanssa äänestysnäkymää ja sitten tulee varmaan jotain uusia toiveita, mutta avaan niistä erilliset tiketit sitten. Tämä on vähän yleinen.
