### ISSUE TITLE
Ideapaahtimon uuden prosessin teema-osion uudelleen nimeäminen

### ISSUE THREAD

**Issue by Valinje** [City-of-Helsinki/decidim-helsinki#141]
Ideapaahtimon uuden prosessin lomakkeelle on rakennettu teemat -osiolla alasvetolaatikko, jonka otsikointiin pitäisi pystyä muotoilemaan lause yksittäisen termin sijasta. Nyt termikustomoinnilla on otsikoksi muutettu muotoon: "Toimialasi". Toivottu lause olisi: "Mikä toimiala mielestäsi parhaiten mahdollistaa idean toteutumisen?"

**Comment by ahukkanen** [comment]
Tämä muutos on tehty termikustomoinnin kautta.

Tuo "Henkilöstön oma ideakanava 2020" käyttää hyväkseen aihepiirejä/kategorioita, ei siis teemoja.

Nämä termikustomoinnit löytyvät hallintapaneelista osiosta:
Termien kustomoinnit > "Kategoria->Toimialasi"
