### ISSUE TITLE
Seurannan aikataulujanan toisen rivin viivan näkyminen

### ISSUE THREAD

**Issue by Valinje** [City-of-Helsinki/decidim-helsinki#142]
Seuranta-osiossa aikataulujanan jatkuessa toiselle riville, vaihekohtien välillä oleva viiva ei näy. 

<img width="777" alt="Aikataulujana" src="https://user-images.githubusercontent.com/60175999/78788526-9f2fb700-79b4-11ea-824f-1f5351dce2af.png">

**Comment by ahukkanen** [comment]
Ongelma liittyi siihen, että kuvauksissa on käytetty oletettua pidempiä sanoja, joka venyttää yhden aikajanan merkinnän leveyden yli sille määritellyn rajan. Kuvassa havainnollisesti sana "tutkimuskysymysten" venyttää kyseisen aikajanan merkinnän leveyden yli sille varatusta 20% tilasta kyseisellä rivillä.

Tämä on nyt korjattu siten, että yhdelle riville tulostuu leveillä näytöillä 4 merkintää (aikaisemmin 5 merkintää), jotta niille jää hieman enemmän tilaa. Kapeammilla näytöillä tulostuu nyt 3 merkintää per rivi (aikaisemmin 4 merkintää).

Leveysrajoitus tulee silti edelleen ottaa huomioon aikajanan merkintöjä laadittaessa. Niissä ei saa käyttää pitkiä yhdyssanoja, koska ne rikkovat aikajanan vaakamuodon.
