### ISSUE TITLE
Ideapaahtimon nykyisille ja menneille prosesseille painikkeet

### ISSUE THREAD

**Issue by Valinje** [City-of-Helsinki/decidim-helsinki#145]
Muutetaan ideapaahtimon ja kokeilukiihdyttämön Osallistu-sivuilla ylävalikon: 
"Käynnissä nyt", "Katso ""Menneet", "Kaikki" painikemuotoon ja poistetaan Katso -sana joukosta. 
Painikkeissa jatkossa nimet Käynnissä, Menneet, Kaikki. Valittu painike näkyy eri värillä.

![image](https://user-images.githubusercontent.com/60175999/79958883-1886d980-848c-11ea-8935-f1f423e4a8aa.png)

**Comment by ahukkanen** [comment]
Tämä on muutettu nyt niin, että kaikki linkit säilyvät näkyvillä riippumatta valitusta tilasta ja otsikkoa ei erikseen kirjoiteta linkkien viereen.
