### ISSUE TITLE
Uusi ehdotus selvemmin näkyville

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#15]
Käyttäjiltä tulee jatkuvasti palautetta siitä, että kohta "Uusi ehdotus" pitäisi näkyä selkeämmin.  Painikkeesta voidaan tehdä  näkyvämpi kuten pormestarin ideakilpailun yhteydessä. Olisiko kuitenkin myös mahdollista  lisätä oma välilehti "Uusi ehdotus" joka siirtyisi suoraan  ehdotuksen luontiin? Siis tähän näkymään: https://osallistu.hel.ninja/processes/osbu-itainen/f/26/proposals/new.  Tällöin nykyisen ehdotusvälilehden nimeksi vaihtuisi "Kaikki ehdotukset" ja toinen välilehti olisi "Uusi ehdotus".

**Comment by ahukkanen** [comment]
Onko ongelma nimenomaan prosessin etusivulla vai itse Ehdotukset-komponentissa (Proposals)?

Mikäli ongelma koskee ainoastaan Ehdotukset-komponenttia, ratkaisisin tämän vain käyttöliittymämuutoksella kyseiseen komponenttiin, eli siis kasvattamalla sen "Uusi ehdotus" -painikkeen kokoa ja muuttamalla sen sijaintia.

Mielestäni myös se karttanäkymän piilottaminen oletuksena voisi auttaa tässä, mitä suunniteltiin ideakilpailuun.

**Comment by katjahenttonen** [comment]
Jep, kyllä karttanäkymän piillottaminen oletuksena ja Ehdotukset-painikkeet suurentaminen on varmasti riittäviä toimenpiteitä. Kysyin nyt tuosta välilehtiasiastakin koska sitä on esittetty.
