### ISSUE TITLE
Ruutibudjetoinnin kopiointi omalle instanssilleen 

### ISSUE THREAD

**Issue by Valinje** [City-of-Helsinki/decidim-helsinki#151]
Erotetaan Ruutibudjetointi Omastadi.fi yhteydestä omalle instanssilleen. Luodaan myös uusi domain.
Uusi verkko-osoite on ruutibudjetti.hel.fi.

**Comment by ahukkanen** [comment]
Ruutibudjetti toimii nyt osoitteessa:
https://ruutibudjetti.hel.fi/

MPASSid pitää liittää siihen vielä, kun saamme sen auki, eli jätetään tämä toistaiseksi auki.

**Comment by ahukkanen** [comment]
MPASSid on nyt liitetty myös ruutibudjetti.hel.fi-palveluun.

Kirjautumissivu toimii, joten luultavasti myös kirjautuminen toimii normaalisti. Koko kirjautumisprosessi kannattaa kuitenkin vielä testata jonkun sellaisen toimesta, jolla on Wilma-tunnus.
