### ISSUE TITLE
Ohjaavan painikkeen lisäys kaupunginosapenkin seurantasivulle 29.5.

### ISSUE THREAD

**Issue by Valinje** [City-of-Helsinki/decidim-helsinki#155]
Lisätään kaupunginosapenkin seurantasivulle 29.5. ylimääräinen: 
- otsikkoteksti: "Kaupunginosapenkin muotoilukilpailu julkistettu" (otsikon väri sininen, jos mahdollista)
- painikkeen teksti: "Tutustu muotoilukilpailuun"
Painikkeesta ohjaus muotoilukilpailun sivulle eli kaupunginosapenkin aliosivulle.
Otsikon ja painikkeen paikka heti hankkeen kuvailutekstin perässä.

**Comment by ahukkanen** [comment]
Tämä on nyt toteutettu.

Otsikon väriä ei ole muutettu, koska kuten puhuimme Slackissa, niin tyylimuutokset pitäisi tehdä keskitetysti, jotta vältymme odottamattomilta ongelmilta, joita tietyt historiassa tehdyt poikkeukset aiheuttavat sivustokokonaisuuteen. Tämäntyyppiset poikkeukset ovat siis ongelmallisia tilanteissa, joissa tulevaisuudessa lähdetään muuttamaan sivuston tyylejä (esim. värityksiä, fontteja, taustavärejä, yms.).
