### ISSUE TITLE
Yhteistyökumppaneiden käyttöoikeudet

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#16]
Tutkin  käyttöoikeuksia Decidimissä, prosessikohtaisia, komponenttikohtaisia yms ja löysin aiheesta  [keskustelua](https://github.com/decidim/decidim/issues/2023).  Olisiko mahdollista luoda yhteistyökumppaneille (ns. "OSBU agentit") sellaiset käyttöoikeudet hallintapaneeliin, että he voisivat luoda uusia tapahtumia ja suunnitelmia (budjetit)?  He eivät kuitenkaan saisi muokata toisten tapahtumia ja suunnitelmia vaan ainostaan omiaan. Tämä on nyt aika korkean prioriteetin toive.  Tarvitaan yhteiskehittämisen vaiheessa joka näillä näkymin alkaa joulukuussa.

**Comment by ahukkanen** [comment]
**Yhteenvetona:**

En näe, että tätä voi sellaisenaan kovin järkevästi toteuttaa admin-/hallintapuolella. Jos nämä OSBU-agentit eivät tarvitse muita hallintapaneelioikeuksia, toteuttaisin tämän loppukäyttäjien puolella, eli en välttämättä näe tarpeen tehdä näistä käyttäjistä admin-käyttäjiä. Admin-puolella ei ole mahdollista tällä hetkellä antaa erilaisia admin-oikeuksia komponenttikohtaisesti.

Mielelläni hieman tarkentaisin tarpeita. Minulle näiden OSBU-agenttien rooli prosessissa on hieman epäselvä, mutta alla kuitenkin alustava aihio, miten tämän voisi toteuttaa.

**Toteutuksesta**

Käytännössä käyttöoikeudet Decidimin admin-paneelissa ovat ainoastaan seuraavilla tasoilla:
- Järjestelmäkäyttäjät - Järjestelmäylläpitäjät
- Organisaation yleiset käyttäjät - ylläpitäjä, käyttäjien hallinnoija tai peruskäyttäjä
- Prosessit ja kehitysryhmät - Hallinnoija, tarkastaja (collaborator) tai moderaattori

Komponenttikohtaiset oikeudet ovat tällä hetkellä sidoksissa käyttäjätilien varmennuksiin, eli siis juuri siihen "vahvaan tunnistautumiseen", mistä keskustelimme viime kerralla. Toisin sanoen nämä eivät liity hallintaoikeuksiin (admin), vaan loppukäyttäjien oikeuksiin.

Mietin, pystyisikö näitä komponenttikohtaisia oikeuksia toteuttamaan jotenkin sisäisellä ohjeistuksella teillä? Onko riskiä, että "OSBU agentit" tulevat editoimaan muiden tapahtumia tai budjetointiprojekteja?

Jos tämä on must ominaisuus, niin tämä varmaan on toteutettava kustomoinnilla. Noita varmennustapoja on mahdollista kehittää itse lisää, näkisin että yksi mahdollisuus toteuttaa tämä olisi seuraava:

- Lisätään uusi käyttäjäryhmä (organisaatio), mihin linkataan kaikki OSBU-agentit
- Lisätään Decidimiin mahdollisuus lisätä käyttäjiä käyttäjäryhmään (organisaatioon). Tämä on teknisesti mahdollista, mutta tällä hetkellä ei käyttöliittymästä. Tarkastettava löytyykö `decidim-members` -moduulista. Jos ei, sen voisi kehittää kyseiseen moduuliin.
- Toteutetaan uusi varmennustapa, joka käytännössä tarkastaa, että käyttäjätili kuuluu tiettyyn käyttäjäryhmään (organisaatioon). Tämä toteutettaisiin ulkoisena ominaisuutena, koska varmennustapoja voidaan lisätä.

Näiden toteutuksen jälkeen näkisin, että nuo tapahtumien ja suunnitelmien lisäys ja muokkaus pitäisi tuoda tuonne loppukäyttäjien näkymään, ei Decidimin hallintapaneeliin. Tämä siitä syystä, että nuo varmennustavat liittyvät nimenomaan loppukäyttäjien käyttöliittymään ja komponenteille ei ole hallintapuolella mahdollista asettaa erilaisia käyttäjärooleja.

Käyttöliittymään tarvittaisiin siis seuraavat uudet ominaisuudet:

- Tapahtumakomponentti - Tapahtuman lisääminen
- Tapahtumakomponentti - Tapahtuman muokkaaminen
- Budjetointikomponentti - Projektin lisääminen
- Budjetointikomponentti - Projektin muokkaaminen

Lisäksi näille komponenteille pitäisi kehittää lisää oikeuksia:

- Tapahtumat - Jos käyttäjätili varmennettu tavalla X (tietyn organisaation jäsen), salli tapahtuman lisääminen
- Tapahtumat - Jos käyttäjätili varmennettu tavalla X (tietyn organisaation jäsen), salli omien tapahtumien muokkaaminen
- Budjetointikomponentti - Jos käyttäjätili varmennettu tavalla X (tietyn organisaation jäsen), salli projektin lisääminen
- Budjetointikomponentti - Jos käyttäjätili varmennettu tavalla X (tietyn organisaation jäsen), salli omien projektien muokkaaminen

Näille "OSBU agenteille" jäisi sitten tehtäväksi varmentaa, että he kuuluvat tiettyyn organisaatioon. Tämä  tapahtuisi oman käyttäjätilin alla.

**Comment by katjahenttonen** [comment]
Ok, kiitos selkästä määrittelystä.  Tämä pitäisi sitten toteuttaa käyttöliittymän puolelle, kuten ehdotat. Asian hoitamisesta ohjeistuksella on keskusteltu, mutta sitä ei pidetty mahdollisena.   Osbu agentit ovat kuitenkin käytännössä organisaatioita (esim. asukasyhdistykset)  joten voisiko toteutusta yksinkertaistaa siten, että kaikille organisaatiokäyttäjille annettaisiin oikeudet luoda tapahtumia ja suunnitelmia? Tällöin pitäisi toki huolehtia siitä, ettei kuka tahansa voi luoda organisaatiokäyttäjää.  Organisaatiokäyttäjän luomisen voisi minun puolesta ehkä kokonaan poistaa käyttöliittymästä.  Hallintapaneelista sitten loisin nämä kaikki organisaatiot, joille annetaan tässä kuvatut oikeudet.

**Comment by ahukkanen** [comment]
@katjahenttonen En näkisi, että organisaatiokäyttäjien luontimahdollisuus itsessään on kovinkaan suuri ongelma, koska kaikki organisaatiokäyttäjät pitää hallintakäyttöliittymästä vielä erikseen hyväksyä. Voitte siis vain jättää hyväksymättä ns. "väärät organisaatiot" tai hylätä ne.

Toteutusta voidaan toki yksinkeritaistaa siten, että kaikki organisaatiokäyttäjät voivat luoda tapahtumia ja suunnitelmia kaikissa mahdollisissa prosesseissa. Uskon kuitenkin, että tämä saattaa potkaista takaisinpäin tulevaisuudessa ja järkevämpää olisi tehdä kerralla ns. kunnolla.

**Comment by katjahenttonen** [comment]
Kiitos, unohdin tuon että organisaatiokäyttäjät pitää hyväksyä erikseen.  Eli kaikki ok.  Ja, joo, olen samaa mieltä, että pidemmän päälle ehdottamasi toteutustapa on parempi.  Jos voimme tehdä sen kuvaamallasi tavalla ja silti pysyä aikataulussa muiden toimintojen suhteen, niin mennään sillä.  Mun pitää kuitenkin vielä keskustella speksistä kehityspäällikön kanssa. Palaan!

**Comment by katjahenttonen** [comment]
@ahukkanen  Kehityspäällikkö vahvisti että tämä omainaisuus tarvitaan.  Käyttötapaus ei ole vielä kovin tarkasti määritelty, mutta jos tämä toteutetaan tuolla ehdottomallasi "sofistikoituneemmalla" tavalla niin silloin tekniikka kyllä venyy kaikkiin käyttötapausskenaarioihin, joita on tällä hetkellä suunnittelupöydällä.

**Comment by ahukkanen** [comment]
Korvataan seuraavalla issuella:
https://github.com/City-of-Helsinki/decidim-helsinki/issues/43
