### ISSUE TITLE
Alapalkin rekisteriseloste-kohdasta linkki

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#17]
Alapalkin kohdasta "Rekisteriseloste" pitäisi olla suoraan linkki (open new window) tänne: https://www.hel.fi/static/liitteet/kanslia/rekisteriselosteet/Keha/Kanslia-EU-Osallisuuden-ja-palautteiden-rekisteri.pdf.  Osallistu-rivin valikosta rekisteriselosta haluttaneen kokonaan poistettavaksi, palaan valikkojen rakenteisiin myöhemmin.

**Comment by ahukkanen** [comment]
Mielestäni tämän osalta Decidimiin voisi ehdottaa sellaista ominaisuutta, että sivu voisi olla joko sivuston sisäinen sivu (kuten nyt) tai vaihtoehtoisesti linkki ulkoiseen sisältöön (näkyisi samalla tavalla sivuna alapalkissa ja Lisätietoja-sivulla, mutta linkkaisi ulkoiseen sisältöön).

Näkisin, että tämäntyyppisille linkeille voisi olla muutenkin tarvetta. Vastaavaa toiminnallisuutta löytyy myös monesta CMS-järjestelmästä.

Tein tälle ehdotuksen Metadecidimiin:
https://meta.decidim.org/processes/roadmap/f/122/proposals/13154
