### ISSUE TITLE
"Sisältää liian monta merkki" ilmoitus väärässä kohdassa

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#18]
Palvelussa tulee viesti "sisältää liian monta merkkiä" jos käyttäjä laittaa peräkkäin kaksi erikoismerkkiä, esimerkiksi kysymysmerkin ja huutomerkin.   En tiedä onko tälläistä tarvetta estää. Jos on tarve nin sitten viestin pitäisi olla oikea tyyliin "kahta erikoismerkkiä ei saa laittaa peräkkäin".  Katja voi laittaa bugin MetaDecidim-alustalle, korjauksella ei ole kiire.

**Comment by ahukkanen** [comment]
Tämä on itseasiassa Decidimin suunniteltua toiminnallisuutta. Decidmistä löytyy validaattori, joka tarkastaa ehdotusten tai viestien ns. "etiketin", missä yksi ehto on, että kahta välimerkkiä (!, ?, ¡ ja ¿) ei voi olla peräkkäin viestissä.

Vaihdoin suomenkieliseksi käännökseksi seuraavan:
`sisältää liian monta välimerkkiä peräkkäin (esim. ! ja ?)`

Tein tämän muutoksen sekä Helsingin Decidim repositorioon että Crowdiniin. En ole vielä ajanut päivitystä ninjaan tai tuotantoon.

Englanniksi (lähdekieli) tämä on tosin edelleen:
`is using too many marks`

Lisäsin kommentin tästä Englanninkielisestä termistä aiheeseen liittyvään GitHub-issueen Decidimin päärepositoriossa:
https://github.com/decidim/decidim/issues/2124

Tuo termi pitäisi päivittää itse Decidimiin, koska se on lähdekielen käännös, eikä siihen voi siten vaikuttaa Crowdinin kautta.

**Comment by katjahenttonen** [comment]
Ok, kiitokset!  Eihän tuo "etiketti" mitään haittaa niin kauan kuin viesti on sellainen, että käyttäjä ymmärtää mikä menee pieleen.

**Comment by katjahenttonen** [comment]
Löytyyköhän koko etiketti jostain dokumentoituna?  Tämä pitäis tulla käyttöohjeisiin jo valmiiksi, että millainen ehdotuksen pitää olla.

**Comment by ahukkanen** [comment]
Käsittääkseni ei ole dokumentaatiota tälle, mutta jos osaa muutaman rivin lukea Ruby, tämän voi päätellä täältä:
https://github.com/decidim/decidim/blob/8b9a573c00bdb7f3cbe9860c9332522f754c386a/decidim-core/app/validators/etiquette_validator.rb

Säännöt ovat seuraavat:
- Teksti ei saa sisältää yli 25% isoja kirjaimia (A-Z)
- Peräkkäin ei saa esiintyä kahta välimerkkiä (!, ?, ¡ ja ¿)
- Teksti ei saa sisältää yli 35 merkkiä pitkiä sanoja
- Tekstin on alettava isolla kirjaimella
- Tekstin on oltava pidempi kuin 15 merkkiä

Samoja sääntöjä sovelletaan ehdotukseen otsikkoon ja runkotekstiin. Lisäksi otsikolla on sääntönä, että sen pituus ei saa ylittää 150 merkkiä. Runkotekstin pituusrajoitus on kofiguroitavissa admin-puolelta.

Admin-puolelta voi myös lisätä ohjeet siihen ehdotuksen luontinäkymään:
- Proposal wizard "Create" step help text
- Proposal wizard "Compare" step help text
- Proposal wizard "Publish" step help text

Nämä näytetään kyseisten näkymien ylälaidassa, jos ne on määritelty.

**Comment by ahukkanen** [comment]
@katjahenttonen Tämä on nyt saatu mukaan Decidimin coreen (ks. https://github.com/decidim/decidim/issues/2124), eli tulee seuraavaan versioon. Käännökset on päivitetty Crowdiniin.

Myös noiden muiden virheviestien tekstejä päivitettiin kuvaamaan paremmin, mikä meni pieleen yo. speksin mukaisesti.

**Comment by katjahenttonen** [comment]
Hieno juttu!
