### ISSUE TITLE
Käyttäjän voitava vaihtaa suurpiiriä jossa äänestää

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#19]
Tällä hengelle kaupunginhallituksella on esitetty, että jokainen voi äänestää yhdessä vapaavalintaisessa suurpiirissä ja lisäksi kaupungin yhteisiä hankkeita.  Tämä edellyttää sitä, että ihminen voi itse valita jossain suurpiirinsä ja sitten oikeutta osallistua prosesseihin rajataan sen perusteella.   Tämä varmistuu lähivikkona.

**Comment by ahukkanen** [comment]
Tuo tieto suurpiiristä pitäisi kaiketi tulla jostain OmaStadin ulkopuolelta, eli siis esim. sieltä Helsinki-profiilista. Tämän toteuttamiseen tarvitsisimme hieman lisää speksejä, että minkä rajapinnan kautta tämä luetaan ja millä tavalla.

**Comment by katjahenttonen** [comment]
Joo, pohditaan tätä jossain vaiheessa myöhemmin.  Joku varmastikin sanoo, ettei Helsinki-profiilin pitäisi tallentaa sellaista tietoa, joka liittyy vain ja ainoastaan tähän yhteen osallistuvan budjetoinnin alustaan. Toki sieltä voitaisiin antaa esim. postinumeroon/kotiosoitteen perustava oletussuurpiiri, mutta ihmisen pitäisi voida itse vaihtaa se  Decidimin puolella.  Meneekö liian hankalaksi?

**Comment by ahukkanen** [comment]
Kyllä tätä tietoa voidaan säilyttää Decidimin päässäkin, mutta mietin lähinnä, että tämäntyyppinen tieto olisi hyvä säilyttää keskitetysti. Jos henkilön kotiosoite vaihtuu, niin tällöin vaihtuu myös suurpiiri.

Lähinnä vain pitäisi tietää, millä tavalla tämä toteutetaan. Samaa tietoa tuskin kannattaa kysyä kahdesti, jos suurpiiri tai osoite on jo kyseiselle henkilölle tiedossa.

**Comment by katjahenttonen** [comment]
Toki tieto asuinpaikasta säilytetään toki keskitysti. Mutta siis ideana on, että henkilö voi valita ITSE suurpiirin, jonka äänestykseen osallistuu, asuinpaikasta rippumatta.  Eli henkilö X voi asua Itäisen suurpiirin alueella, mutta siltäi osallistua Läntisen suurpiirin budjetointiprosessiin jos itse näin haluaa.  Eli suurpiirivalinta ei ole mitenkään kytketty osoitteeseen.

**Comment by katjahenttonen** [comment]
Tämä on nyt sovittu siten että henkilöllä on yksi postinumeron (VRK) tai koulukoodin (mPassID) mukaan määräytyvä OLETUSsuurpiiri, jossa hän lähtökohtiasesti äänestää.  Jollain kikkavitosella ihmisen pitää pystyä vaihtamaan suurpiiriä halutessaan, tästähän puhuimmekin jo keväällä.   Käytännössä suuret massat ihmiset varmastikin äänestävät heille oletuksena tarjotussa suurpiirissä.

**Comment by katjahenttonen** [comment]
@ahukkanen  kuten muista tiketeistä ilmenee niin nyt ekalla kierroksella käyttäjän oletussuurpiiri on tarkoitus määritellä postinumeron perusteella.  Muistaakseni VRK:stakaan ei saa suurpiirikooodia suoraan? Laitan liitteeksi taulukon, josta on mätsattu suurpiirit ja postinumeroalueet. 
[Kopio postinumerot_suuralueittain.xlsx](https://github.com/City-of-Helsinki/decidim-helsinki/files/3485273/Kopio.postinumerot_suuralueittain.xlsx)

**Comment by ahukkanen** [comment]
Tämä toimii nyt niin, että tuolla "Budjetointi" -varmennuksella varmennettaessa käyttäjiä, käyttäjän tulee ensin identifioida itsensä mahdollisilla tavoilla (Suomi.fi tai MPASSid). Tämän jälkeen käyttäjä voi valita suurpiirin listasta, missä haluaa äänestää.

Listaan tarjotaan ensimmäisenä käyttäjän osoitetietoa vastaavaa suurpiiriä, jos se löytyy (muutoin aina ensimmäinen). MPASSid:n valintaa varten tarvitaan vielä ne koulumäppäykset, jotka toistaiseksi puuttuvat.
