### ISSUE TITLE
Osallistu.hel.fi --> OmaStadi.hel.fi

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#2]
Osallistu palvelu ollaan brändäämässä uudestaan nimelle MunStadi. Tämä vaatisi domain-osoitteen muutokseen vielä ennen marraskuuta. Vanha osallistu.hel.fi pitää toki myös ohjata samaan paikkaan, koska sitä on jo mainostettu. Selvitän itse mitä tämä vaatii, mutta tiedoksi!

**Comment by katjahenttonen** [comment]
Tämä on nyt odotustilassa, ei ehkä tehdäkään.

**Comment by katjahenttonen** [comment]
Haen uutta domainia omstadi.hel.fi  (tai omastadi.helsinki, tämäkin on vaihtoehtona vielä) ASAP.  Voisitko 
 laittaa minulle nimipalvelime ja muut tiedot asap, jotta saan kerrotua meidät IT-tuelle mihin ko. domain pitäisi reitittää?

**Comment by ahukkanen** [comment]
Laitoin tiedot mailitse @katjahenttonen

**Comment by katjahenttonen** [comment]
Kiitos!   Minulle tuli tieto, että omastadi.hel.fi  nyt lisätty DNS-palveluun ja loppu pitäisi olla teidän konfattavissa. Osoite olisi hyvä ottaa käyttöön suht. pikaisesti, koska osoitetta jo ollaan päivittämässä mainosmateriaaliin.  Vanhantuvan osoitteen osallistu.hel.fi olisi hyvä johtaa toistaiseksi vielä jonkin aikaa samaan paikaan (302 redirect tms).

**Comment by ahukkanen** [comment]
Tämä on nyt toteutettu ja ohjaukset lisätty.

Mitä tehdään ninja-domainin kanssa?

**Comment by katjahenttonen** [comment]
@ahukkanen  Tunnistamon ohjauksissa näyttäisi vielä olevan ongelmia.  Jos menen palvelun omastadi.hel.fi osoitteen kautta niin en pääse Tunnistamoon vaan saan viesti: "Redirect URI Error
The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri)."

Olin muuten ajatellut ninja voisi pysyä nykyisellään - ainakin siihen asti kunnes osallistu.hel.fi otetaan muuhun käyttöön (tämä tuskin on ihan pian).  Vai onko joku syy siihen, että testipuolen domain-nimen pitäisi vastata pääpalvelun domain-nimeä?

**Comment by ahukkanen** [comment]
Totta tosiaan, Tunnistamoon pitää tehdä vielä konffausmuutos.

Laitan teidän päähän viestiä, että osoite on vaihtunut.

**Comment by ahukkanen** [comment]
@katjahenttonen Muutos on toteutettu nyt myös Tunnistamoon.
