### ISSUE TITLE
Osoitteen tai liitteen syöttäminen muuttuu pakolliseksi jos kerran yrittää tehdä niin  

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#21]
Lähtökohtaisesti valinnaiset kentät  (osoite ja liite) muuttuvat jossain tilanteissa pakolliseksi vain siksi, että käyttäjä ensin yrittää syöttää niihin jotain.

Jos käyttäjä syöttää vääränmuotoisen osoitteen eikä ohjelma hyväksy sitä, sen jälkeen hän haluaa usein jättää ehdotuksensa ilman osoitetta.  Kun osoitetta on kerran yritttänyt syöttää niin siitä tulee pakollinen. Vaikka poistaisi rastin "Liittyy osoitteeseen" -kohdasta niin edelleen  palvelu vinkuu osoitetta eikä käyttäjä pääse eteenpäin syöttämättä sitä.  Tämän saan toistettua joka kerta.

Tiedostoa liitteässä ilmenee usein samanlainen ongelma, käyttäjä yrittää lisätä tiedoston ja sitten peruukin liittämisen kesken kaiken. Tämän jälkeen ohjelma alkaa usein vaatia liitettä eikä käyttäjä enää pääsekään eteenpäin syöttämättä liitettä.  En saa toistettua joka kerta, mutta muutaman kerran tämä tilanne on tullut minulle ja useille testikäyttäjille vastaan.  

Tälläiset ovat näennäisesti pieniä asioita, mutta ärsyttävät käyttäjiä paljon.

**Comment by katjahenttonen** [comment]
Sijainti tai liite muuttuu tietyissä tilanteissa edeleen pakolliseksi jos henkilö vain käväisee hiirellä tyhjässä kentässä. Tänään 8 testihenkilöstä kolme onnistui pääsemään tilaan, jossa ohjelma vaatii pakollisena sijaintia tai liittettä vaikka henkilö ei halunnut sitä antaa.

**Comment by ahukkanen** [comment]
Osoitekentälle on tehty seuraavat toimenpiteet, kuten juttelimme Slackissa:

- Vaikka osoitekenttä olisi avattu, se ei ole enää pakko syöttää, eli sen voi jättää tyhjäksi
- Osoitetta ei pakoteta, vaikka se olisi kertaalleen syötetty, eli tyhjentämällä kentän osoitteen saa pois

Lisäksi näihin liittyen, lomakkeelta on poistettu ns. "etikettivalidaattori", joka pakotti ne tietyt säännöt otsikolle ja tekstille. Tällä hetkellä ainoat säännöt niille on, että ne on syötetty.

Muutokset ovat nyt ninjassa, missä niitä voi kokeilla.
