### ISSUE TITLE
Selkeä siirtymä ehdotuksen syöttämisen jälkeen

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#22]
Sen jälkeen kun käyttäjä on syöttänyt oman ehdotuksensa, hän ei ei useinkaan tajua miten pääsee jatkamaan kaikkien ehdotusten katseluun. Tämän voisi hoitaa ohjeviestillä (muutoinkin jollekin "kiitos ehdottamisesta" -viestille olisi tarvetta) tai uudella painikkeella.

**Comment by ahukkanen** [comment]
Mielestäni yksittäisen ehdotuksen sivulle olisi joka tapauksessa syytä lisätä linkki "Takaisin ehdotuksiin". Tämä on käynyt myös itselläni mielessä, että olisi tarpeellinen.

Ratkaisisiko se tämän ongelman?

**Comment by katjahenttonen** [comment]
Jep, painike "Takaisin ehdotuksiin"  hoitaisi homman  Tämän lisäksi jonkinlaiselle kustomoitavissa olevalla "kiitosviestille" ehdotuksen jättämisen jälkeen olisi myös tarvetta, mutta se ei ole niin kiireellinen.

**Comment by ahukkanen** [comment]
Tähänkin liittyen itse asiassa löytyi jo kehitysehdotus Metadecidimistä:
https://meta.decidim.org/processes/roadmap/f/122/proposals/13272

Tuokaan tuskin tosin ehtii aivan heti kehityslistalle, mutta kannattaa silti äänestää tulevaisuutta silmällä pitäen.
