### ISSUE TITLE
Rekisteröintilomakkeella radiobotton voi mennä väärälle riville

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#24]
Mobiilaitteella (tai muulla kapealla näytöllä) käyttäjiä häiritsee rekisteröitymislomakkeessa se, että "Organisaationa/Yhteisönä" -teksti menee eri riville kuin siihen liittyvä "pallura" (radiobutton). Pieni asia mutta varmaan myös pieni korjata.

**Comment by ahukkanen** [comment]
@katjahenttonen Pystytkö linkkaamaan, mistä löysit tuon informaation? Luulen, että jos se ei ole vielä GitHub-issuena, niin se ei ole tulossa ihan lähitulevaisuudessa. 

Tuo alkuperäinen ongelma on sinänsä helppo korjata lisäämällä vain rivinvaihto näiden väliin.

**Comment by ahukkanen** [comment]
Tämä on korjattu niissä edellisissä päivityksissä. Nyt menee kokonaan toiselle riville.
