### ISSUE TITLE
Kommentointi ei toimi IE11:ssa

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#25]
Kommentointi ei toimi IE11:ssa lainkaan,  ehdotuksiin tulleita kommenteja ei näe eikä omaa kommenttai voi lisätä.

**Comment by ahukkanen** [comment]
@katjahenttonen Tämä on jo korjattu Ideapaahtimoon ja tulossa myös siten muihin instansseihin, kuhan ajetaan päivitykset.

Tässä commit, joka korjasi tämän:
https://github.com/City-of-Helsinki/decidim-helsinki/commit/7b7226e8ac81b59792d5f24b97265a0340bcca7c

Se on tosin hieman "hassusti" nyt korjattu tähän Helsingin instanssiin ja tästä on myös olemassaoleva issue Decidimin repositoriossa:
https://github.com/decidim/decidim/issues/3562

Olen kommentoinut kyseiseen issueen ehdotukseni, kuinka tämäntyyppiset ongelmat voitaisiin korjata "paremmin" koko plattaan.
