### ISSUE TITLE
Decidim selkosuomeksi?

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#26]
Meillä on tullut paljon pyyntöjä, että OmaStadi-palvelu pitäisi saada julkaistua myös selkosuomeksi.  Olisiko mahdollista saada Decidimiin lisätty uusi tuettu kieli, joka olisi selkosuomi eli Plain Finnish.  Käytännössä pitäisi varmaan merkata Finnish (standard) ja Finnish (plain) tai jotain siihen päivin.  Selkosuomenkielisiin tiedostoihin pitäisi oletuksena kopioida normisuomen termit ja sitten muuttaa niitä tarpeen mukaan. Suurimmat muutokset koskevat meidän omia tekstisisältöjä, mitä  myös Decidimistä tulevia tekstejä pitäisi päästä muokkaamaan.

**Comment by ahukkanen** [comment]
Tein pyynnön Crowdiniin, jos saataisiin tämä ihan virallisten kielien joukkoon.

**Comment by ahukkanen** [comment]
Decidimin Crowdin-projektin ylläpitäjät ovat nyt lisänneet selkosuomen uudeksi kieleksi:
https://crowdin.com/project/decidim/fi-plain

Nyt sitä voi siis kääntää Crowdinissa.

**Comment by katjahenttonen** [comment]
Ok, hienoa. Kävin hakemassa itselleni oikeuksia tohon kieleen. Käytännössä Ensin  varmaan aloitamme siitä että käännämme sisällöt ja sen jälkeen etenemme kääntämään valikkoja yms. Crowdinissa.

**Comment by katjahenttonen** [comment]
Meidän käännöstöiden ei tarvii olla gitissä, joten suljen tämän.
