### ISSUE TITLE
Muistiinpanojen ja päätösten siirtäminen suunnitelmiin

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#27]
Ehdotuksille on mahdolista lisätä halintakäyttöliittämästä sisäisiä huomioita/suunnitelmia.  Lisäksi ehdotuksiin on mahdollista vastata (Hyväksytty/Hylätty) jolloin vastaus näkyy näyttävästi ehdotuksessa. Osatko @ahukkanen  "lonkalta" arvioida onko vastaavan toiminallisuuden siirtäminen suunnitelmiin suurikin työ?  En vielä tiedä onko suunnitelmia tarpeen hylätä  (toivottavasti ei), mutta ainakin kustannusarvioinnin yhteydessä pitäisi työntekijöiden voida sisäisesti keskustella suunnittelmasta ja kustannusarvioille pitäisi voida kirjoitttaa perustelu näkyvästi kaupunkilaisille. Monesti kaupunkilaisten näkökulmasta asiat tuntuvat tosi kalliilta, joten on tärkeää perustella, että mistä hintalappu koostuu.

**Comment by ahukkanen** [comment]
@katjahenttonen Onko tässä siis tarpeena, että tietty ryhmä keskustelee suunnitelmasta ennen kuin se jalostetaan varsinaiseksi budjetointisuunnitelmaksi? Suunnitelmien itsessään pitäisi olla lähtökohtaisesti jo mietitty siinä määrin, että ne ovat toteutettavissa niille asetetun budjetin raameissa, eli siis niitä ei enää hyväksytä tai hylätä, vaan valinta tapahtuu budjetointiprosessin kautta.

Jos näin on, toteuttaisin tämän mieluummin ehdotukset- tai yhteistyöehdotukset-ominaisuudella. Tällöin siis tätä keskustelua voitaisiin käydä ehdotuksen sisällä ja sitten myöhemmin liittää kyseinen ehdotus suunnitelmaan, jolloin se näkyy linkattuna suunnitelman sivulla.

Yhteistyöehdotukset toimivat siten, että niitä voi muokata ja työstää useampi käyttäjä ennen niiden julkaisua. Uusien muokkaajien pitää pyytää muokkausoikeutta ehdotuksen alkuperäiseltä luojalta. Kun ehdotus on valmis, se voidaan julkaista varsinaisena ehdotuksena.

Ehdotusten sisällä pystytään rajaamaan käyttöoikeuksia tietyn varmennuksen (authorization) mukaan. Esimerkiksi voidaan määritellä, että jos käyttäjä kuuluu tiettyyn ryhmään, vain hän voi luoda uusia ehdotuksia. Tällöin siis kuka tahansa näitä ei pääsisi luomaan.

Palvelisiko tällainen lähestymistapa tätä tarvetta?

Suunnitelmiin voi myös lisätä liitetiedostoja, jos tarpeena on siis vain tämän tiedon jakaminen ulospäin.

Tuo hyväksymis/hylkäysominaisuus ei siis mielestäni kuulu suunnitelmiin, minkä takia en sitä toteuttaisi.

**Comment by katjahenttonen** [comment]
Yhteistyö ehdotus vastaa muutoin tarpeitamme,  paitsi että  siihen ei ole mahdollista ilmeisesti linkata toisia ehdotuksia.  En myöskään ole ihan varma  koska en ole nähnyt  vielä tätä toiminallisuutta - ilmeisesti tullut mukaan uuteen versioon, jota ei ninjaankaan ole vielä asennettu?  Jutellaan tästäkin maanantaina.

**Comment by ahukkanen** [comment]
@katjahenttonen Kyllä kyseinen ominaisuus löytyy ninjasta ja tuotannostakin. Molemmissa pyörii viimeisin major-versio (0.14).

Huomaathan, että tämän voi asettaa päälle siis Ehdotukset-ominaisuuden asetuksista, ei siis itse prosessin asetuksista.

Olet oikeassa, että yhteen ehdotukseen (tai yhteistyöehdotukseen) ei voi linkata muita ehdotuksia, koska nämä itsessään ovat ehdotuksia. Toisaalta, voisiko siihen liittyvät ehdotukset vain linkata ehdotuksen kuvaukseen?

**Comment by ahukkanen** [comment]
Korvataan seuraavalla issuella:
https://github.com/City-of-Helsinki/decidim-helsinki/issues/43
