### ISSUE TITLE
Kävijämäärätilastot

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#29]
Tero Kantalo on käsittääkseni sopinut jo kävijämäärien keräämisestä Snoobilla ja toimittanut tarvittavat tiedot? Vai tarvitse vielä jotain tätä varten @ahukkanen ?

**Comment by ahukkanen** [comment]
Teron toimittama Snoobin seurantakoodi on asennettu OmaStadin tuotantoympäristöön.

Sieltä Snoobin päästä tietysti voisi tarkastaa, että se toimii.

**Comment by katjahenttonen** [comment]
Snoobissa kävijätilastot näyttävät olevan nollilla, joten jossain on vielä vikaa. Ei toimi siis.
