### ISSUE TITLE
Organisaatiokäyttäjien luominen ei toimi

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#3]
En saa osallistu.hel.fi osoitteessa luotua organisaatiokäyttäjää.   Kun luon organisaatiokäyttäjän niin järjestlemän mukaan kaikki menee onnistuneeksi.  Käyttäjällä ei kuitenkaan pääse kirjautumaan eikä sähköpostiin tule vahvistusviestiä.  Vika ei liene pelkässä sähköpostisssa koska saan virheviestin myös pyytäessäni vahvistusviestin uudelleen (katso kuva).
![osbuhel](https://user-images.githubusercontent.com/39044068/45145296-0548cc80-b1c9-11e8-9bae-a5dd8acf9257.PNG)

**Comment by ahukkanen** [comment]
@katjahenttonen Testasin organisaatiokäyttäjän rekisteröintiä lokaalisti ja se meni läpi odotetusti. Järjestelmä lähetti varmistusviestin, minkä klikkauksen jälkeen pääsin kirjautumaan kyseisellä käyttäjätilillä.

Tarkastin myös tuotantoympäristöstä, sieltä ei löytynyt käyttäjätiliä tietokannasta kuvassa esiintyvällä sähköpostilla. Voisitko kokeilla vielä luoda käyttäjää uudestaan rekisteröitymislomakkeella?

Huomioithan, että uudet organisaatiot pitää myös varmentaa admin-paneelista kohdasta Käyttäjät > Käyttäjäryhmät. Tätäkin ennen kuitenkin pääsee jo kirjautumaan, kunhan sähköpostiosoite on varmennettu. Ainoastaan organisaationa ei voi kommentoida, mikäli organisaatiota ei ole vielä varmennettu.

**Comment by katjahenttonen** [comment]
En ole vieläkään saanut organisaatiokäyttäjää luotua.  Tämä ongelma tuli esille myös testaustilaisuudessa, kukaan mukaan ei toistaiseksi meidän päässä ole saanut luotua organisaatiokäyttäjää.  Yritän selvitellä vielä itsekin.

**Comment by ahukkanen** [comment]
Sain myös Ninjassa luotua organisaatiotilin. Käy katsomassa sieltä hallintapaneelin osiosta Käyttäjät > Käyttäjäryhmät. Siellä näkyy uusi organisaatiorekisteröityminen odottamassa hyväksyntää.

Epäilen, että jokin kenttä jää rekisteröitymisessä virheelliseksi, minkä takia organisaatiokäyttäjän rekisteröityminen ei mene läpi. Ainakin muutama validaatioehto tuossa on:

- Organisaation nimi ei saa olla mikään olemassa olevista
- Organisaation "asiakirjan numero" ei saa olla kenelläkään muulla käytössä

**Comment by katjahenttonen** [comment]
Tämä on kunnossa!  Ongelma johtui siitä, että käytettiin testivaiheessa asiakirjanumeroa 123456.  Tämä numero pitäisi varmaankin muuttaa suomennokseksi muotoon "Y-tunnus" tai yhteisötunnus, sillä suomessahan organisaatiolla ei ole mitään "asiakirjanumeroa".

**Comment by katjahenttonen** [comment]
Olen vaihtanut Crowdinissa organisaatiokäyttäjän kohdalle "document number" käännökseksi yhteisötunnus.  Kyseessä ei ole kirjaimellinen käännös, mutta luulisin tämän palvelevan parhaiten kaikkia käyttäjiä suomessa.

**Comment by katjahenttonen** [comment]
Jos em. käännös Crowdinissa on ok, niin voidaan sulkea.
