### ISSUE TITLE
Sisäisen "tagin" lisääminen

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#32]
Meillä on tarve, että  kaupungin pitäisi pystyä lisäämään hallintakäyttöliittymän puolelta kullekin ehdotuksellä "tagi" joka kertoo minkä toimialan vastuulla asia on.  Tähän voisi käyttää aihepiiriä, mutta heti kun aihepiirin määrittelee niin se pomppaa myös ehdotuslomakkeelle.  Ehdottajilta itseltään emme kuitenkaan halua asiaa kysyä.  Tägi voisi sinänsä hyvinkin näkyä käyttöliittymässsä ja olla vaikka hakuehtonakin kunhan se ei näy ehdotuslomakkeella. Miten tämän saisi onnistumaan?

**Comment by ahukkanen** [comment]
Pitääkö tämän tägin näkyä myös ehdotuksessa ulkopuolisille käyttäjille?

Mietin, että jos tämä on vain teidän sisäisiä merkkaustarpeita varten, voisiko tähän käyttää sitä "Omat muistiinpanot" -ominaisuutta?

Jos tämän pitää näkyä myös ulospäin, voisiko vastuutoimialan määritellä virallisen vastauksen avulla tekstinä?

Tein tästä joka tapauksessa kehitysehdotuksen Metadecimiin:
https://meta.decidim.org/processes/roadmap/f/122/proposals/13324

**Comment by katjahenttonen** [comment]
Ulospäin näkyminen ei ole välttämätöntä. Sisäiset muistiinpanot eivät tule kysymykseen, koska toimialojen pitää pystyä nopeasti suoraan listasta näkemään mitkä ehdotuksen koskevat heitä ja sitten exporttaamaan ne Exceliin.  Ei ole tässsä kohdin järkevää kliksutella auki muistiinpanoja jokaisen ehdotuksen kohdalla.

**Comment by katjahenttonen** [comment]
Pitää toteuttaa ja määritellä tarkemman, otan itselleni työjonoon.

**Comment by katjahenttonen** [comment]
Tämä on otettu mukaan toiseen tikettiin joten suljen.

**Comment by katjahenttonen** [comment]
Suljen duplikaattina.
