### ISSUE TITLE
"Sivua ei löydy" käyttäjän luomisen jälkeen

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#35]
"Sivua ei löydy"  ilmoitus (klassinen selaimen 404 virhe)  näytetään joissakin tapauksissa käyttäjän luomisen jälkeen kun käyttäjä menee vahvistamaan sähköpostiosoitettaan. Käyttäjä luodaan normaalisti, mutta virheilmoitus tulee silti.  Tästä on tullut satunnaisia raportteja aiemmin, mutta en ole pystynyt toistamaan virhettä (enkä saanut tarkempia tietoja virheen raportoineilta).  Minulla tuli viime viikolla nyt sama virhe kun loin käyttäjää sähköpostiosoitteelle omastadi.hel.fi.   En ole ehtinyt testata tarpeeksi löytääkseni selkeitä parametreja milloin virhe esiintyy ja milloin ei.

**Comment by ahukkanen** [comment]
Tätä en saa lokaalisti toistettua millään. Kokeilin puoli tuntia naputella erilaisia rekisteröitymiskeissejä ja kaikki toimi täysin normaalisti.

Eli kaivataan lisää ohjeita bugin toistamiseen, jotta pystytään korjaamaan.

**Comment by katjahenttonen** [comment]
Ok.  Mulle on tullut tämä kerran pari syksyn aikana vastaan. Otan tän omaan työjonoon jo yritän testailla lisää.

**Comment by katjahenttonen** [comment]
Suljetaan toistaiseksi.  Avataan uudelleen jos tarvis.
