### ISSUE TITLE
Virallistettujen käyttäjien kommenttien korostaminen

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#4]
Meillä oli alkuaikoina puhetta, että organisatiokäyttäjien kommentit pitäisi korostaa, esimerkiksi vaihtamalla väriä. Parempi olisi oikeastaan korostaa kaikkien virallistuttujen käyttäjien kommentit, koska esim. stadiluotsit, kaupunginvaltuutetut ja pormestarit halauvat varmaan kommentoida omalla nimellään eivätkä organisaationa. Virallistamissysteemi on hyvä muutoin, mutta kommentit eivät kovin hyvin erotu massasta, tulee vain pieni tähti viereen.  Voisiko tätä helposti parantaa?

**Comment by ahukkanen** [comment]
Käytännössä nuo tyylittelymahdollisuudet kommenttikomponentitssa on jätetty aika vähäisiksi. Kyllä tämän varmaan saa jollain jQuery-hackilla tehtyä seuraavalla lähestymistavalla:

1. Odota, että kommentit ovat latautuneet.
2. Etsi kaikki kommentit, jotka sisältävät sen tähtimerkin (badge)
3. Lisää kaikkiin näihin kommentteihin uusi CSS-luokka, jolla 

Tätä pitäisi hieman tarkemmin miettiä, miten ne väritetään ja miten se vaikuttaa niihin keskusteluketjuihin, eli siis jos kommentti saa vastauksia. Vastauksethan tulevat aina vastavärillä ja vastauksen vastaukset jälleen sillä kommenttivärillä.

Vaikuttaako tämä muutos siis koko keskusteluketjuun vai ainoastaan kyseisten virallistettujen käyttäjien yksittäisiin kommentteihin missä tahansa (ketjussa tai sen ulkopuolella)?

Tästä olisi hyvä varmaan piirtää jokin malli, että miltä nuo voisivat näyttää eri tilanteissa:

1. Normaalit tilin kommentit allekkain, virallistettujen tilien kommentteja välissä.
2. Virallistetun tilin kommentin vastaukset, sekä normaaleilta tileiltä että virallistetuilta tileiltä.
3. Normaalin tilin kommentin vastaukset, seassa vastauksia virallistetuilta tileiltä.
4. Molemmat 2. ja 3. myös vastausten vastauksille (eli miltä näyttää, jos ketju jatkuu "syvemmälle")

Varmaan "helpoin" tapa toteuttaa tämä olisi huomioida vain yksittäiset kommentit ja tämä muutos ei vaikuttaisi kommenttiketjuihin, vaikka kommenttiketjun olisi aloittanut virallistettu tili.

Lisäsin aiheeseen liittyen myös kehitysehdotuksen Metadecidimiin, joka helpottaisi kustomoinnin toteutusta:
https://meta.decidim.org/processes/roadmap/f/122/proposals/13136

Silti nuo yo. käyttöliittymäpointit pitäisi itse miettiä, koska tuota UI-muutosta tuskin halutaan Decidimin coreen mukaan.

**Comment by katjahenttonen** [comment]
Ok, kiitos tarkennuksesta! Tämä ei ole korkean prioteetin ominaisuus, joten voidaan varmaan unohtaa toistaiseksi.  Jos ehdotuksesi Decidim-yhteisössä etenee, niin palataan sitten tähän uudestaan.
