### ISSUE TITLE
Sosiaalisen median jakokuvat

### ISSUE THREAD

**Issue by ahukkanen** [City-of-Helsinki/decidim-helsinki#40]
Lisätään palvelulle oma sosiaalisen median jakokuva, joka on oletuksena kaikilla sivuilla koko palvelun laajuisesti. Prosessien sisällä ei siis käytetä prosessiin liittyvää värikuvaa SOME-kuvana.

Poikkeuksena tähän ovat yksittäiset ehdotukset, missä halutaan näkyvän käyttäjän syöttämä kuva. Jos käyttäjä ei ole syöttänyt kuvaa, tällöin näytetään oletuskuva.

**Comment by ahukkanen** [comment]
@katjahenttonen Määritelkää kuva ja lähettäkää minulle.

**Comment by katjahenttonen** [comment]
@ahukkanen  Voisiko oletuskuva olla automaattisesti etusivun pääkuva?  Vai onko siihen pakko asettaa erikseen joku kuva, jota emme voi itse vaihtaa?

**Comment by katjahenttonen** [comment]
![hki_os_riippumatto_some](https://user-images.githubusercontent.com/39044068/48853013-3cd21880-edb7-11e8-9c12-ee62074275fb.jpg)

**Comment by ahukkanen** [comment]
Nämä on päivitetty meta-kenttiin "og:image" ja "twitter:image", joista SOME-palveluiden nämä pitäisi ladata. Jostain syystä kuitenkin esim. jaettaessa etusivun linkkiä FB:iin, se näyttää edelleen hero-kuvan.

Tutkittava lisää.

**Comment by katjahenttonen** [comment]
Uskoisin olevan täysin ok, että etusivun linkkiä jaettaessa näkyy se hero-kuva.  Eli ei tarvitse tätä korjata.  Tärkeintä oli elimoida ne keltaiset boksit pois, mikä onkin näköjään jo tehty.  Lisäksi käyttäjien syöttämät kuvat pitäisi saada näkyville kun ehdotuksia (tai seuraavassa vaiheessa suunnitelmia) jaetaan somessa.

**Comment by katjahenttonen** [comment]
Tämä toimii nyt ok, paitsi että naapuritiimiltä saatu kuva ei ole oikein tarkoitukseen soveltuva.  Jätän auki etten unohda, yritän saada tähän paremman kuvan.
