### ISSUE TITLE
Suositukset näkyvät listauskorteilla, vaikka eivät ole käytössä

### ISSUE THREAD

**Issue by ahukkanen** [City-of-Helsinki/decidim-helsinki#41]
Jos suositukset eivät ole käytössä ehdotuksille, suositukset eivät tulisi näkyä kortilla (peukkuikoni alakulmassa).

**Comment by katjahenttonen** [comment]
Suositukset on otettu takaisin käyttöön eikä asiaa enää muuteta ehdotusvaiheen kuluessa. Tämä korjaus ei siis ole kiirellinen, mutta hyvä hoitaa ettei jää roikkumaan.
