### ISSUE TITLE
Decidim-päivitys: v0.15

### ISSUE THREAD

**Issue by ahukkanen** [City-of-Helsinki/decidim-helsinki#42]
Päivitetään Decidim uusimpaan 0.15-versioon.

Tärkeimpänä uudistuksena tämän osalta on sivujen aihealueet (Topics), joiden mukaan sivuja voidaan kategorisoida erilaisiin kokonaisuuksiin (esim. Ohjeet).

Tämän jälkeen Osallistumisohjeet-ryhmästä voidaan siirtää kaikki sivut yhteen aihealueeseen yleisiin sivuihin.

**Comment by ahukkanen** [comment]
@katjahenttonen Ninjassa pyörii nyt versio 0.15.

Testaattehan siellä vielä sisäisesti ennen kuin viedään päivitys tuotantoon?

**Comment by katjahenttonen** [comment]
Ok, mä testaan ja käyn tämän myös kehittämispäällikön kanssa läpi.   Kuittaan sitten kun asia on kunnossa. Otan omaan työjonoon.
