### ISSUE TITLE
Suunnitelmien yhteistyöstämiseen uusi Decidim-komponentti (loput työt alkuperäisestä määrittelystä)

### ISSUE THREAD

**Issue by ahukkanen** [City-of-Helsinki/decidim-helsinki#43]
Toteutetaan uusi Decidim-komponentti, jonka avulla ideoita voidaan yhteistyöstää suunnitelmiksi.

Tarpeena ovat eri sidosryhmät, joista jokainen voi aloittaa uuden suunnitelman ja "vetää" itsenäisesti projektia eteenpäin. Sidosryhmiä, jotka uuden suunnitelman voivat aloittaa, ovat mm. asukkaat, fasilitaattorit ja stadiluotsit.

Käytämme pohjana tälle uudelle komponentille Decidimin Ehdotukset-komponentista löytyvää yhteistyöstämiskomponenttia. Tämän pohjalta jaamme tämän yhteistyöstämisen kokonaan omaan komponenttiinsa ja tuomme siihen uusia ominaisuuksia.

Olemassaolevasta yhteistyöstämiskomponentista tarvitsemme seuraavat ominaisuudet:

- Uuden suunnitelman "käynnistäminen" kenen tahansa käyttäjän toimesta
- Tästä käyttäjästä tulee suunnitelman "vetäjä", hän päättää kuka saa osallistua kyseiseen suunnitelmaan
- Kuka tahansa muu käyttäjä voi pyytää pääsyä osallistumaan suunnitelman suunnitteluun
- Suunnitelman "vetäjä" hyväksyy tai hylkää liittymispyynnöt
- Hyväksymisen jälkeen kuka tahansa mukaan päässyt käyttäjä voi muokata suunnitelmaa
- Suunnitelman muokkauksen jälkeen siitä luodaan aina uusi versio, vanha versio jää talteen ja nähtäväksi
- Kaikki alustan käyttäjät näkevät koko versiohistorian sivulla halutessaan

Lisäksi ominaisuutta tulee laajentaa seuraavasti:

- Lisättäessä uutta suunnitelmaa, se tulee voida liittää myös ehdotuksiin Ehdotukset-komponentista
- Linkattuja ideoita tulee voida lisätä tai poistaa prosessin aikana
- Jos jokin idea on jo linkattu tiettyyn suunnitelmaan, sitä ei enää voi linkata muihin suunnitelmiin

Hallintakäyttäjien puolella tarpeet ovat seuraavat:

- Yhteistyöstämissuunnitelmista tulee voida luoda suoraan budjetointisuunnitelmia. Hallintakäyttäjä voi siis määrätä, että tietystä suunnitelmasta luodaan uusi budjetointiprojekti. Toiminnallisuus kopioi tarvittavat tiedot suunnitelmasta (otsikko, kuvaus, liittyvät ehdotukset) ja hallintakäyttäjän tehtäväksi jää hintalapun määrittely ja suunnitelman lisäys.
- Hallintakäyttäjien tulee voida myös sulkea tiettyjen suunnitelmien muokkaus tarvittaessa. Luotaessa budjetointisuunnitelma, yhteistyöstetty suunnitelma sulkeutuu automaattisesti. Sulkeutumisen jälkeen suunnitteluryhmä ei enää voi muokata kyseistä suunnitelmaa.

Liittyy myös seuraaviin aikaisempiin issueihin:

- https://github.com/City-of-Helsinki/decidim-helsinki/issues/16
- https://github.com/City-of-Helsinki/decidim-helsinki/issues/27

**Comment by katjahenttonen** [comment]
Tässä vielä päivitetetyt käyttäjätarinat sekä ehdotuslomakkeen kentät.
[Suunnitelmalomake1.0.pptx](https://github.com/City-of-Helsinki/decidim-helsinki/files/2723506/Suunnitelmalomake1.0.pptx)
[Käyttäjätarinat-seuraavavaihe1 yhteiskehittäminen.pptx](https://github.com/City-of-Helsinki/decidim-helsinki/files/2723509/Kayttajatarinat-seuraavavaihe1.yhteiskehittaminen.pptx)

**Comment by katjahenttonen** [comment]
Tänään keskustelussa nousi esiin tarve saada lomakkeelle kenttiä, jotka olisivat vain kaupungin työntekijöiden muokattavissa. Näitä kenttiä tarvitaan aikaisintaan kustannusarviointivaiheessa, joka käynnistynee noin 1.4.  Meidän pitäisi varmaan vielä keskustella siitä miten tämä olisi toteuttavissa Mutta jos siis 18.11. mennessä saamme nuo kaupunkilaisille tarkoitetut toiminnot kuntoon niin se on tässä vaiheessa kiireellisintä.

**Comment by katjahenttonen** [comment]
En tiedä missä vaiheessa teillä on tämä kehitys nyt menossa, mutta eilen tuli vielä yksi lisätoive.  Haluttaisiin lisäkenttä,joka olisi rastiruutuun tyylinen "Ehdotukseksellani ei ole sijaintia".   Muuutoin sijainti olisi pakollinen, mutta jos tämä on ruksattuna niin sitten sen voisi jättää tyhjäksi.  Saman voisi ottaa käyttöön myöhemmin ehdotuslomakkeella.  Mun puolesta kävis se alkuperäinen "Ehdotuksella on osoite" mutta tällöin siinä kohdassa pitäisi olla ruksi valmiina.  Mielestämme käänteinen "Ehdotuksella ei ole osoitetta" olisi hieman käytetävämpi,  koska haluamme useimpien syöttävän osoitteen.

**Comment by ahukkanen** [comment]
Yhteistyöstämiskomponentin tämänhetkinen versio on nyt testattavana ja demottavana Ninja-ympäristössä:
https://osallistu.hel.ninja/processes/katjantesti/f/63/

Tiedämme, että siinä on vielä puutteita, niitä työstetään tällä hetkellä. Kehys on kuitenkin kasassa ja tällä hetkellä toimii ainakin:

- Komponentin itsensä lisäys
- Kysymyksien lisäys ja muokkaus
- Suunnitelmien lisääminen, listaus ja katselu

**Comment by katjahenttonen** [comment]
Kiitokset! Tosi hienoa, että osiot ja niiden lukumäärä ovat joustavasti määriteltävissä hallintapaneelista.  Jos tuohon saisi vielä osiokohtaisen maksimimerkkimäärän? Sellainen huomio, että suunnitelmaluonnoksia on tarkoitus syöttää vain yhdellä kiellellä (samoin kun ehdotuksiakin) eli loppukäyttäjän käyttöliittymästä voisi poistaa monikielisyyden.  Muutoin en nyt enempää kommentoi, kun ymmärrän toki että se on vielä kesken.  Mut hyvältä näyttää tähän asti.

**Comment by ahukkanen** [comment]
@katjahenttonen Tuosta pitää varmaan keskustella vielä, että miten suunnitelma on tarkoitus muuttaa sitten budjetointiprojektiksi, jossa monikielisyys teksteille on pakollinen.

Toinen asia, joka on hieman vielä avoinna, on tuo paikkatiedon liittäminen, koska lopullisiin budjetointiprojekteihin paikkatietoa ei voi liittää, koska se on ehdotuksilla. Toisaalta, jos suunnitelmiin halutaan paikkatieto mukaan, niin onko kyseessä yksi paikka vai useampi paikka, kun siihen voi jo liittää useampia ehdotuksia. Vai voisiko paikkatieto tulla oletusarvoisesti jo ehdotuksilta.

**Comment by katjahenttonen** [comment]
Sovimme suullisesti, että monikielisyys säilytetään taustalla mutta piilotetaan ja että paikkatiedon voi jättää pois tässä vaiheessa.  Nämä onkin jo toteutettu, myös versionhallinta näkyy toimivan, kiitos siitä. 

Seuraavat asiat puuttuvat vielä komponetista (kiireellisyysjärjestyksessä):

 1. suunnitelmien merkitseminen valmiiksi pääkäyttäjän toimesta (tämän jälkeen suunnitelmia ei voi enää muokata,  ”valmiiksi merkitseminen” on voitava tehdä yhdelle suunnitelmalle kerrallaan ja se on voitavat peruuttaa)
 2. suunnitelmien automaattinen vienti Excel-taulukkoon  (jokainen kenttä omaan Excel-sarakkeeseensa) 
3.   Valmiiden suunnitelmien vieminen äänestys-/budjetointinäkymään automaattisesti 

Tätä ei mainittu määrittelyssä, mutta käyttäjät ovat kaivanneet myös Excel-taulukkoon myös kenttää "Liittyvä ehdotukset" jossa olisi liittyvien ehdotusten id:t.  Sama tarve voitaneen tosin ratkaista jollain muullakin tapaa.

Avaan uuden tiketin Ideapaahtimoon liittyvistä muutoksista.

**Comment by katjahenttonen** [comment]
Lisäksi seuraavat korjaukset vielä tarvitaan komponenttiin:

- [ ]  suunnitelmille ei pidä liittää hylättyjä ehdotuksia (odotan vielä naapuritiimin vastausta siihen, mitä tehdään arvioinnissa oleville ehdotuksille, eli saako niittä liittää vai ei)

- [ ]  suunnitelmille ei saisi liittää "olemattomia" ehdotuksia - nyt ehdotuksen nimeksi voi kirjoittaa mitä tahansa, esim. "kissa" ja jos tämän nimistä ehdotusta ei löydy niin lomakkeella lisätään "tyhjä täppä".

**Comment by ahukkanen** [comment]
Komponenttia on nyt päivitetty ja uusina ominaisuuksina valmiiksi merkitseminen, suunnitelmien vienti Excel-taulukkoon sekä suunnitelmien vienti käyttäjän omien tietojen lataukseen.

**Comment by ahukkanen** [comment]
Toinen päivitys ajettu sisään, missä uutena ominaisuutena suunnitelmien vienti budjetointiprojekteiksi.

En tiedä, mitä yllä tarkoitit "automaattisesti", mutta tämä toimii siis hyvin vastaavasti kuin ehdotusten vienti projekteiksi.

Tämä toimii seuraavasti:

- Hallintapaneelin suunnitelmat-näkymästä painetaan "Vie projekteiksi".
- Lomakkeelle valitaan, mihin komponenttiin (samassa tilassa) suunnitelmat luodaan.
- Lomakkeelle annetaan ns. "oletusbudjetti", joka määrittelee projekteille syötettävän "hintalapun" (voi muokata projekteille myöhemmin).
- Luonnin jälkeen suunnitelmat ilmestyvät komponenttiin.

Vienti vie ainoastaan "valmiit" suunnitelmat, eli ne tulee merkitä valmiiksi ennen vientiä. Jos suunnitelma on jo aikaisemmin viety projektiksi, sitä ei viedä enää uudestaan (ellei alunperin vietyä suunnitelmaa ensin poisteta).

**Comment by katjahenttonen** [comment]
Kiitos näistä! Selainen juttu on vielä oli tuossa alkuperäsessä määrittelyssä mainittu, että käyttäjälle pitäisi lähteä automaatinen notifikaatio kun joku liittää hänen suunnitelmansa ehdotukseen. Tämä vissiin jäi tekemättä - en ainakaan nopeassa omassa testissa saanut toimimaan?

**Comment by ahukkanen** [comment]
Notifikaatio on lisätty nyt ehdotusten kirjoittajille siinä kohtaa, kun uusi suunnitelma julkaistaan.

**Comment by katjahenttonen** [comment]
Ok, kiitokset! Tämä siis valmis.

**Comment by katjahenttonen** [comment]
ai niin @ahukkanen  notifikaation teksti on nyt varmaankin jälkikäteen lisätty YML-tiedostoon? Tarvitsetko tsekata käännökset tms?  :)

**Comment by katjahenttonen** [comment]
Päätin että suljetaan nyt tämä vaan.  En saanut kyseisiä viestejä ikinä asianosaisilta,  joten mennään sillä mitä kirjoitit.
