### ISSUE TITLE
Pieni bugi merkkilaskurissa

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#44]
Seuraava käyttäjäpalaute  tuli äsken: "En pysty jättämään ehdotusta. Systeemi herjaa, että se on liian pitkä. Samalla kuitenkin lukee, että merkkejä on jäljellä 2. Testasin siirtämällä wordiin ja siellä merkkimäärä välilyönteineen on 991. Raja on 1000. Miten saisin ehdotuksen syötettyä järjestelmään?"

Sain toistettua ongelman: varsinaisen validaattorin mielestä teksti on liian pitkä silloin kun käyttäjälle näkyvä merkkilaskuri näyttää että vielä muutama merkki olisi jäljellä. Eli merkkilaskuri (se joka näyttää ”X merkkiä jäljellä) toimii hieman eri periaateella kuin varsinainen ohjelmisto.

**Comment by ahukkanen** [comment]
Tämä on ihan tekninen juttu Wordin merkkimäärälaskurissa, olen huomannut saman. Word tai OpenOffice Writer kumpikaan ei laske kaiketi rivinvaihtoja merkeiksi.

Decidim kuitenkin laskee ne merkeiksi myös taustalla, jolloin ne on otettava merkkimäärälaskurissa huomioon, koska muuten taustatoiminnallisuus herjaisi validaatioerroria.

Eli kyse on kaiketi siitä, mikä tulkitaan merkiksi ja mikä ei. Teknisesti myös rivinvaihto on merkki.

**Comment by ahukkanen** [comment]
Mitä tehdään tämän kanssa?

Tuo voi olla hieman vaikeasti teknisesti tulkittava, jos rivinvaihtoja ei lasketa merkkimäärään. Toki mahdollista, mutta onko tämä niin iso asia, että tähän kannattaa laittaa tunteja kiinni?

**Comment by katjahenttonen** [comment]
Toki Decidimin merkkilaskuri voi ihan hyvin toimia eri tavoin Wordin tai Open Officen kanssa, ei se haittaa. Mut siis ongelmana on se, että Omastadi front-end ja Decidim back-end laskee merkit eri tavoin.  Eli tuo teidän front-endiin tekemä merkkilaskuri sanoo että vielä "2 merkkiä on jäljellä", mutta kun käyttäjä painaa "Jatka" niin hän saa validaattorilta virheilmoituksen että "ehdotus on liian pitkä".  Ja tässä vaiheessa käyttäjät sitten tulevat meille lankoja pitkin että miksi en saa tätä jätettyä mun ehdotuksile.  Suunnitelmiin tarvitaan myös merkkilaskurit joten sitäkin silmällä pitäen tämä olisi hyvä korjata. MTK:n suhteen myös pelkään, että tästä voi tulla paljon palautetta. Yllättävän moni ihminen näemmä optimoi tekstinsä tosi lähelle maksimimerkkimäärää, tässä tapauksessa 995-1000 merkkiä.

**Comment by ahukkanen** [comment]
Sittenhän tämä on ongelma, en vain ymmärtänyt tätä oikein.

Tutkin vielä tuota frontin ja bäkin eroa merkkien määrän tulkitsemisessa.

**Comment by katjahenttonen** [comment]
Tämä on @ahukkanen  ilmeisesti korjattu? En ainakaan enää saaa toistettua ongelmaa?

**Comment by ahukkanen** [comment]
@katjahenttonen Tälle ei ole löytynyt ratkaisua.

Esimerkkisyötteet ongelmallisista teksteistä helpottaisivat tämän bugin toistamista. Hyvin luultavasti nämä on kopioituja tekstejä Microsoft Word -ohjelmasta.

**Comment by katjahenttonen** [comment]
Joskus aikaanaan syksyllä kun tämä oli ajankohtainen ja testailin asiaa niin ongelman sai kyllä toitettettua ihan millä tahansa oikeanpituisella merkkijonolla.  Koitin hyvinkin erilaisilla syötteillä ja kaikilla sain virheen, sen takia en ottanut kyseisiä syötteitä mihinkään ylös.   Nyt virhe ei ole enää toistettavissa, joten onkohan versiopäivityksen vaikuttaneet? Joka tapauksessa suljen toistaiseksi.

**Comment by ahukkanen** [comment]
@katjahenttonen Ei käsittääkseni mikään ole muuttunut tämän toiminnallisuuden osalta. Fronttikoodi (käli) tarkastaa syötteen pituuden JavaScriptin merkkijonon `.length` -arvosta. Taustatoiminnallisuus tarkastaa syötteen pituuden Rubyn merkkijonon `.length` -arvosta.

Käytännössä en keksi muita tilanteita, milloin nämä kaksi voivat erota kuin:
a) eroavaisuudet syötteen pituuden tulkinnassa näiden kielien välillä
ja
b) syötteen muuttuminen "matkalla" palvelimelle (eli siis esim. form datan parsinnan yhteydessä sivuutettaisiin jotain erikoismerkkejä)

Sen takia epäilin Wordia syyksi, koska monesti Word syöttää erikoismerkkejä ikään kuin automaattisesti osaksi tekstiä, mitä jompi kumpi näistä ei välttämättä tunnista.

Fronttitoiminto:
https://github.com/City-of-Helsinki/decidim-helsinki/blob/ed65054affbd9b91c7f8464e84f616484ab5abc3/app/assets/javascripts/app/remaining-characters.js#L19

Taustatoiminto:
https://github.com/decidim/decidim/blob/6c1244186aef9d0336d0c077ffc1715f03b066f0/decidim-proposals/app/forms/decidim/proposals/proposal_wizard_create_step_form.rb#L32
