### ISSUE TITLE
Kommenttia ei voi jättää tietyissä tilanteissa (tietyt merkkijonot, erikoismerkit)

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#45]
Olen saanut ehdotusvaiheen avaamisen jälkeen viestejä siitä, että kommentointi käyttäytyy arvaamattomasti. Jos kommenttiin sisältyy joku väärälainen merkkiyhdistelmä (esim. "SOTE:lle") kommentti vain häviää tuhkana tuuleen kun painaa "Lähetä".  Näytöllä välähtää joku keltainen ilmoitusviesti, mutta sitä ei ehdi lukea.  Merkkien logiikkaa on vaikea tajuta, esim. "SOTE:lle" tai "XXXX:xxx" aiheuttaa virheen, mutta "SOTE:ll" tai XXXX:xx ei aiheuta. Mistä mahtaa johtua?

**Comment by ahukkanen** [comment]
Tämä on Decidim-bugi, joka on korjattu jo coreen: https://github.com/decidim/decidim/issues/4157

Käsittääkseni siinä uusimmassa päivityksessä tulossa korjaus tähän.

Liittyy: #42

**Comment by katjahenttonen** [comment]
Testasin ninjan puolella ja tämä näyttäisi olevan kunnossa.
