### ISSUE TITLE
Ehdotusten satunnaistaminen

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#49]
Kun käyttäjä menee tarkastelemaan yksittäisiä ehdotuksia ja painaa "Takaisin ehdotuksiin" niin ehdotukset uudestaan satunnaistetaan.  Tämä on häiritsevää koska käyttäjä hukkaa sen kohdan missä oli listalla.  Laitan tämän nyt muistaessa koska unohdin aiemmin, asiasta on tullut paljon palautetta.

**Comment by ahukkanen** [comment]
Tässä on kyseessä Decidimin bugi, jonka olen ilmoittanut Metadecidimiin:
https://meta.decidim.org/processes/bug-report/f/210/proposals/14295

Tämä on korjattu Helsingin instansseihin toivon mukaan väliaikaisella korjauksella ehdotukset- ja suunnitelmat-moduuleihin.
