### ISSUE TITLE
Prosessiryhmät etusivulle

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#5]
Voisimmeko saada prosessiryhmät etusivuille kuten vanhassa KUVA:n teettämässä versiossa?   Tämä on meille välttämätön omaisuus nyt kun alustalle halutaan melko pikaisesti muutakin kuin osallistuva budjetointi. Pidemmän päälle asian pitäisi mielestäni olla konfiguroitavissa  käyttöliittämästä.

**Comment by ahukkanen** [comment]
Tämä onnistunee helpoiten tuossa viimeisimmässä versiossa, joka julkaistiin viime viikolla. Siihen lisättiin feature nimeltä "Content blocks", jonka avulla noita kotisivun palikoita voi itse määritellä ilman, että koko näkymätiedostoa tarvitsee kustomoida.

Varmaan kannattaa päivittää kohtapuolin tuo core viimeisimpään.

Laitan tähän vielä itselleni ylös esimerkin näiden blokkien konfiguroinnista:
https://github.com/decidim/decidim/blob/e06bef740022aa97e5d50faf8847130dee12445c/decidim-core/lib/decidim/core/engine.rb#L297-L300

**Comment by katjahenttonen** [comment]
Ok, hyvä juttu että tämä onnistuu suht helposti.

**Comment by katjahenttonen** [comment]
Muutos @ahukkanen  tätä ei tarvitsekaan tehdä! Aimmista tiedoista poiketen OmaStadi-instassi halutaan toistaiseksi pitää vain osallistuvan budjetoinnin käytössä joten muutosta ei tarvitse tehdä.  Eli etusivulla näytetään prosessit samoin kuin myös Ideapaahtimossa. Myöhemmin muutos voi olla tarpeen ja on hyvä että kävimme tästä keskustelun.  Suljen kuitenkin tiketin toistaiseksi.
