### ISSUE TITLE
Yhteiskehittämisen komponentti V2

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#50]
Ideapaahtimon tarpeisiin muutetaan yhteiskehittämisen komponenttia siten, että:

- [x]  kohteen nimi on muutettavissa hallintakäyttöliittymästä, esim. parametri "lomakkeen nimi"  - haluttu sana on voitava antaa yksikössä (esim. "idea", "suunnitelma"), monikossa ("esim. "ideat", "suunnitelmat") sekä ehkä lukusanan jälkeisessä sijassa ("n ideaa, n suunnitelmaa" jos tarpeen) 

- [x]  Kohteen linkittäminen ehdotuksiin voidaan laittaa asetuksissa päälle tai pois tarpeen mukaan.

- [x]  Teemat ja kategoriat (alavalikot) voidaan laittaa päälle tai pois tarpeen mukaan.

Samalla komponetin nimen voisi muuttaa geneeriseksi, esimerkiksi "yhteistyölomakkeet",  "collaborative forms". Aikaisemmasta tiedosta poiketen Suosittele-toimintoa EI tarvita.

**Comment by ahukkanen** [comment]
Uudet konfigurointiasetukset on nyt lisätty komponenttiin ja ovat käytettävissä kaikissa ympäristöissä.

Termikustomointeja varten on tulossa kokonaan erillinen moduuli, mistä mainitsinkin, eli näistä ei tule ominaisuutta suunnitelmat-komponenttiin.

**Comment by ahukkanen** [comment]
Termikustomointikomponentti on otettu nyt käyttöön kaikkiin instansseihin.

Ideapaahtimoa koskevat termikustomoinnit (Suunnitelma -> Idea) on tehty Ideapaahtimoon.

**Comment by katjahenttonen** [comment]
Tämä ok, suljetaan.  Voisimme jossain vaiheessa katsoa miten tuo kustmointimoduli ja niihin liittyvät "käännöspaketit" toimivat, pelkästä käyttöliittymästä ei pääse jyvälle.

**Comment by ahukkanen** [comment]
Katsotaan vain läpi, kun sinulle sopii.

Ideapaahtimon tapauksessa niistä "käännöspaketeista" tai niiden "rajaussäännöistä" sinänsä ei tarvitse ollenkaan välittää. Ideapaahtimossa termikustomoinnit koskevat koko instanssia, joten ne voi jättää täysin tyhjäksi. Käännöspaketti tarvitaan vain sitä varten, että on jokin paikka, mihin niitä kustomointeja lisätään.

Muissa instansseissa nuo "käännöspaketit" auttavat siinä, että termikustomoinnit voi rajata vain tiettyyn osaan palvelusta. Jos esim. halutaan, että termikustomoinnit koskevat kaikkia "Osallisuusprosesseja", niin silloin käännöspaketti rajataan "Osallisuusprosessit" -tiloille (vastaavasti voi rajata myös "Ryhmät" -tiloille). Jos taas halutaan, että termikustomoinnit koskevat ainoastaan esim. "Eteläinen Helsinki" -prosessia (ja eivät mitään muuta osaa järjestelmässä), niin silloin ne rajataan "Osallisuusprosessit" -tilaan ja tämän alta valitaan "Eteläinen Helsinki".

Tämän lisäksi käännöspaketit voi rajata myös ainoastaan tiettyyn komponenttiin, eli esimerkiksi "Eteläinen Helsinki" -tilassa voisi olla kaksi Suunnitelmat-komponenttia, joista toisessa käytettäisiin termiä "Suunnitelmat" ja toisessa termiä "Ideat". Tällöin käännöspaketti rajattaisiin tiettyyn komponenttiin esim. "Eteläinen Helsinki" -prosessin sisällä.

En tiedä avaako tämä yhtään, mutta ideana on se, että nuo käännöspaketit auttavat termikustomointien rajaamisessa eri kontekstien sisällä samassa järjestelmässä. Kuten mainittu, Ideapaahtimossa tämä ei sinänsä ole olennaista, koska siinä kustomoinnit koskevat koko instanssia.
