### ISSUE TITLE
Suunnitelmakomponetille sisäiset "tägit"

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#51]
Kun ideoiden arvointi alkaa Ideapaahtimossa, tarvitaan seuraavat:

- [x] vastausten kustomointi siten, että kaikki vastauksen tekstit olisivat konfiguroitavissa
käyttöliittymässä.  Eli olisi vain kolme vastaustyyppiä "kielteinen", "myönteinen" ja "neutraali" sekä näihin vastaustyyppeihin liittyvät sanat voisi valita käyttöliittymästä (esim. mahdollinen/ei-mahdollinen/arvioitana tai "Hyväksytty, hylätty, arviotavana" jne).  Lisäksi vastaukseen liitettävä vakioteksti "Ehdotuksesi ei edennyt jatkoon" jne pitäisi olla kustomoitavissa.

- [x]  hallintapaneelista ylläpitäjän toimesta asetetettavat "tägit" (pudotusvalikko) joita ei kysytä lomakkeella loppukäyttäjältä. Tägien pitää kuitenkin näkyä käyttäjälle ja mielelellään olla hakuehtona

**Comment by ahukkanen** [comment]
Vastauksia voi kustomoida nyt uudella termikustomointikomponentilla.

**Comment by ahukkanen** [comment]
Sisäiset tägit löytyvät nyt komponentin hallintapaneelinäkymästä Tägi-ikonin alta suunnitelmalistauksessa. Saatavilla olevia tägejä hallitaan "Hallitse merkintöjä" -alanäkymästä ja siitä ensimmäisestä näkymästä näitä jo luotuja tägejä voi etsiä ja määritellä suunnitelmille.

Tägit näkyvät hallintapaneelin listauksessa ja myös käyttäjille suunnitelman sisällön alapuolella siinä, missä näkyy myös kategoria tai teema. Näiden mukaan voi myös filtteröidä listausnäkymässä.
