### ISSUE TITLE
Suunnitelmille ei saa liittää ehdotuksia jotka on hylätty

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#52]
Yhteiskehittämisen komponetissa suunnitelmille ei saa liittää ehdotuksia, jotka on hylätty -  suunnitelmille voidaan liittää hyväksyttyjä ehdotuksia sekä ehdotuksia, joita ei ole arvioitu

**Comment by ahukkanen** [comment]
Tämä muutos on nyt toteutettu.

**Comment by katjahenttonen** [comment]
Kiitos!
