### ISSUE TITLE
Suuunitelmille ei saa liittää "tyhjiä" ehdotuksia

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#53]
Suunnitelmille ei pitäisi voida lisätä "olemattomia" ehdotuksia - jos nyt kirjoittaa ehdotuksen nimeksi "kissa" eikä tälläistä ehdotusta ole niin ohjelma lisää "tyhjän täpän" suunnitelmalle.  Tämän sijasta ei pitäisi lisätä mitään jos yhtään liitettävää ehdotusta ei ole löytynyt hakusanalla.

**Comment by ahukkanen** [comment]
Tämä on core-bugi, jolle olen tehnyt pull requestin (hyväksyttiin eilen):
https://github.com/decidim/decidim/pull/4842

Varsinainen korjaus siis tulossa seuraavaan Decidim-versioon.

Tälle on lisätty myös väliaikainen korjaus suunnitelmamoduuliin.
