### ISSUE TITLE
Tapahtumakutsujen lähettäminen ei toimi

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#54]
Tapahtumakutsujen lähettäminen ei toimi. Jos henkilö ei ole valmiiksi kirjautuneena Omastadi-alustalle (kuten kukaan ei yleensä ole) ja seuraa sähköpostikutsun linkkiä ”Ilmoittaudu tapahtumaan”  hän saa virheilmoitukset ”Tiliäsi ei ole varmennettu tämän toiminnon suorittamiseen” (punainen palkki sivun yläreunassa, heti vihreän Omastadi-palkin alapuolella).

**Comment by ahukkanen** [comment]
Tämä on korjattu ninjaan ja tuotantoon.

Lisäksi coreen tehty pull request: https://github.com/decidim/decidim/pull/4839

**Comment by katjahenttonen** [comment]
Hienoa, kiitos!
