### ISSUE TITLE
Vastaamattomien ehdotusten linkittäminen ei toimi

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#55]
Jostain syystä komponenttipäivityksen yhteydessä ehdotuksiin linkkaaminen on muuttunut siten, että vain hyväksyttyjä ehdotuksia voi linkittää.
Tarve olisi linkittää myös sellaisia ehdotuksia joihin ei ole vastattu vielä.

**Comment by ahukkanen** [comment]
Tämä on korjattu suunnitelmat-komponenttiin.

**Comment by katjahenttonen** [comment]
Kiitos!
