### ISSUE TITLE
Sivua ei löydy -suunnitelmakomponetissa virheen jälkeen

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#56]
Jos suunnitelmat komponetissa tulee lomaketta tallentaessa joku virhe (esim. siksi että osion runkoteksti on tyhjä) niin tämän jälkeen käyttäjä aina menettää kaikki tallentamattamat osiot.  Vaikka virheen korjaa niin seuraava tallennus päättyy virheeseen "Sivua ei löydy" ja kaikki tallentamaton menetetään. 

Ei ole kiireellisemmästä päästä, mutta pitää hoitaa pois.  Moni ihminen näemmä painaa "Lisää osio" juuri ennen tallennusta jolloin tämä virhe tulee esiin ja tiedot menetetään.

**Comment by ahukkanen** [comment]
Siis tämä kaiketi koskee admin-käyttöliittymää, missä hallitaan suunnitelmat-komponentin osioita?

**Comment by ahukkanen** [comment]
Näyttäisi koskevan myös suunnitelman liitteitä ja kaikkia muita "dynaamisesti" lisättäviä osioita decidimissä (mm. tapahtumien agendalistat, lomake- ja kyselykomponenttien kysymysosiot).

Tämä bugi koskee vain tilannetta, jossa osioita tai liitteitä on jo olemassa tietokannassa ennaltaan ja tämän jälkeen käyttäjä muokkaa niitä ja lisää uuden.

Suunnitelmille saa toistettua seuraavasti:

- Lisää uusi suunnitelma.
- Lisää suunnitelmalle yksi liite (liitä tiedosto ja määritä otsikko).
- Siirry eteenpäin julkaisunäkymään niin, että suunnitelman luonnos tallentuu ja pääset esikatselunäkymään.
- Siirry takaisin muokkausnäkymään esikatselusta.
- Lisää toinen liite lomakkeelle. Määritä uudelle liitteelle otsikko, mutta jätä tiedosto liittämättä.
- Klikkaa "Päivitä".
- (lomakkeella pitäisi nyt näkyä virhe, että liite puuttui)
- Lähetä lomake uudestaan tekemättä mitään muutoksia.

Vastaavasti osionäkymille bugin saa toistettua osioiden hallintanäkymässä vastaavasti (lisää ensin osioita, mene uudestaan muokkausnäkymään, lisää uusi osio ja tallenna kaksi kertaa virheellisenä).

Tekniset tiedot:

Tämä johtuu siitä, että tyhjille uusille osioille ei lisätä lomakekenttiin ns. teknistä positionumeroa, koska niillä ei sellaista vielä ole olemassa. JavaScript-komponentti kuitenkin lisää käyttöliittymästä käsin tämän numeron, mutta palvelimen päässä renderöitäessä tyhjä kenttä, sitä ei lisätä.

Esimerkki uuden tyhjän lomakekentän nimestä kun se on lisätty JS-komponentilla käyttöliittymässä:
`lomakekentta[12312315666][alakentta]`

Esimerkki samasta lomakekentästä, kun se renderödään palvelimen päässä ilman, että sitä on vielä tallennettu tietokantaan:
`lomakekentta[][alakentta]`

Bugi liittynee Decidimin coren omaan dynaamisten kenttien hallintalogiikkaan. Tyhjät kentät pitäisi joko "alustaa" käyttöliittymässä, kun näkymä ladataan tai sitten palvelinpäässä niille pitäisi generoida jokin ID-numero lomakekenttien nimiin.

**Comment by katjahenttonen** [comment]
Kiitos perusteellisesta selvityksestä.  Tarkoitin nimenomaan osioiden lisäämistä hallintaapaneelista tässä kohtaa. Mutta lisättäessa liitteitä suunnitelmaan on tullut  kyllä sama virhe  parilla käyttäjällä testitilanteessa.  Myös ehdotusvaiheessa tulleista virheraporteista jokunen selittynee tällä samalla.  Mitä tälle voisi tehdä? Ainakin ehdottaa tuonne kv-kehittäjille  mainitsemiasi ratkaisuja?

**Comment by ahukkanen** [comment]
Keksin jo tälle ratkaisun ja korjasin komponenttiin. Korjaus tulee seuraavassa päivityksessä.

Tämä pitää korjata kaikille lomakkeille erikseen ja tein coreen myös pull requestin samaan bugiin liittyviin ominaisuuksiin: https://github.com/decidim/decidim/pull/4896

**Comment by ahukkanen** [comment]
Korjaus suunnitelmat-komponenttiin on viety liveksi. Core-komponentteihin muutos tullee seuraavassa core-päivityksessä.
