### ISSUE TITLE
"Ehdotusten liittäminen käytössä" ja "Kategoriat käytössä" ei toimi

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#57]
Huomasin myös että "Ehdotusten liittäminen käytössä" ja "Kategoriat käytössä" ruksit eivät vielä vaikuta mitenkään suunnitelma komponentin toimintaan.

**Comment by ahukkanen** [comment]
Tämä on korjattu. Johtui Helsingin instanssiin tehdyistä näkymäkustomoinneista, jotka eivät ottaneet uusia asetuksia huomioon.

**Comment by katjahenttonen** [comment]
Testattu,toimii. Kiitos!
