### ISSUE TITLE
Ideapaahtimoon vain Tunnistamon/AD:n kautta

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#58]
Ideapaahtimoon pääsi joskus taannoin vain Tunnistamon ja Kaupungin AD:n kautta, mutta  jonkun päivityksen yhteydessä sinne on tullut mukaan tuo vaihtoehto "Luo omat tunnukset".   Ideapaahtimoon saisi edelleenkin päästä vain Helsingin kaupungin työntekijöiden AD-tunnuksilla.

**Comment by ahukkanen** [comment]
Se "kirjaudu omalla tunnuksella" on ollut siellä alusta asti, mutta toki uuden leiskan mukaan se on nyt hieman näkyvämmin esillä.

Me esimerkiksi tarvitsemme sitä palvelun hallintakäyttöön, koska meillä ei ole kaupungin AD-tunnuksia.

**Comment by katjahenttonen** [comment]
Joo, eihän tuo tosiaan mitään haittaa kun rekisteröityminen on piillotettu eikä onnuksia tunnuksia pääse itse luomaan. Anteeksi! Olen selvästi väsynyt, pitäisi pysyä pois gitistä myöhäisellä illalla.
