### ISSUE TITLE
Uusien sivujen näkyminen alatunnisteessa

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#59]
Huomasin (oletatettavasti meidän omaan visukustomointiin?) liittyvän ongelman, että kaikki uudet sivut näkyvät alatunnistetessa vaikka EI raksittaisikaan kohtaa "näytä alatunnisteessa".  Tämä tekee mahdottomaksi käyttää uusia sivutoimintoja ohjeiden kirjoittamiseen toivomallamme tavalla.

**Comment by ahukkanen** [comment]
Kyllä, tämä liittyi visukustomointiin.

Tämä on korjattu kaikkiin instansseihin, eli ottaa nyt myös sen asetuksen (ja aiheet) huomioon footerissa.
