### ISSUE TITLE
Ruotsi mukaan kielivalikoimaan suomen ja englannin rinnalle

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#6]
Ruotsi pitäisi lisätä MunStadi (ex. osallistu.hel.fi ) alustan kielivalikoimaan.  Käännökset eivät ole valmiit, joten asialla ei ole kiire. Laitan tänne etten unohda.

**Comment by katjahenttonen** [comment]
@ahukkanen  voisitteko laittaa ruotsinkielen OmaStadiin pikaisesti päälle samoin kuin keskustelu.hel.fi alustalle. Tälläinen pyyntö tuli meidän kehityspäälliköltä aiemmasta poiketen.  Ilmeisesti het nyt tuottavat heti alkuviikosta jonkin verran ruotsinkielistä tekstiä.

**Comment by katjahenttonen** [comment]
Tässä vielä ruotsinnosta varten lauseet kirjautumiseen liittyen:

Kirjaudu Tunnistamo-palvelun avulla
Logga in med hjälp av tjänsten Tunnistamo

Kirjaudu omalla tunnuksella
Logga in med eget konto

Luo omat tunnukset 
Skapa eget konto

Tunnistamon avulla voit kirjautua palveluun mm. Google-, Facebook- tai YLE-palveluiden avulla.
Med hjälp av Tunnistamo kan du logga in i tjänsten bl.a. med tjänsterna Google, Facebook eller YLE.

Kirjaudu sisään sähköpostisoittella ja itse valitsemallasi salasanalla.
Logga in med e-postadress och ett lösenord som du själv väljer.

Luo oma käyttäjätili ja kirjaudu jatkossa sisään sähköpostisoittella ja itse valitsemallasi salasanalla
Skapa ett användarkonto och logga i fortsättningen in med e-postadress och ett lösenord som du själv väljer

**Comment by ahukkanen** [comment]
Ruotsi on nyt laitettu päälle ninjassa ja tuotannossa.

Nämä termipäivitykset tulevat seuraavassa päivityksessä.
