### ISSUE TITLE
Ideapaahtimon värien ja somekuvan päivitys

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#61]
Ideapaahtimon värejä on pyydetty päivittämään seuraavasti: yläbanneriin "sumu" RGB 159, 201, 235 ja alabanneriin "kesä" RGB 255, 212, 0. Lisäksi somejakokuvaksi pitäisi päivittää oheinen logo.
![ideapaahtimo-tunnus-ehdotus2](https://user-images.githubusercontent.com/39044068/53565342-e288e680-3b61-11e9-8fce-15c181d529fd.png)

**Comment by katjahenttonen** [comment]
Ideapaahtimon värejä on pyydetty päivittämään seuraavasti: yläbanneriin "sumu" RGB 159, 201, 235 ja alabanneriin "kesä" RGB 255, 212, 0.  Lisäksi somejakokuvaksi pitäisi päivittää oheinen logo.
![ideapaahtimo-tunnus-ehdotus2](https://user-images.githubusercontent.com/39044068/53565287-b8cfbf80-3b61-11e9-8d54-ecadb432db09.png)

**Comment by katjahenttonen** [comment]
Alasivuilla olevan yläbannerin ulkoasua pitää myös muokata (nythän tuo valkoinen vaihe-laatikko on aika tylyn näköinen) mutta avaan tästä uuden tiketin kun saan lisätietoa.

**Comment by katjahenttonen** [comment]
Tässä yhteydessä myös alabannerissa olevan palautesähköpostin osoitteen voisi vaihtaa omastadi.hel.fi --> ideapaahtimo@hel.fi.

**Comment by ahukkanen** [comment]
Värimuutokset ja somekuvan muutos on toteutettu ideapaahtimoon.

**Comment by ahukkanen** [comment]
Palautesähköposti on nyt myös vaihdettu ideapaahtimoon.
