### ISSUE TITLE
Ideapaahtimossa alasivujen bannerit samanlaiseksi kuin omastadissa

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#62]
Ideapaahtimossa alasivujen bannerit pitäisi saada samannäköiseksi kuin osbussa.  Eli kaikki tekstit mustalla, vaihelaatikko läpinäkyväksi, mustat reunaviivat jne.  Bannerikuvaa ei ole vielä valittu, mutta haluavat käyttää vaalesävyistä kuvaa, johon sopivat mustat tekstit nykyisiä vaaleita paremmin.  Vaihelaatikosta voisi samalla poistaa (sekä Ideapaahtimossa että Omastadissa) ne yläreunanan siniset pallurat (ne eivät ole kovin informatiiviset) mikäli tämä ei suuri työ tai aiheuta jatkossa ongelmia.

**Comment by ahukkanen** [comment]
Nämä on toteutettu ideapaahtimoon.
