### ISSUE TITLE
Ei pysty valitsemaan suunitelmalle ehdotusta, jonka nimessä lainausmerkit

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#63]
Omastadissa asiakas ei pysty luomaan suunnitelmaa ehdotukselle jossa on lainausmerkit.  Siis tässä tämä ehdotus: https://omastadi.hel.fi/processes/omastadi-lantinen/f/24/proposals/433

Ehdotus näkyy haettaessa pudotusvalikossa, mutta sitä ei pysty valitsemaan eikä suunnitelmaa saa luotua. Oletan että ongelma johtuu lainausmerkeistä.  Mitä tämän saisi fiksattua?

**Comment by ahukkanen** [comment]
Tämä bugi on korjattu suunnitelmat-komponentin päivityksessä.

**Comment by katjahenttonen** [comment]
Voisitko @ahukkanen tehdä tästä hotfixin tuotantoon? Suunnitelmien avaaminen suljetaan virallisesti huomenna 8.3. (käytännössä maanantainaamuna 11.3.) ja kaikkien ihmisten pitäisi saada avattua  suunnitelmana sitä ennen.  Tietokannassa on muutamia noita launausmerkkillisiä ehdotuksia ja heillä on hätä kun eivät saa avattu suunnitelmaa.  Kiitos.

**Comment by ahukkanen** [comment]
@katjahenttonen Pitäisi olla korjattu myös tuotantoon. Minkä nimiselle ehdotukselle se ei toimi? Kokeilin ainakin lokaalisti ehdotusta, jonka nimeen lisäsin lainausmerkkejä ja sen pystyi valitsemaan.

**Comment by ahukkanen** [comment]
Kokeilin myös tuotannossa ja pystyin valitsemaan kyseisenlaisen ehdotuksen Läntisessä Helsingissä.

**Comment by katjahenttonen** [comment]
Anteeksi väärinkäsitys, kaikki kunnossa!
