### ISSUE TITLE
"Decidim organization ei löydy" rekisteröitymisen/kirjautumisen yhteydessä

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#64]
Käyttäjilltä on aina silloin tällöin tullut viestiä virheilmoituksesta "Decidim organization ei löydy"  rekisteröitymisen (tai kirjautumisen?) yhteydessä. Kyseessä ei ole yhteisökäyttäjä.  Näitä on tullut jokunen aiemminkin, aina ongelma on saatu digineuvonnan avulla ratkaistua, mutta virhelmoitus on ilmeisen harhaanjohtava. Pääsisetkö kiinni mistä tämä johtuu ja voisiko virheilmoituksesta muokata ymmärrettävämmän? Laitoin spostiin käyttäjän tiedot, jolla on tämä ongelma.

"2 virhettä esti ei käyttäjiä tallentamisen:
Decidim organization ei löydy
Sähköposti ei löydy
Sähköposti xxx.xxxx@zzzz.fi
Lähetä vahvistusohjeet uudelleen"

**Comment by katjahenttonen** [comment]
En ole saanut tätä taaskaan toistettua eikä käyttäjä ilmaantunut sovitusti tapaamaan stadiluotsia.  Onko teillä mitään tietoa siitä milloin kyseisen virheen ylipäänsä pitäisi aiheutua?

**Comment by ahukkanen** [comment]
Olen näköjään etsinyt ongelmaa aikaisemmin väärästä paikasta ja nyt tuoreemmilla silmillä sain tästä kiinni.

Tämä ei liity rekisteröitymiseen tai kirjautumiseen, vaan vahvistusohjeiden tilaamiseen siitä "Etkö saanut vahvistusohjeita?" -linkistä. Tämä virheilmoitus tulee siis silloin, kun käyttäjä yrittää tilata ohjeita sellaisella sähköpostilla, joka ei ole käyttäjänä järjestelmässä.

Tuo ensimmäinen termi on ns. yleiskäännös, jota on hieman hankala kustomoida sellaisenaan. Ehkä kannattaisi esittää Decidimin coreen suoraan, että tuohon vaihdettaisiin tilalle spesifimpi käännös.

**Comment by katjahenttonen** [comment]
Kiitos! Huomasinkin että olit avannut tiketin liittyen Metadecidmiin: https://meta.decidim.org/processes/bug-report/f/210/proposals/14302

Tämä voitaneen sulkea jos termien kustomointi hankalaa meidän päässä. Pääasia että nyt tiedä mistä virhe johtuu ja millon se esiintyy, ihmiset eivät useinkaan osaa selittää mitä ovat tekemässä ja sen vuoksi vähän haastava selvitellä näitä.
