### ISSUE TITLE
Suunnitelmakomponentin ruotsinnos

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#65]
Liitteenä suunnitelmakomponentin ruotsinnos, voisiko nämä vielä viedä alustalle?

[fi_SV-uusi.zip](https://github.com/City-of-Helsinki/decidim-helsinki/files/2935300/fi_SV-uusi.zip)

**Comment by ahukkanen** [comment]
Tässä ei ole kaikkia niitä uusimpia, mutta valitsin niihin myös Crowdinin tarjoamat automaattiset käännökset, joista vaihdoin tietyt termit yhteneväksi näiden kanssa. Osassa käännöksiä oli myös jätetty suomenkielisiä sanoja (esim. "osallisuusprosessi"), jotka niin ikään muutin yhteneviksi.

Crowdiniin voi pävitellä myöhemmin, jos näitä halutaan vielä muuttaa.

**Comment by ahukkanen** [comment]
Ruotsinkieliset käännökset on viety myös kaikkiin instansseihin siinä muodossaa kuin ne nyt ovat Crowdinissa.

**Comment by katjahenttonen** [comment]
Kiitos paljon! Ja pahoittelut suomenkielisistä sanoista, en ehtinyt itse ehtinyt tarksistaa saamaani käännöstiedostoa.
