### ISSUE TITLE
Käyttäjän herätteessä toimimaton linkki

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#66]
Osallistujaksi pääsemispyynnöstä ilmoittavassa sähköpostissa (kuva 3) ympyröity linkki johtaa osoitteeseen http://www.processes.com/ideointia/f/6/plans/9 joka ei johda ideapaahtimoon, ks. kuva.

![toimimaton-linkki-herate](https://user-images.githubusercontent.com/39044068/53874438-1903ad00-400b-11e9-967d-b529343337a0.png)

**Comment by ahukkanen** [comment]
Kyseiset linkit on korjattu.
