### ISSUE TITLE
Käyttäjä ei saa avata suunnitelmaa muokattavaksi

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#67]
Tämä lienee värinymmärys eikä bugi, mutta peruskäyttäjä ei saisi milloinkaan avata suunnitelmaa muokattavaksi sen jälkeen kun se on kerran merkattu valmiiksi.  Valmiit suunnitelmat lähetetään kustannusarvioon eikä sen jälkeen teksti enää saisi missään tapauksessa muuttua.  Pääkäyttäjän on voitava halintapaneelista palauttaa suunnitelma muokattavaksi poikkeustapauksessa, jos kustannusarvioinissa huomataan suunnitelmassa joku merkittävä virhe, puute tms.  Poistaisitko peruskäyttäjän näkymästä painikkeen, josta valmis suunnitelma voidaan avata uudelleen muokattavaksi?

**Comment by ahukkanen** [comment]
Tämä on muutettu.
