### ISSUE TITLE
Tunnistamo-kirjautuminen ei saisi päivittää käyttäjäprofiilia

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#68]
Slack-keskusteluumme liittyen: jos käyttäjä päivittää nimensä tai tunnuksensa omaan profiilinsa, muutos pitäisi jäädä pysyväksi eli seuraavat Tunnistamo-kirjautumiset eivät saisi päälle kirjoittaa näitä kenttiä.

**Comment by ahukkanen** [comment]
Nimen automaattinen päivitys on otettu pois Tunnistamo-kirjautumisen logiikasta.
