### ISSUE TITLE
Ilmoitusasetukset eivät toimi IE11

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#69]
Käyttäjätilin ilmoitusasetuksissa ("Haluan saada ilmoituksia" ja "Lähetä ilmoitukset sähköpostitse) napit eivät lainkaan toimi IE11:lla (toimii yleisimmillä selaimilla, mutta tästä tulee palautetta kun kaupungilla on niin paljon IE-käyttäjiä, etenkin Ideapaahtimoa varmasti käytetään paljon IE:llä).

**Comment by ahukkanen** [comment]
Issue Decidimin repositoriossa:
https://github.com/decidim/decidim/issues/5031

**Comment by ahukkanen** [comment]
Pull request coreen: https://github.com/decidim/decidim/pull/5044
