### ISSUE TITLE
Muutoksia visuaaliseen ilmeeseen

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#7]
Viestintätoimisto suunnittelee  MunStadi (ent. osallistu.hel.) kampanjan visuaalista ilmettä ja tämä vaikuttaa jollain tavoin myös nettisivun ilmeseen, varmasti ainakin värit muuttuvat.  LIsäksi pitänee katsoa mitkä pormestarin ideapalveluun tehtävistä muutoksista ovat sellaisia, että ne kannattaa tuoda kehityksen päähaaraan mukaan.

**Muutoksia:**

Yleiset muutokset:

- [X] Yläosion muokkaus
- [X] Alaosion muokkaus
- [X] Etusivun osioiden taustaväri pois (aktiiviset prosessit/ryhmät)
- [X] Etusivun päätekstiosion fonttityylit ja väri mustaksi
- [x] Korttityylit (esim. prosessien listaus, ryhmien listaus, prosessisivut, etusivun osiot, yms.)
- [x] Etusivun "tärkeästä sisältöbannerista" overlay-väri pois ja tekstin varjostus pois.
- [x] Etusivun tilastot-osiosta poistetaan taustaväri (valkoinen elementti)
- [x] Etusivun prosessit isoina ja koko sivun levyisinä (kuten korostetut prosessit)
- [x] Etusivun ryhmät isoina ja koko sivun levyisinä (kuten korostetut ryhmät)
- [x] Etusivun lead-tekstin pitäisi skaalautua näytön koon mukaisesti
- [x] Etusivun isoissa korteissa (prosessit ja ryhmät) vain lyhyt kuvaus
- [x] Tärkeän sisältöbannerin skaalautuminen mobiilissa
- [x] Yläpalkin palvelun nimen (OmaStadi) skaalautuminen mobiilissa

OmaStadi-instanssia koskevat muutokset:

- [x] Alasivujen yläbannereissa tekstityylit mustaksi ja tekstin varjostus pois. Tekstin väritystä koskeva muutos tulee koskea vain OmaStadi-instanssia.
- [x] Prosessisivujen yläbannerin vaihelaatikon taustaväri pois ja tekstit mustaksi, eli vaiheet näkyisivät suoraan taustakuvan/värin päällä.
- [x] Etusivun "tärkeän sisältöbannerin" tekstin väri mustaksi.

**Comment by katjahenttonen** [comment]
- muutamia visuilmettä koskevia kommentteja:  uuden ehdotuksen jättämistä on vaikea löytää, asiattoman kommentin raportoimista on tosi vaikea löytää (pikkuinen lippu),  ehdotuksen jättämisen monivaiheisuus koetaan sekavana ja lisäksi liitteen otsikointi koettiin hämmentäväksi,  tilastot-kohta etusivulla koetaan outonnäköisenä jne.  Käyttäjät myös kokevat, että napppuloita on aivan liikaa ja niiden merkitystä vaikea hahmottaa.

**Comment by katjahenttonen** [comment]
Tästä on myös huomautettu, että "Unohdin salasanani" ja "Lähetä uusi vahvistusviesti" pitäisi olla kirjautumisen yhteydessä eikä rekisteröitymisen yhteydessä. Tai ainakin ensiksi mainittu.  Tästähän puhuttiinko jo MTK:ssa mutta laajemminkin Decidimille voisi tehdä hyvää korjata tämän. Joku ajatusvirhe. Eihän kukaa rekisteröitymislomakkeen täytettyään kaipaa kadonnutta salasanaa.

**Comment by ahukkanen** [comment]
@katjahenttonen Samat linkit löytyvät myös sisäänkirjautumissivulta, jos avaat sen palvelun oman lomakkeen. Jos kirjaudut Tunnistamolla, et tarvitse näitä linkkejä.

Sinänsä, tarvitaanko noita linkkejä rekisteröitymislomakkeella voi olla muutamaakin mieltä. Nämä linkit tulevat suoraan Devise-nimisestä tunnistautumiseen liittyvästä Gem-kirjastosta, millä on 39,5 miljoonaa latausta tällä hetkellä ja sitä on kehitetty vuodesta 2009 lähtien. Uskoisin siis, että niille on aikanaan mietitty jokin peruste, minkä takia ne on laitettu oletuksena molempiin näkymiin.

Toki voidaan erota oletuksista, jos nämä linkit koetaan hämääviksi rekisteröitymislomakkeella.

Toisin sanoen, jos tätä muutetaan, muutosta ei luultavasti hyväksytä Decidimiin. Tämä siis pitää kustomoida.

**Comment by katjahenttonen** [comment]
Saa olla ilman muuta molemmissa näkymissä. Tärkeintä on siis että se että ne löytyy myös kirjautumisnäkymästä, siitä Decidimin omasta. Käyttäjät ovat testauslomakkeilla raportoineet kuvatun virheen ja luulin todentaneeni sen. Taisi olla ajatusvirhe minun päässä. :)

**Comment by katjahenttonen** [comment]
Juttelin viime perjantaina visuilmeen muutoksista N2 viestintätoiminton kanssa.  He tekevät omastadi-palvelun visut tämän viikon aikana.  Pääosin muutokset ovat värien tai kuvien vaihtamista, eli eivät edellytä kustomointia.  Etusivulle pitäisi kuitenkin heidän näkemyksensä mukaan saada kolme pienempää lisäkuvaa nykyisen ison kuvan alle.   Oletan, että tämä kustomoinnilla onnistuu jos nähdään kokonaisuuden kannalta tarpeelliseksi?  Asiasta pitää vielä käydä sisäinen keskustelu sitten kun heidän ehdotuksensa tulee.

**Comment by ahukkanen** [comment]
@katjahenttonen Muokkasin tuota aloitusta ja lisäsin siihen tähän liittyvän tehtävälistan. Lisää toki, jos jotain puuttuu.

**Comment by katjahenttonen** [comment]
Kiitos näistä!  Etusivun "tärkeän sisältöbannerin" otsikkotekstin sekä  yläpalkin OmaStadi-tekstin jos saisi skaalautumaan mobiilinäytöillä pienemmäksi niin näyttäisi paremmalta myös puhelimella.
