### ISSUE TITLE
Suunnitelmien tai niissä olevien kommenttien poistaminen tai piillottaminen ei toimi

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#70]
Suunnitelmien tai niissä olevien kommenttien poistaminen tai piillottaminen ei toimi. En ole vielä päässyt kiinni logiikkaan miksi joskus toimii ja joskus ei.

**Comment by ahukkanen** [comment]
Ilmoitukseen liittyvän kommentin piilottaminen ei toimi enää sen jälkeen, kun se on ilmoitus on kerran jo todettu aiheettomaksi painamalla hallintapaneelista sitä "Poista ilmoitus" -painiketta.

Tällöin järjestelmä jättää raportoinnin silti elämään järjestelmään, jotta samaa kommenttia ei enää ilmoitettaisi montaa kertaa uudestaan aiheettomasti. Kaiketi tämä on ollut ideana toiminnallisuudessa alun perin.

Decidimin seuraavassa versiossa 0.17 tämä on muutettu niin, että tuo "Poista ilmoitus" -painike poistaa sen oikeastikin, jolloin sen uudelleenilmoittaminen ja piilottaminen tulee jälleen mahdolliseksi.

**Comment by ahukkanen** [comment]
Tähän liittyvä issue Decidimin repositoriossa: https://github.com/decidim/decidim/issues/3573

Kyseisessä issuessa ongelma koskee samanlaisen kommentin piilottamista, mutta loogisesti kyseessä on sama ongelma riippumatta yritetäänkö sitä piilottaa vai ilmoitusta poistaa.

Tämä tosiaan näyttää olevan korjattu kehitteillä olevaan versioon (0.17).
