### ISSUE TITLE
Tykkäystä tai alaspeukutusta ei voi poistaa

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#71]
Decidimissä jonkun päivityksen munka  näyttäisi tulleen ongelma, että tykkäystä tai alaspain peukutusta ei voi poistaa. Ihmiset klikkailee näitä joskus vahingossa.

**Comment by ahukkanen** [comment]
Metadecidimissä issue tähän liittyen:
https://meta.decidim.org/processes/bug-report/f/210/proposals/14310

**Comment by katjahenttonen** [comment]
Ok. Jäädänkö odottamaan heidän korjausta vai korjataatko itse?  Joskushan nuo tulee aika nopeastikin Barcelonan päästä mutta yleensä kestää...

**Comment by ahukkanen** [comment]
Odotetaan tuohon bugiraporttiin ensin kommenttia, niin voidaan korjata coreen, jos ovat samoilla linjoilla.

**Comment by ahukkanen** [comment]
Näyttäisi, että tämä on OK heidän puolestaan. Issue on siirtynyt GitHubiin:
https://github.com/decidim/decidim/issues/5033

**Comment by ahukkanen** [comment]
Pull request coreen: https://github.com/decidim/decidim/pull/5042
