### ISSUE TITLE
Sähköpostiviestit mukaan termikustomointiin

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#72]
Decidimin käyttäjille lähettämät sähköpostiviestit pitäisi saada myös muutetettua termikustomointikomponentin kautta. Onnistuuko?

**Comment by ahukkanen** [comment]
Termikustomointikomponentti toimii myös nyt taustaoperaatioissa, kuten sähköpostin lähetyksessä. Taustaoperaatoissa voi kuitenkin edelleen olla teknisiä rajoituksia sen suhteen, miten hyvin niitä saa rajattua esim. osallisuustilan tai komponentin mukaan.

Ainakin ne ilman rajoituksia olevat kustomoinnit kuitenkin toimivat melko suurella todennäköisyydellä nyt myös taustaoperaatoissa, kuten sähköpostien lähetyksessä.
