### ISSUE TITLE
Suunnitelmamoduli: Käyttäjien valmiiksi merkintä pois tai konfiguroitavaksi

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#73]
Suunnitelmamoduli: Poistetaan "Merkitse valmiiksi" painike käyttäjiltä kokonaan pois tai tehdään se konfiguroitavaksi (lisätään mahdollisuus kytkeä päälle tai pois).

**Comment by ahukkanen** [comment]
Tälle on nyt konfiguraatiovalinta suunnitelmakomponentissa ja oletuksena se on pois päältä.
