### ISSUE TITLE
Suunnitelmamoduli: Ilmoitus käyttäjälle että suunnitelmaa ei voi muokata

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#74]
Kun suunnitelma on merkitty valmiiksi niin käyttäjälle pitäisi näyttää suunnitelman kohdalla esim. ilmoitus "Suunnitelma arvioinnissa, muokkaaminen estetty" tms.   Onnistuuko tämä helposti? Ideaalisti ilmoitus näkyisi lähellä kohtaa, jossa on ollut aiemmin muokkauspainike mutta voi olla muuallakin.

"planen beräknas, redigering är inte tillåten"
"the plan is being evaluated,  editing not allowed"

**Comment by ahukkanen** [comment]
Nyt kun suunnitelma merkitään valmiiksi, niin se siirtyy automaattisesti tilaan "Arvioitavana". Ennen varsinaista arviointia tämä viesti näytetään käyttäjille ja muokkausnappi näkyy disabloituna. Jos disabloitua nappia painaa, siitä avautuu popup, jossa lisää tekstiä.

Kyseinen teksti ja disabloitu nappi näkyvät tilanteessa, jolloin suunnitelma on:
a) Arvioitavana
JA
b) Siihen ei ole vielä vastattu käyttäen vastaustoimintoa.

Sen jälkeen, kun suunnitelmaan on vastattu, ei enää nappia tai tekstiä näytetä.
