### ISSUE TITLE
Suunnitelma ei päivity  - virheilmoitus Liite 2 ei voi olla sisällötön

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#75]
Käyttäjä ei onnistu päivittämään suunnitelmaa jossa on useita liitteitä.  Ei ole helposti toistettavissa, mutta selkeä bugi.  Käyttäjän kuvaamat videot virhetilanteesta lähetetty sähköpostitse.

**Comment by ahukkanen** [comment]
Tämä näyttäisi olevan IE11-ongelma. Kyseisessä selaimessa on sellainen "ominaisuus", että se ei ymmärrä, että `<template>` -tägin sisäiset asiat eivät ole osa lomaketta, vaan kokonaan erillään siitä, kuten modernit selaimet ymmärtävät. Tästä johtuen IE siis luulee, että tyhjä esimerkkitemplate on ensimmäinen liite. Kuten videostakin näkyy, niin IE luulee ensimmäistä näkyvää liitettä järjestysnumeroltaan toiseksi (`Liite #2`).

Mietimme tähän jotain ratkaisutapaa... Väliaikaisratkaisuna voi pyytää käyttämään jotain muuta selainta kuin IE:tä.

**Comment by katjahenttonen** [comment]
Kiitos tiedosta.  Tämä asia tulee varmasti vastaan myös Ideapaahtimon puolella, jota lähes kaikki käyttävät IE:llä (koska menevät sinne joko sähköpostistaan tai intrassa, mitkä kummatkin avaavat IE:n meillä).

**Comment by ahukkanen** [comment]
Tämä on korjattu.
