### ISSUE TITLE
Ohjeosio ei näy prosessin johtantosivulla

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#76]
Prosession ohjeosio (Asetukset --> Ohjeosio) ei toimi nyt meidän instanssissa sanoin kuin Metadecidimissä.  Metadecidimin toiminaltalogiikka ohjeosiolle olisi se mitä meilläkin haluttaisiin.  Onko tämä meidän omien kustomointien aiheuttama bugi vai jo fiksattu bugi pääversiossa?

Eli MetaDecidimissä ohje-osio (sininen laatikko jossa teksti "participatory process is...") näkyy sekä prosessisivulla https://meta.decidim.org/processes että lisäksi jokaisen prosessin johdantosivulla erikseen, esim. https://meta.decidim.org/processes/bug-report

Omastadi-alustalla samainen osio (sininen laatikko jossa teksti "ehdotuksia tehdään...") näkyy prosessi sivulla https://omastadi.hel.fi/processes mutta
ei yksittäisen prosessin alla, esim.  https://omastadi.hel.fi/processes/omastadi-koillinen

**Comment by ahukkanen** [comment]
Tämä näyttäisi olevan joo näkymäkustomointien takia.

**Comment by ahukkanen** [comment]
Tämä on korjattu. Ainoastaan tämä ei siis toiminut siinä prosessin "etusivulla" (Tietoa).
