### ISSUE TITLE
Liitteen otsikko sisällöksi alt-teksteihin

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#77]
https://meta.decidim.org/processes/roadmap/f/122/proposals/14329

**Comment by ahukkanen** [comment]
Pull request coreen: https://github.com/decidim/decidim/pull/5043

**Comment by katjahenttonen** [comment]
Suljen tämän.  Jos jostain syystä PR:ää ei hyväksytä ja asiaan pitää palata niin avaatko @ahukkanen itse uudelleen?

**Comment by ahukkanen** [comment]
Uskon vahvasti, että se hyväksytään. Siellä on vain rikkoutuneita testejä, jotka pitäisi korjata. Katson niitä tänään.

**Comment by ahukkanen** [comment]
Pull request on hyväksytty ja mergetty coreen.
