### ISSUE TITLE
Julkaisemattomat suunnitelmat pois hallintapaneelin listauksesta

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#78]
Julkaisemattomien suunnitelmien ei pitäisi näkyä hallintapaneelin listauksessa, mutta pitäisi olla jonkin tapa tietää että onko suunnitelmia kenties jäänyt paljon julkaisematta.

"julkaisemattomien ei pitäisi näkyä listauksessa
voisi olla alakulmassa vain jokin luku esim. "Julkaisematta: x kpl"
samaan tapaan kun äänestyksessä voi seurata sitä, kuinka moni on äänestänyt loppuun asti ja kuinka moni on jättänyt äänensä vahvistamatta"

**Comment by ahukkanen** [comment]
Tämä on nyt korjattu ja näkymän alalaidassa näkyy nyt kokonaismäärät myös julkaisemattomista. Listauksessa vain julkaistut.
