### ISSUE TITLE
Prosessiryhmät etusivulle

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#80]
Etusivulle pitäisi saada näkymään prosessiryhmät prosessien sijaan.  Prosessiryhmän kortit pitäisi mielellään näyttää samalta kuin etusivun prosessit nyt (eli olla koko näytön pituisia), mutta myös toisen muotoiset pienemmät kortit kelpaavat (jos sellainen toteutus on jo valmiiksi olemassa).

Prosessiryhmän korttia klikkaamalla pitää päästä sivulle, jolla näkyvät vain kyseisen prosesessiryhmän prosessit, tapahtumat yms. Siis tähän näkymään: https://osallistu.hel.ninja/processes_groups/3.

**Comment by ahukkanen** [comment]
Tällaisen moduulin olemme aikaisemmin kehittäneet, missä ryhmät tulevat näkyviin pienempinä kortteina:
https://github.com/mainio/decidim-module-process_groups_content_block

Prosessiryhmän kortti tosin on tyyliltään hieman eroava, eli siinä näkyy se ns. "korttipino", joka on esim. näkyvillä Ninjassa prosessit-sivulla:
https://osallistu.hel.ninja/processes

Tuota moduulia voidaan toki jatkokehittää myös siten, että tyyli olisi mahdollista muuttaa sisältöblokin asetuksista tuollaiseksi leveäksi, kuten nykyään korostetuilla prosesseilla.

**Comment by ahukkanen** [comment]
Tämä on nyt asennettu ninjaan, missä sitä voi testata.

Muokkasin hieman kortin tyyliä vastaamaan paremmin tuota leiskaa.
