### ISSUE TITLE
Suomi.fi autorisointi Decidimiin

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#81]
Liitetään Decidimiin suomi.fi autorisointi. Kaupunkilainen tunnistetaan suomi.fi palvelussa ja VRK:n tietokannasta haetaan seuraavat tiedot: hetu, etunimi, sukunimi, postinumero, äidinkieli, kotikunta, syntymäaika (jonka saa toki myös hetusta).  Henkilö voidaan autorisoida jos kuntokunta=Helsinki ja syntymäaika<=31.12.2007 (henkilö täyttänyt tai täyttää tänä vuonna 12 v). Muut tiedot tallennetaan myöhempää käyttäjäprofiiliin myöhempää käyttöä varten.

**Comment by katjahenttonen** [comment]
Lisätietoa:
[suomifi-tunnistatuminen.docx](https://github.com/City-of-Helsinki/decidim-helsinki/files/3306449/suomifi-tunnistatuminen.docx)

**Comment by katjahenttonen** [comment]
Huomasin että määrittelyssä puuttui muutamia VRK:n tietokannasta haettavia kenttiä.  Laitoin päivitetyn dokumentin liitteeksi, lisätyt asiat punaisella.
[suomifi-tunnistatuminen-updated.docx](https://github.com/City-of-Helsinki/decidim-helsinki/files/3445809/suomifi-tunnistatuminen-updated.docx)

**Comment by ahukkanen** [comment]
Suomi.fi autorisointi on nyt valmiina testattavaksi ja löytyy ninjasta.
