### ISSUE TITLE
mPassID autorisointi Decidimiin

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#82]
Lisätään Decidimiin mPassId-autorisointi. mPass-tunnistuksen yhteydessä tietokannasta haetaan henkilön kotikunta ja luokka-aste.  Omastadissa henkilö voidaan autorisoida jos hänen kotikuntansa on Helsinki ja hän opiskelee 7-9 luokalla peruskoulussa.

**Comment by katjahenttonen** [comment]
[mPassID-tunnistatuminen.docx](https://github.com/City-of-Helsinki/decidim-helsinki/files/3306441/mPassID-tunnistatuminen.docx)

Tarkempi määrittely mPassId-tunnistautumisen yhteydessä haettavista tiedoista ja äänioikeudesta.

**Comment by katjahenttonen** [comment]
Tähän vielä @ahukkanen  pieni tarkennus: em. dokumentissa mainittujen tietokenttien lisäksi pitäisi vielä tarkistaa rooli, eli että kyseessä on nimenomaan oppilas eikä esim. opettaja tai vanhempi.  Tietomalllista näyttäisi löytyvän kenttä "Role" tätä varten.
https://tietomallit.suomi.fi/model/mpass/Role/28b8b80b-d0f3-46dd-92c4-ec920955b3f5

**Comment by ahukkanen** [comment]
MPASSid autorisointi on nyt valmiina testattavaksi ja löytyy ninjasta.

**Comment by katjahenttonen** [comment]
@ahukkanen  tätä on nyt muutettu siten että kertalleen lisätyt vitosluokat tiputetaan pois äänestyksestä, eli luokka-asteen pitää olla 6-9.  Pahoittelen moninkertaista veivaamista!

**Comment by ahukkanen** [comment]
Autoriosointitavan tarkastusta on muutettu siten, että vain 6. luokkalaiset ja ylöspäin voivat äänestää.
