### ISSUE TITLE
Prosessien korostaminen, joissa henkilö on äänioikeutettu

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#83]
Käyttäjän näkymässä pitäisi selkeästi erottua ne prosessit (osbussa suurpiirit, Ruudissa ruutialueet), joissa hänellä on äänioikeus. Miten tämä tehdään?

**Comment by ahukkanen** [comment]
Tätä varten on nyt olemassa oma moduulinsa, johon käyttäjät voidaan linkata ja joka pyöräyttää käyttäjän autorisoinnin läpi ja tämän jälkeen päästää äänestämään. Tämä löytyy ninjasta ja osoitteesta `/budgeting`. Tähän voi linkata myös esim. etusivun bannereista tai koko sivun kattavasta ylhäällä näkyvästä huomioelementistä (lisätty ninjaan).
