### ISSUE TITLE
Toimipisteessä tapahtuma autorisointi Decidimiin

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#84]
Decidimin on lisättävä autorisointitapaa, joka mahdollistaa henkilön tunnistautumisen toimpisteessä (tai olemassa olevaa tapaa on muokattava Helsingin kaupungin tarpeita vastaavaksi). Liitteenä on erittäin lyhyt määrittely asiasta.
[henkilökohtainen-tunnistatuminen.docx](https://github.com/City-of-Helsinki/decidim-helsinki/files/3445824/henkilokohtainen-tunnistatuminen.docx)

**Comment by ahukkanen** [comment]
Toimipisteautorisointi on nyt myös testattavana ninjassa. Toimii sieltä hallintapaneelin "Esiintymiset toisena käyttäjänä" -osiosta.

**Comment by katjahenttonen** [comment]
äidinkielen voisi poistaa koska tietoa saatu VRK:lta, näin pienen porukan äidinkieltä tuskin kannattaa tilastoida kun suremmasta massasta ei saatu vastaavaa tietoa
jos kentän poistamisesta on vaivaa niin sen voi myös muuttaa vapaa-ehtoiseksi

**Comment by katjahenttonen** [comment]
Onko logiikkaa mahdollista korjata siten, että kun uusi hallittu käyttäjä on kerran luotu sen voisi ottaa uudestaan haltuun painamalla "Esiinny käyttäjänä". Esim. etsin tuolta "Outi osbudemon" ja painan "Esiinnyt käyttäjänä" --> tulee sama tyhjä tietoikkuna kuin uutta käyttäjä luodessa.

**Comment by katjahenttonen** [comment]
Käyttäjän kotipaikka on Helsinki voisi olla oletuksena täpättynä jos sellaisen toteuttaminen on helpooa

**Comment by ahukkanen** [comment]
Äidinkieli- ja "kotipaikka Helsinki" -kentät on poistettu toimipisteautorisoinnin lomakkeelta, uusi versio on testiympäristössä. Poistin kokonaan tuon "kotipaikka Helsinki" -kentän, koska jos se on suoraan valittuna, sillä ei mielestäni ole mitään virkaa lomakkeella.

Tämän alkuperäinen tarkoitus oli nimenomaan vaikeuttaa täyttöä, jotta virkailija muistaisi aina varmistaa, että kotipaikka on Helsingissä. Jos täppä on valmiiksi valittuna, sillä ei mielestäni ole mitään virkaa.

**Comment by ahukkanen** [comment]
Tuohon jo luotuun käyttäjään:

Tämä on Decidimin ominaisuus, että tiedot pitää jokaisella kerralla syöttää uudestaan. Tällöin voidaan paremmin pitää huoli siitä, että käyttäjä on jokaisella esiintymiskerralla oikeasti tunnistettu.

Tästä puhuimmekin jo Slackissa, että tämä tuskin aiheuttaa ongelmaa oletetulla määrällä toimipisteeseen tulevista henkilöistä. En itse suosittelisi muuttamaan tuota core-logiikkaa tämän osalta.

Jos tunnistus kuitenkin halutaan tehdä toisella koneella kuin itse äänestys, niin pitäisi miettiä jonkinlaista kertakirjautumistapaa, jossa tuo toimipisteautorisointi loisi kertakäyttösalasanan, jolla voisi kirjautua Decidimiin kerran uuden kirjautumistavan kautta. Tämä luonnollisesti tarkoittaisi myös lisää työtä tämän suhteen.

**Comment by katjahenttonen** [comment]
Tämä on kunnossa, ei tarvitse avata uudestaan.
