### ISSUE TITLE
Omastadi-sivun footerissa tulee virhe jos painaa Helsingin kaupungin logoa

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#85]
Helsingin kaupungin logoa klikatessa Omastadi-sivun footerissa tulee virhe "Etsimääsi sivua ei löydy"  Logon pitäisi viedä joko Helsingin kaupungin sivuille www.hel.fi (tai ei minnekään).

**Comment by ahukkanen** [comment]
Näyttäisi, että tämä oli muutettavissa sieltä konfiguraatioista, "organisaation virallinen URL-osoite". Tästä puuttui `https://` edestä, minkä takia se ei toiminut oikein.

**Comment by katjahenttonen** [comment]
Sori, en tajunnut, kiiots!
