### ISSUE TITLE
Palvelimelle pgaudit

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#86]
Asennetaan Decidim-tuotantopalvelimelle pgaudit  tai vastaava  ohjelmisto VRK:n vaatimusten täyttämiseksi. Puhuimme tästä palaverissa 20.8.

**Comment by ahukkanen** [comment]
Tuotantopalvelimelle on asennettu pgaudit ja se logittaa tälläkin hetkellä tapahtumia.

Pgaudit ei oletuksena logita mitään auditointilogiin, mutta OmaStadin tuotantoympäristölle auditointilogitus on otettu käyttöön taululle `decidim_authorizations`, mihin tuo Suomi.fi:stä tuleva metadata tallennetaan.

Mikäli joku tietokantakäyttäjä tekee kyselyitä kyseiseen tietokantaan (luku, kirjoitus, päivitys, poisto), PostgreSQL:n logiin ilmestyy seuraavanlainen rivi esimerkiksi lukutilanteessa:

```
2019-10-02 08:00:00.000 EEST [123] username@database_name LOG:  AUDIT: OBJECT,2,1,READ,SELECT,TABLE,public.decidim_authorizations,"SELECT  ""decidim_authorizations"".* FROM ""decidim_authorizations"" WHERE ""decidim_authorizations"".""decidim_user_id"" = $1 LIMIT $2","1,11"
```

Tältä riviltä näemme seuraavat tiedot:

- Milloin tietoa on kysytty, kirjoitettu, päivitetty tai poistettu auditoitavasta taulusta
- Tietokantaprosessin ID, joka kyselyn on tehnyt (esimerkkitapauksessa `123`)
- Kuka tietokantakäyttäjä tämän kyselyn on tehnyt
- Auditointilogin tyyppi (näissä tapauksissa aina `OBJECT`)
- Tietokantakyselyn ID ja alakyselyn ID (statement ID, sub statement ID)
- Kyselyn luokka (esimerkkitapauksessa `READ`), ks. [pgaudit dokumentaatio](https://github.com/pgaudit/pgaudit#pgauditlog)
- Auditoitavan komennon tyyppi (esimerkkitapauksessa `SELECT`)
- Auditoitavan "olion" tyyppi (esimerkkitapauksessa `TABLE`)
- Auditoitavan "olion" nimi (esimerkkitapauksessa `public.decidim_authorizations`)
- Tietokantakysely, jonka käyttäjä on tehnyt ja jonka kautta auditointilogi on kirjattu
- Tietokantakyselyssä käytetyt parametrit

Auditointilogiin tallentuu luonnollisesti myös kaikki Decidim-applikaation tekemät kyselyt tuotantoympäristössä. Myös kyselyt, joissa tuo autorisointitaulu `decidim_authorizations` on ollut osana (esim. kyselyliitoksen kautta) kirjautuvat auditointilogiin.

Auditointilogit voi hakea logitiedostosta normaaleilla tekstinkäsittelytyökaluilla, esimerkiksi grepillä seuraavasti:

```
$ grep 'AUDIT:' /var/log/postgresql/postgresql-x.x-main.log | less
```
