### ISSUE TITLE
Vakava virhetilanne kun kahdella hallitulla käyttäjällä on sama nimi

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#88]
Kun lisätään uutta hallittua käyttäjään niin lomakkeessa on ensimmäisenä kohta "nimi" (mikä tarkoittanee oikeasti uniikkia käyttäjätunnusta?).  Jos tähän syöttää nimen (esim. se "Matti Virtanen"), joka käyttäjätietokannasta löytyy ennestään, niin ohjelma ei luo uutta käyttäjätiliä vaan päivittää ja ottaa haltuun toisen samannimisen henkilön käyttäjätilin (vaikka henkilötunnus on eri).  Mitään varoitusta ei tule ennakkoon tai jälkikäteen.  Melko fataali ongelma käyttötilanteen kannalta koska saman nimisiä ihmisiä on paljon.

**Comment by ahukkanen** [comment]
Tämä vaikuttaisi olevan Decidimin core-bugi. Tämä ei suoranaisesti liity tähän autorisaatioon, vaan tuohon uuden hallitun käyttäjätilin luontiin. Itse autorisaatio on uniikki (perustuen HETU:uun), mutta bugi on hallitun käyttäjätilin luonnissa.

Bugi löytyy coresta seuraavilta riveiltä:
https://github.com/decidim/decidim/blob/c097e3b9f24c151aee5e3cf94a5f6eab88f4685a/decidim-admin/app/controllers/decidim/admin/impersonations_controller.rb#L77-L87

Olit aivan oikeilla jäljillä tuon "uniikin käyttäjätunniksen" osalta, joskin kyseinen kenttä ei varsinaisesti ole se uniikki käyttäjätunnus, vaan tunnuksen julkisesti näkyvä nimi.

Kyseinen toiminto siis etsii käyttäjän tietokannasta nimen perusteella hallittuja käyttäjiä ja jos hallittu käyttäjätili jo löytyy samalla nimellä, kyseinen käyttäjätili otetaan haltuun luomatta uutta. Uskoisin tämän olevan bugi (vaikka en tiedäkään, miten tuota ominaisuutta on Barcelonassa käytetty).

Tämä on kuitenkin korjattava Helsingin instannsiin, mutta pitänee korjata myös coreen. Core-päivitys tuskin kuitenkaan ehtii varsinaiseen äänestykseen, minkä takia tämä pitää korjata erikseen Helsingin instanssiin.

Toki tuon bugin voi ohittaa toistaiseksi nimeämällä hallitut käyttäjät uniikilla tavalla, mutta korjataan.

**Comment by ahukkanen** [comment]
Selvennyksenä vielä siis, että tuo Nimi-kenttä viittaa siis siihen "julkiseen nimeen", joka näytetään esim. käyttäjien jättämien ehdotusten tai kommenttien vieressä. Sen ei siis ole pakko olla oikea nimi.

Uniikki käyttäjätunnus generoidaan tuon nimen perusteella, mutta sen pitäisi toimia jo nykyisellään oikein, vaikka samannimisiä käyttäjiä olisikin. Nimimerkin perään vain lisätään juokseva numero niin kauan, että vapaa tunnus löytyy.

**Comment by ahukkanen** [comment]
Bugiraportti Metadecidimissä:
https://meta.decidim.org/processes/bug-report/f/210/proposals/14764

**Comment by katjahenttonen** [comment]
@ahukkanen  hyvä jos tämä saadaan korjattua. Meillä on aika iso porukka luomassa noita tunnuksia (ryhmää on laajennettu) eikä  liene realistista saada nimistä uniikkejä pelkällä ohjeistamisella, eli tosiaankin pitäisi tapahtua palvelun päässä esim. juuri lisäämällä numeroita käyttäjätunnukseen.

**Comment by ahukkanen** [comment]
@katjahenttonen Tuo numeroiden lisääminen tapahtuu jo nykyään. Tosin huomasin, että sekin lienee rajoitettu kahteen numeroon, eli saman nimen perusteella voi olla vain kolme käyttäjää. Tuotakin pitänee hieman kasvattaa esim. kymmeneen, jos se pitää paikkansa.

Tämä bugi liittyy siihen, että hallittu käyttäjä haetaan nimen perusteella tietokannasta. Saman nimisiä henkilöitä sinne voi toki syöttää.

**Comment by katjahenttonen** [comment]
@ahukkanen  tuo ei ole ongelma jos liittyy vain hallittujen kyttäjien hakemiseen tietokannasta, sehän ei muutenkaan toiminut ihan oikein joten sovittiin että sen voi jättää.  Tein tämän virheilmoituksen Riikan raportin perusteella, tarkistan vielä itse.

**Comment by ahukkanen** [comment]
Tästä on nyt tehty pull request coreen:
https://github.com/decidim/decidim/pull/5318

Tämä on patchatty myös Helsingin instanssin develop-branchiin, josta päivitykset menevät testiympäristöön. Testiympäristössä pyörii nyt patchatty versio.

Korjaus toimii siten, että:
1. Jos hallitulle käyttäjälle on jo aikaisemmin luotu uniikki identiteetti (perustuen henkilötunnukseen), kyseinen hallittu käyttäjätunnus otetaan haltuun.
2. Jos saman uniikin identiteetin (perustuen henkilötunnukseen) perusteella on luotu aikaisemmin ei-hallittu käyttäjä, hallitun käyttäjäsession aloitusta ei sallita, koska ei haluta, että oikeita käyttäjiä voi ottaa tätä kautta haltuun.
3. Jos uniikkia identiteettiä ei ole, luodaan uusi hallittu käyttäjä ja aloitetaan uusi sessio kyseiselle käyttäjälle.

Olin väärässä tuosta, että voisi olla vain kolme käyttäjää samalla nimellä automaattisesti generoiduista tunnuksista (luin logiikkaa väärin). Tuota etsintää jatketaan niin kauan, että uniikki tunnus löytyy.

**Comment by ahukkanen** [comment]
@katjahenttonen Luulen, että emme ihan ymmärrä toisiamme tuon käyttäjätunnus-asian osalta, mutta siis selvennyksenä vielä, että nyt sen pitäisi käsitykseni mukaan toimia nyt kaikissa tilanteissa oikein.

Uuden hallitun käyttäjäsession luontilomakkeella kenttä "Nimi" viittaa siis kyseisen käyttäjän alustalla näkyvään julkiseen nimeen.

Julkisen nimen perusteella luodaan automaattisesti uniikki käyttäjänimi, kuten muissakin ulkoisissa kirjautumistavoissa (Suomi.fi, MPASSid, Facebook, jne.).

Tämä luodaan seuraavasti:

- Otetaan käyttäjän nimitieto
  * Esim. `Harri Helsinkiläinen`
- Muutetaan nimi pieniksi kirjaimiksi
  * Tulos: `harri helsinkiläinen`
- Muutetaan kaikki ASCII:n ulkopuoliset erikoismerkit (kuten "ä", "ö") vastaaviksi ASCII-merkeiksi
  * Tulos: `harri helsinkilainen`
- Muutetaan kaikki välilyönnit alaviivoiksi
  * Tulos: `harri_helsinkilainen`
- Lyhennetään nimimerkkiä loppupäästä niin paljon, että se on validin käyttäjätunnuksen merkkimäärärajoituksissa, maksimimerkkimäärä on 20 merkkiä)
  * Tulos: `harri_helsinkilainen`
- Etsitään, onko tietokannassa jo käyttäjiä samalla nimimerkillä. Jos on, jatketaan generointia seuraavasti:
  * Lähdetään liikkelle numerosta 2
  * Tehdään tästä nimimerkkiin jälkiliite lisäämällä eteen alaviiva, ensimmäiseksi siis kokeillaan `_2`
  * Lyhennetään nimimerkkiä niin paljon, että tämä jälkiliite mahtuu sallitun merkkimäärän rajoissa generoituun nimimerkkiin (maksimimerkkimäärä on 20 merkkiä)
  * Jatketaan etsimistä niin pitkään numeroita ylöspäin, että vapaa käyttäjätunnus löytyy.

Tähän etsintään siis etsittäisiin esimerkin nimimerkillä seuraavasti, kunnes vapaa tunnus löytyy:

- `harri_helsinkilainen_2`
- `harri_helsinkilainen_3`
- `harri_helsinkilainen_4`
- jne.

Etsintä jatkuu niin pitkään kuin numeroita on olemassa Integer-numeroavaruudessa tai se pysähtyy siihen, kun vapaa käyttäjätunnus löytyy.

Tämän pitäisi toimia kaikissa tapauksissa. Hallitun käyttäjän autorisoinnin uniikkius on asia erikseen, se ei ole sidoksissa nimeen tai nimimerkkiin (enää nyt, kun em. korjaus on tehty).

Hallitun käyttäjän uniikkius tarkastetaan autorisointitapaan liittyvällä uniikilla tunnisteella. Helsingin toimipisteautorisoinnissa tämä autorisaation uniikki tunniste luodaan suolattuna tarkastemerkkijonona syötetystä henkilötunnuksesta, jolloin siis voidaan estää äänestäminen samalla henkilötunnuksella uudestaan.

Pahoittelut pitkästä sepustuksesta, mutta yritin selventää, jotta puhutaan samasta asiasta.

**Comment by katjahenttonen** [comment]
Kiitos yksityskohtaisesta selvityksestä, ei sitä tarvitse pahoitella, toki haluan ymmärtää miten vastuullani olevat ohjelmistot toimivat. :) Palaan tähän huomenna.

**Comment by katjahenttonen** [comment]
Testasin tämän viikonloppuna ja nyt näkyi toimivan.  Katson tuon virhekuvauksen ja ymmärsin mitä on korjattu. Asia kunnossa, kiitos!
