### ISSUE TITLE
Yläbanneri puuttuu, kun äänestykseen menee yläpalkin kautta

### ISSUE THREAD

**Issue by riikkamoisio** [City-of-Helsinki/decidim-helsinki#89]
Kun menee äänestykseen (Osallistuva budjetointi 2019 - Täältä pääset äänestämään >) palkin kautta jää yläbanneri pois 
![Banneri_pois](https://user-images.githubusercontent.com/54899310/64263030-adf24f00-cf37-11e9-8254-f861a94e2220.PNG)
Jos puolestaan äänestykseen menee Osallistu valinnan kautta niin banneri on paikallaan
![Banneri_paikallaan](https://user-images.githubusercontent.com/54899310/64263235-fc9fe900-cf37-11e9-8b97-95c6c315f590.PNG)

**Comment by ahukkanen** [comment]
Kyllä, tämä on tarkoituksella.

Jos menee "Osallistu" -valikon kautta, niin banneri ja alavalikko näkyy, koska käyttäjä on löytänyt oikeaan prosessiin.

Jos menee "Osallistuva budjetointi 2019" -pikalinkistä, menee siihen "Yhdistetty budjetointi" -moduuliin, joka ohjaa käyttäjää äänestyksen läpi. Tässä äänestyspaikka valitaan listasta ja mielestäni olisi harhaanjohtavaa näyttää silloin tuo prosessin banneri. Tällöin käyttäjät voisivat helpommin eksyä pois äänestyksestä muille välilehdille.

**Comment by katjahenttonen** [comment]
Pahoittelut, esittelitkin mulle varmaan tätä toiminnallisuutta demotilaisuudessa, mutta se oli mennyt minulta ohi.  Mun pitää vielä keskustellla tästä omstadi-tiimin kanssa että miten he kokevat tämän.  Käytettävyysvaikutus on vähän kaksi puoleinen, toisaalta on hyvä ettei käyttäjä eksi väärillä välilehdille, toisaalta henkilön olisi hyvä nähdä missä prosessissa on äänestämässä.

**Comment by ahukkanen** [comment]
@katjahenttonen Tuo prosessin nimi voidaan tuoda kyllä näkyviin tuohon kyseiseen moduuliin ilmankin sitä koko ylävalikkoa.

Mielestäni olisi ehdottoman tärkeää, että jos käyttäjä käyttää tuota pikalinkkiä, silloin sitä yläbanneria ei näytettäisi.

Nämä ovat kaksi erillistä palvelupolkua. Osa käyttäjistä ehkä löytää itse prosessin, mutta uskoisin, että suurin osa käyttäjistä hyödyntää pikalinkkejä, jos ne nostetaan korostetusti esille (esim. etusivun bannereissa ja tuolla ylhäällä).

**Comment by katjahenttonen** [comment]
Joo, ymmärrän pointin.  Ennustaisin vaan että siitä tulee negapalautetta jos prosessin nimi häviää näkyvistä. Jos prosessin nimen saa näkyviin ilman että näyttää koko yläbanneria niin minusta ratkaisu kuulostaa erinomaiselta.

**Comment by katjahenttonen** [comment]
Suljen tämän, avaan uudet tiketin prosessin nimen näkymisestä  jos/kun se koetaan meillä tarpeelliseksi.
