### ISSUE TITLE
Muutoksia ylävalikkoon

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#9]
Osallistu-rivin sisältö muuttumassa. Odotan, että saan päätöksiä näistä.

**Comment by katjahenttonen** [comment]
Olenko ymmärtänyt oikein, että toistaiseksi ylävalikko on sama Ideapaahtimolle ja OmaStadille.  Tämä tulee varmaan vielä muttumaan mutta seuraava olisi kohtuulinen kompromissi toistaiseksi:

Palvelun nimi (Ideapaahtimo, OmaStadi tms)
Osallistu -> Linkki aktiivisiin prosesseihin
Ohjeet -> kolme alasivua  
(Tapahtumat -> tapahtumalistaukseen, sitten kun tämä on tehty joskus )
Yhteystiedot -> Kaksi alasivua

Olen ymmärtänyt, että alasivujen nimet voi määritellä instassikohtaisesti. Olenhan oikeassa?

**Comment by ahukkanen** [comment]
> Olen ymmärtänyt, että alasivujen nimet voi määritellä instassikohtaisesti. Olenhan oikeassa?

Voi määritellä kyllä.

**Comment by katjahenttonen** [comment]
Ok, hyvä. Älä tee näitä valikkojuttuja vielä. Keskustelen asiasta vielä asianosaisten kanssa huomenna, jospa selvittäisiin tältä osin perusasetuksilla.

**Comment by katjahenttonen** [comment]
Kävimme tänään vielä asiaa läpi.  Jonkin verran valiikkoihin tarvitaan muutoksia.  Prosessit pitäisi muuttaa nimellä "Osallistu" ja Lisätietojen rinnalle yläotsikoksi haluttaisiin nostaa yhteystiedot.

Eli Osallistu-rivi olisi seuraava:

Palvelun nimi (OmaStadi tai Ideapaahtimo)
Osallistu --> Prosessisivulle
Yhteystiedot --> Yhdelle sivulle
Lisätietoja --> Kolme alasivua

Voisiko myös alapalkin sivut irrottaa yläpalkin Lisätietoja kohdasta?  Eli alapalkkiin voisi kussakin instanssissa laittaa kolme vapaavalintaista sivua, jotka olisivat eri kuin yläpalkin Lisätietoja kohdassa. Tällä saisimme riittävästi instassikohtaista kustomoitavuutta, eikä koodia tarvitsisi tältä osin jakaa.

**Comment by ahukkanen** [comment]
@katjahenttonen Onko tuo "Yhteystiedot" -linkki pakollinen? Se voi olla hankalaa tuolla nykyisellä systeemillä, kun näitä ei voi konffata suoraan käyttöliittymästä.

Alapalkin linkit ovat samat kuin mitä näkyy Lisätietoja-sivulla. Voisiko sinne vain lisätä yhdeksi uudeksi sivuksi "Yhteystiedot"?

Decidimissä ei pysty tällä hetkellä luomaan minkäänlaisia navigaatiorakenteita tai staattisten sisältösivujen "sivuryhmiä". Ainoat vaihtoehdot navigaatiorakenteelle ovat:
- Manuaalinen määritys (kovakoodattu)
- Kaikki sisältösivut listattuna (dynaaminen, mutta linkkaa ainoastaan sisältösivuille)

Kovakoodatut linkit ovat ongelmallisia etenkin, kun samaa koodia käytetään useammassa instanssissa (ninja, paahtimo, tuotanto). Jos esim. tuotantoon luodaan sivu nimeltä "Yhteystiedot", se ei sellaisenaan löydy paahtimosta tai ninjasta ja sillä voi olla myös eri ID-numero jokaisessa instanssissa.

Tämä parannus Decidimiin helpottaisi tämäntyyppisiä pyyntöjä huomattavasti:
https://meta.decidim.org/processes/roadmap/f/122/proposals/13126

**Comment by katjahenttonen** [comment]
Kiitos selvityksestä! Jätetään Yhteystiedot-linkki pois toistaiseksi. Yritetään ensin tehdä ao. muutos  Decidimin jos suostuvat. Katsotaan jos sille saisi vielä yhden äänen. :)

**Comment by ahukkanen** [comment]
Tuo termimuutos ylämenuun Prosessit -> Osallistu on toteutettu.

**Comment by ahukkanen** [comment]
Onko tähän liittyen vielä jotain tekemättä, vai voidaanko sulkea?

**Comment by katjahenttonen** [comment]
Voidaan sulkea!
