### ISSUE TITLE
Palaaminen äänestysnäkymästä prosessilistaukseen (käytettävyys)

### ISSUE THREAD

**Issue by riikkamoisio** [City-of-Helsinki/decidim-helsinki#90]
Kun menee ylälinkin kautta niin siellä tulee hienosti että Takaisin listaukseen, jos on jo äänestänyt. Mutta jos ei ole äänestänyt tai menee etusivun kautta projektiin Osbudemo ja sieltä valitsee esim läntinen suurpiiri ja äänestä niin puuttuu paluu projektiin.
Nyt olen mennyt aina pääsivun kautta.
Esim. Tässä ei ole suoraa paluuta
![image](https://user-images.githubusercontent.com/54899310/64406035-6c71b900-d089-11e9-88d4-4a94cb719924.png)
Tähän takaisin
![image](https://user-images.githubusercontent.com/54899310/64406074-8d3a0e80-d089-11e9-88b9-4594f2f55e2f.png)

**Comment by ahukkanen** [comment]
Jos prosessin sisältä halutaan takaisin prosessilistaukseen tai prosessiryhmän listaukseen, niin sama linkki pitäisi varmaan esiintyä kaikilla prosessin välilehdillä.

Ylälinkistä mentäessä siihen ohjattuun äänestykseen tämä on selkeämpi asia, kun siinä ei varsinaisesti olla minkään tietyn prosessin sisällä. Siellä tiedetään jo, missä alueilla henkilöllä on mahdollisuus äänestää ja ollaan rajoitettuna vain äänestyskomponentteihin, jolloin tuo takaisin-linkki on myös paljon selkeämmin toteutettavissa.

@katjahenttonen Mihin kohtaa mielestäsi tuo linkki pitäisi lisätä prosessin sisällä?

Linkki siis näkyisi kaikilla välilehdillä, esim. myös Ehdotukset-välilehdellä. Linkki myös näkyisi äänestyksen aikana, koska tuossa prosessin sisällä ei sinänsä ole mitään kontekstitietoa siitä, mitä kullakin välilehdellä tehdään. Jos tämä ei ole ongelma, voidaan linkki lisätä esim. siihen yläbannerin alapuolelle.

Ohjatussa budjetointimoduulissa paluulinkki näytetään VAIN, jos henkilö on jo äänestänyt valitussa prosessissa.

<hr>

Sitten jälleen pointtina haluaisin nostaa esille sen, että suosittelen vahvasti tekemään kaikki nostot ja ohjaukset suoraan tuohon ohjattuun budjetointimoduuliin (eli siis mihin tuosta ylälinkistä päästään), jolloin toivon mukaan suurin osa löytäisi perille sitä kautta. Voidaan käydä tätä vielä tarkemmin läpi, jos on tarpeen - jos tämä siis ei ole selkeää.

**Comment by katjahenttonen** [comment]
@ahukkanen  kiitos eiköhän tämä nyt ole selkeää selkeää. Katsoin nyt tämän vasta itse kunnolla ja tosiaanhan linkkihän ilmestyy sen jälkeen kun on äänestänyt.  Tuo on minusta ihan hyvä ratkaisu.  Jos ihminen on tullut etusivulta ns. "pitkän kautta" niin hän osannee mennä samaa reitttiä myös takaisin. Meidän pitäänee muuttaa etusivun banneria siten että se myös heittää budjetointimoduliin.

**Comment by katjahenttonen** [comment]
Kävin @ahukkanen  käyttäjäpolkua vielä läpi ja pelkään että tästä "Palaa takaisin" linkistä on tulossa äänestyspolun ongelmallisin kohta. Olisiko mahdollista a) tehdä linkkiä suuremmaksi ja näkyvämmäksi (esim. suurempi fontti ja toinen viesti pois samasta näkymästä) ja b) toteuttaa tämä siten että henkilö voisi palata takaisin myös ennen äänestämistä?  Aiempien  kokemusten perusteella uskon että ihmiset haluavat surffailla ja katsella alueita ennen kuin ovat valmiita antamaan äänensä.

**Comment by ahukkanen** [comment]
Voi sen paluulinkin toki lisätä siihen ylälaitaan.

Mutta miten tuolla varsinaisten prosessien sisällä, halutaanko se sinnekin jokaiselle välilehdelle?

**Comment by katjahenttonen** [comment]
@ahukkanen  kuten puhumme tänään niin homman voisi toteuttaa kuvan tapaan.  Tekstit hieman pienemmiksi. Alempi teksti: "<< Takaisin äänestysaluelistaan".  Jos ei ole vielä äänestetty niin sitten tietysti näkyy vain jälkimmäinen teskti.  Tekstit saisivat näkyä vain budjetoinnin etusivulla, jossa siis on listanäkymä suunnitelmista. 
![takaisinäänestysaluelistaan](https://user-images.githubusercontent.com/39044068/64617914-f0100a80-d3e7-11e9-9fc6-8fc067e539e8.png)

**Comment by katjahenttonen** [comment]
Tässä vielä testatessa huomasin että "Olet jo äänestänyt tässä äänestyksessä" pitäisi piilottaa näytöltä jos henkilö poistaa äänensä.  Kyseinen teksti "Olet jo äänestänyt tässä äänestyksessä" voi hyvin myös olla ilmoitustyyppinen (mikä ikinä onkaan helpoin toteutta( - kunhan "<<Takaisin listaukseen" on vakio ja aina näkyvissä tällä sivulla, riippumatta siitä onko äänestänyt vai ei.

**Comment by katjahenttonen** [comment]
@ahukkanen  olen jutellut tästä tällä viikolla paljon digineuvojien  kanssa ja siihen liittyen muutama pointti: sitä ei lähtökohtaisesti pidetty isona ongelma jos linkki näkyy vasta äänestyksen jälkeen.  Sen sijaan juurikin linkin löydettävyyttä pidettiin isona ongelma. Linkki haluttiin samantyyliseksi mitä Decidimin muut paluulinkit, esim. "<< Näytä kaikki suunnitelmat".  Mutta jos tämä on teknisesti helpompaa toteuttaa siten että linkki ilmestyy vasta äänen vahvistamisen jälkeen niin se on  ihan ok.

**Comment by ahukkanen** [comment]
@katjahenttonen Molemmat toki onnistuvat. Alun perin ajatus oli, että käyttäjä menisi vain yhteen suuntaan, kunnes on äänestänyt.

**Comment by katjahenttonen** [comment]
@ahukkanen joo, siinäkin on kieltämättä etunsa että käyttäjä ei pääsi poistumaan helposti ennen kuin on vahvistanut äänen. Kyselin asiaa tilaisuuden tullen meidän digineuvojilta (he ovat hyviä käytännön käyttettävyysasiantuntijoita) ja mielipiteet  jakautuivat sen suhteen, että pitäisikö linkki näkyä aina vai vaan äänestämisen jälkeen.

**Comment by katjahenttonen** [comment]
@ahukkanen  tein asiasta vielä pikakyselyn stadiluotseille.  Vastanneiden mielestä sinun alkuperäinen ajatuksesi siitä että käyttäjä menee vain yhteen suuntaan on paras.  Jos et ole vielä ehtinyt tuottaa niin mennään siis tuon sinun alkuperäisen ajatuksesi mukaan,  kuitenkin siten että linkki tulee selvästi esille, esim. aiemmin suunnitelemaamme tyyliin.

**Comment by ahukkanen** [comment]
Viestin ja linkin tyyliä on nyt muutettu ja ne on siirretty otsakkeen/kuvan alle.

Linkki ohjaa nyt seuraavasti:
- Jos henkilöllä on muita äänestyskomponentteja, missä voi äänestää (kuten tilanne on ainakin OSBU:ssa), linkki ohjaa takaisin komponenttilistaukseen
- Jos muita komponentteja ei ole valitussa "yhdistetyssä" budjetointiäänestyksessä, linkki ohjaa edelleen takaisin tuohon aikaisempaan näkymään.
- Jos muita komponentteja tai "yhdistettyjä" budjetointiäänestyksiä ei ole, linkki ohjaa takaisin etusivulle.

**Comment by katjahenttonen** [comment]
Kiitos @ahukkanen, logiikka on hyvä. Helsingin Osbu, jossa on kaksi aluetta, toimii kuten pitääkin eli palataan aluelistaan.   Rubussa, jossa on vain yksi alue, niin tällä hetkellä linkki ei näytäisi johtavan mihinkään. Tosin testiympäristön konfigurointi ei vastaa tuotoa, ehkä vika on siinä (?).  Joka tapauksessa tällä alueella kuin äänestään niin "Takaisin listaukseen" linkki ei mene mihinkään. https://osallistu.hel.ninja/budgeting/ruuti-2019/voting/83

**Comment by ahukkanen** [comment]
Totta tosiaan. Melkein veikkaan, mistä tuo johtuu, mutta varmuuden vuoksi - millä käyttäjätilillä näin tapahtuu?

**Comment by ahukkanen** [comment]
@katjahenttonen Uskoisin korjanneeni tämän, mutta tarkastathan vielä, että nyt toimii oikein.

**Comment by katjahenttonen** [comment]
Jep, nyt näytti toimivan oikein.
