### ISSUE TITLE
Ehdotukset rikki tuotannossa ja testissä

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#94]
Sekä osoitteissa omastadi.hel.fi ja osallistu.hel.ninja mihinkään ehdotuksiin ei pääse vaan tulee virhe "Sivua ei löyty" kun yrittää siirtyä ehdotuskortilta varsinaiseen ehdotustekstiin.

**Comment by ahukkanen** [comment]
Tämä on korjattu.
