### ISSUE TITLE
Takaisin listaukseen -linkki johtaa väärään kohtaan

### ISSUE THREAD

**Issue by riikkamoisio** [City-of-Helsinki/decidim-helsinki#96]
Käyttäjä meni etusivun isosta kuvasta (OmaStadi - Helsingin osallistuva budjetointi) äänestämään. Valitsi Suurpiirisi Helsinki projektin ja siellä valitsi suunnitelmat ja äänesti.
Äänestyksen jälkeen painoi Takaisin listaukseen -linkkiä. Päätyi tälläiseen:
![image](https://user-images.githubusercontent.com/54899310/64704521-1c468c80-d4b7-11e9-9a09-8d70059915e9.png)

Oletus että olisi palannut tähän näkymään, josta menikin:
![image](https://user-images.githubusercontent.com/54899310/64704580-34b6a700-d4b7-11e9-9274-4102dcdde657.png)

**Comment by ahukkanen** [comment]
Tämä on myös korjattu, ks. logiikka #90.
