### ISSUE TITLE
Teemat ja ryhmät näkyvät vaikka eivät ole käytössä

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#97]
Osallistumisryhmien sivulla näkyy teemat ja alueet, vaikka kummatkaan eivät ole meillä  käytössä.
![osbu-prosessivu](https://user-images.githubusercontent.com/39044068/64845372-aeaf7300-d612-11e9-9183-26f39b35bfaa.png)

**Comment by ahukkanen** [comment]
Nämä ovat oletuksena näkyvillä kaiketi siksi, että tuo on prosessilistaussivu ja siten jollain prosessilla voi olla oletetusti nämä filtterit käytössä.

Tein kustomoinnin Helsingin instanssiin, joka piilottaa nämä näkyvistä.
