### ISSUE TITLE
Sivutus ei toimi yläpalkista mentäessä äänestykseen

### ISSUE THREAD

**Issue by riikkamoisio** [City-of-Helsinki/decidim-helsinki#98]
Suunnitelmat sivua kohden* parametri ei toimi yläpalkista mentäessä äänestykseen. Jos äänestyksessä enemmän suunnitelmia kuin tässä parametrissä tulee virheilmoitus: 
Palvelimellamme tapahtui virhe
Yritä myöhemmin uudestaan.
Toista kautta äänestykseen mentäessä sivutus toimii.

**Comment by katjahenttonen** [comment]
@ahukkanen päätimme eilen, että näytämme ehdotukset samalla sivulla.  Eli tämän korjaaminen ei ole kiireellistä.
