### ISSUE TITLE
Muutoksia Wilma-kirjautuneiden äänioikeuteen / 2. aste mukaan

### ISSUE THREAD

**Issue by katjahenttonen** [City-of-Helsinki/decidim-helsinki#99]
Osallistuvan budjetoinnin puolella myös toisen asteen opiskelijoiden pitäisi voida tunnistautua mPassID/Wilma:n avulla.  Ehtoja muutetaan seuraavasti:

Jos koulutyyppi on 15,19,21 tai 22 pääsee suoraan äänestämään jos rooli on "oppilas" ja kotikunta "helsinki", luokkatietoa ei tarkisteta

Jos koulutyyppi on 11 tai 12 (peruskoulut), luokka-aste tarkistetaan aiemman määrittelyn mukaisesti, samoin kotikunta (loogista lienisi tarkistaa myös rooli kuten yllä).

Muun tyyppisissä kouluissa opiskelevat eivät voi äänestää.

Ei ole tarvetta  tarkistaa onko koulu listalla, koska myös esim. espoon kouluissa opiskelevat helsinkiläiset voivat äänestää.  Jos koulu ei ole listalla, niin oletussuurpiiri on tyhjä.

Ruuti-budjetoinnin puolelle ei tule muutoksia.

**Comment by katjahenttonen** [comment]
@ahukkanen  avasin tiketin, mutta tätä ei tarvitse vielä muuttaa, odotetaan ensin muutaman testikäyttäjän kirjautumista lukioista ja ammattikoulusta.

**Comment by ahukkanen** [comment]
@katjahenttonen Ym. speksissä on pieni ristiriita:

- Muun tyyppisissä kouluissa opiskelevat eivät voi äänestää.
- Ei ole tarvetta tarkistaa onko koulu listalla,

Ei ole mahdollista pakottaa koulun tyyppiä, jos koulua ei ole pakko tarkastaa listalta. Koulun tyypin saamme näistä listoista, MPASSid ei välitä sitä.

Lisäksi ikätarkastuksessa tarvitsee myös tietää koulun tyyppi, eli 11 tai 19, joissa ikä tarkastetaan luokkatiedon mukaan (luokan numero ei saa olla alle 6). Ikätarkastus siis sivuutetaan, jos koulu ei ole listalla.

**Comment by ahukkanen** [comment]
Seuraavat muutokset on tehty MPASSid:llä tunnistautuneisiin (budjetointiautorisointi):

- Tarkastetaan, että tunnistautuneen roolina on "oppilas"
- Tarkastetaan luokkatieto vain koulutyypeille 11 ja 12 (alakoulut)

Kuten mainittua, niin tuota koulutyypin tarkastusta ei voida tehdä, mikäli ei listata metadataan kaikkia mahdollisia kouluja, joiden oppilailla on äänioikeus. Jos tarkastus lisätään pakotetusti, se rajaa äänestyksestä pois kaikki sellaiset koulut, joita metadatassa ei ole listattu.

Koulutyypin tarkastus on toiminnallisuutena olemassa, mutta se ei ole tällä hetkellä käytössä. Se voidaan ottaa käyttöön, jos näin päätetään (jolloin myös päätetään tiputtaa äänestyksestä pois kaikki koulut, jotka eivät ole metadatassa).

**Comment by katjahenttonen** [comment]
@ahukkanen  pahoittelut, luulin että koulutyyppi tuli  mPassID:stä ja siksi speksi ei olle ihan kassassa. Nyt kun ei kerran pystytä mPassID:ta ammattikouluille, tehdään luokkatarkitus kaikille kouluille, eli luokka-aste on oltava joku 6-9 tai 17-19. Ei tarvitse tarkistaa koulutyyppiä.  Pahoittelut viime hetken muutoksista, selvyyden saaminen ammattikoulujen tilanteeseen ollut haastavaa.

**Comment by ahukkanen** [comment]
Luokka-asteen tarkastus on nyt lisätty kaikille kouluille.

Äänestys sallitaan nyt kaikille, joiden luokkatiedoissa on numero 6 tai suurempi. Toimii siis molemmille näistä esitetyistä tapauksista.
